- .github/pull_request_template.md
Fixes [BCDA-38](https://jira.cms.gov/browse/BCDA-38). Adds a pull request template!
> BCDA-38: Create pull request template

- Makefile
Changed ":" to ";" at end of debug-worker.
> changed from colon to semi-colon at end of debug-worker

- bcda/api.go
- bcda/api_test.go
We don't have any tests for `api.go`!
* Add test for bad request to `bulkRequest()`
* Add jobs to fixtures with different statuses and matching `jobStatus()` tests
* Add `serveData()` test
This starts creating tests for `api.go`, but coverage is not even close to 100%. Will create a part 2 ticket.
None
1) bcda/api_test.go is created and populated with unit tests for bcda/api.go ✔️ 
2) All unit tests pass ✔️ 
3) Code coverage of bcda/api.go is at 100% ❌ 41.2%, additional ticket to follow
Is this a decent start?
> BCDA-253: Develop tests for bcda/api.go

- bcda/logging/middleware_test.go
- bcda/router_test.go
Increase unit test coverage for router.go 
Set os.env to debug
Added tests for the file serving
no PII implications
I got the test coverage up, I am not certain how much I improved our test quality.  This specific file is really hard to test in isolation because it relies Very heavily on the implementations of the end points.  I think we may not go back and improve this and probably should choose to write our tests of this file in other areas.
Please be nice.  This is not my proudest moment. I was severely limited by the .5 story point valuation.
> bcda-260 Unit Tests for Router.go

- bcda/api.go
- bcda/api_test.go
- bcda/responseutils/writer.go
- bcda/router.go
Patients endpoint is actually ExplanationOfBenefit so I renamed the endpoint
find all references to /v1/Patient/... and made them /v1/ExplanationOfBenefit
FIxed the router, some docs and all unit test references.
no,  This is a purely semantic change
unit tests need to keep running
Patient endpoint should be gone and replaced with ExplanationOfBenefit
> BCDA-261 renaming /Patients/ endpoints to /ExplanationOfBenefit/

- bcda/client/bluebutton.go
Blue Button changed their end point.  We need to adjust our data calls in order to account for this.
change URL for Blue Button calls
Abstract base path for future changes to be easier.
just fixed up the issue
no.  It fixes a broken URL scheme.
Just make sure we can still connect to Blue Button.
> bcda-427 new blue Button endpoints

- Dockerfiles/Dockerfile.smoke_test
- test/smoke_test/bcda_client.go
- test/smoke_test/smoke_test.sh
Need the ability to run smoke test against multiple endpoints independently.
Update smoke test so that it runs on a specific endpoint provided by user on command line.
- The diff for the smoke test code looks crazy, but it is due to indentation formatting (removing the for loop).  I only really changed lines 15, 30, 132, 133, 135, and 190
- Create a smoke test script used by the Dockerfile.
- Additional changes required in bcda-ops, which will be sent out separately following testing within the branch in AWS.
None
Passing in Travis.
Please review.
> BCDA-395: Smoke Test Updates

- bcda/api.go
about 7 letters of code comments accidentally got merged out.  I am replacing them
> fixing bad merge issue

- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
When 'bad' tokens are presented we do not log anything about the actual token used.  Logging the token ID might be helpful in some cases when trying to track down a problem.  
Track the token ID for rejected requests under the following cases:
Revoked or blacklisted token
Invalid token (expired most likely)
Mismatch between ACO and Token
Other cases might result in exposure of PII because a user made a request with a "token" value that happened to be PII.
The changes made do log something about a token, but the information logged should be free from PII.
Make requests with invalid tokens and verify that appropriate log messages are generated
Any other appropriate logging or if there are concerns about what is being logged.
> Knollfear/bcda 664 Log bad Token ID's

- ENCRYPTION.md
We need some developer documentation that helps our partners understand how we encrypt files and how they can decrypt files.
Add an ENCRYPTION.md file.
None
A developer who knows nothing (clearly his name is Jon Snow) can write code to decrypt a data file we have encrypted.
@dhgreene please look at the top section re best practices ... do you want to add some things here?
@knollfear please check my description of the steps
@embh @tbellj @alexhova @adhocEric @michaelrobertsutton @epfrankle 
Everyone else ... please read and try to use this readme to implement some part of this yourself, or even just to understand what Ryan's sample go code is doing, or just for general clarity.
I am working on a Java implementation of this.
> BCDA-519: Add ENCRYPTION readme

- bcda/api.go
- bcda/api_test.go
Completed job status results should include an expires header to indicate when the file will no longer be available.
added expires header
added necessary unit tests
added header
added additional check to unit test
no PII is impacted
Run tests
Run job manually and inspect headers.
> knollfear/bcda-709 Add expires header to completed jobs

- bcda-site-static/index.md
some previous changes altered the indentation level causing bad HTML to be created
fixed indent
fixed indent
no PII
CTA section should have a full grey background
BAD:
Good:
> BCCDA-878 Static Site: Fix indentation

- bcda-site-static/user_guide.md
Add Coverage end point documentation to the user guide
just update the userguide.md file
no pii is affected
Elissa viewed the actual page
> BCDA-1170: add coverage endpoint to User Guide

- Gopkg.lock
- bcda/auth/alpha.go
- bcda/auth/api.go
- bcda/auth/backend.go
- bcda/auth/logger.go
- bcda/auth/logger_test.go
- vendor/github.com/sirupsen/logrus/hooks/test/test.go
Updates logging in auth to use structured logging mechanism and record log entries as described in the Tech Spec.
* creates a package global logger configured for structured logging
* adds logging functions that correspond to events from the tech spec
* adds consts appropriate for logging / events
The tech spec discusses operations that emit events. This implementation assigns responsibility for doing the actual logging to individual functions that emit events. The data for those events is provided by the calling code that gathers the data. A tracking_id is among the fields of data; the intent with this id is to provide an identifier that can correlate a set of related events.
*enhances security by providing an audit trail of events. Existing logging is largely focused on error detection. …
> Create base structured logging pattern

- test/postman_test/SSAS.postman_collection.json
Added initial postman collection for SSAS to repo. Intended for team to gather postman dev tests, which will then be the basis for integration tests.
> Add initial postman collection

- .github/pull_request_template.md
This change includes:
- Updates for our pull request template, primarily around the "security implications" section.
- Minor formatting changes, clean up through the pull request template.
Rationale: in making this change, we're hoping to refine our process for identifying and addressing security concerns in our work and make use of pull requests as a channel for communicating those concerns to the rest of the team and project stakeholders.
Since reviewers typically won't see them, I am highlighting guiding questions embedded in the PR template in **bold** below:
**Does the change deal with PII/PHI at all? What should reviewers look for in terms of security concerns?**
1. **YES or NO**: This change adds new software dependencies
**If yes, list the new dependencies and briefly note any …
> [RFC] BCDA-1251: Updates to "security implications" in pull request template 

- bcda/models/SwaggerStructs.go
- bcda/responseutils/writer.go
- bcda/web/api.go
- bcda/web/api_test.go
- bcda/web/router.go
- bcda/web/router_test.go
- test/performance_test/performance.go
- test/performance_test/performance_test.sh
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
- test/smoke_test/bcda_client.go
- test/smoke_test/bulk_data_requests.sh
Fixes [BCDA-2405](https://jira.cms.gov/browse/BCDA-2405)
Problem:
In order to be more FHIR compliant, we needed to add an additional endpoint to our API. The group endpoint as described here: https://hl7.org/fhir/uv/bulkdata/export/index.html#endpoint---group-of-patients is included with these changes making us one step closer to full FHIR compliance.
The new endpoint matches this pattern:
/api/v1/Group/[id]/$export
where _$export? _type_ will be followed by a comma delimited list of FHIR resource types.
Added a new endpoint for Group $export.
bcda/web/api.go - added new api endpoint for group export. (bulkGroupRequest function)
bcda/web/api_test.go - testing logic for validating request
bcda/web/router.go - added new group export route …
> BCDA-2405 Feature: Implemented Group endpoint

- bcda/web/api.go
Occasionally, an ACO will report that a job is marked as `Completed` almost immediately after initiating the bulk data request.  As a result, access to the `ndjson` files results in `404 - File Not Found` errors.
Investigation uncovered that before the job count is updated on the `jobs` table, it is possible for at least one job to be pulled from the queue and completed, resulting in the entire job to be marked as `Completed` almost immediately.  See logic [here](https://github.com/CMSgov/bcda-app/blob/master/bcda/models/models.go#L82-L107).
This race condition bug needs to be addressed by ensuring that the `jobs` table is updated with total job count _before_ the jobs are enqueued.
Modified logic so that the `jobs` table is updated with total job count _before_ the jobs are enqueued. …
> Fix race condition when enqueuing jobs

- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/ssas_middleware_test.go
- bcda/database/connection_test.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/web/api.go
- bcda/web/api_test.go
[New rules](https://github.com/golangci/golangci-lint/commit/bf27481efd4b1916eac1fedac09077dd82dd995f) were recently added to `golangci-lint`: 
- Updated code to adhere to `S1029` and `S1039` static analysis rules.
No PHI/PII is affected by this change.  This is a code improvement task to adhere to latest static analysis rules.
Local validation included `make lint` and `make test`.
Please review.
> Fix issues uncovered by new linting rules introduced in golangci-lint

- .travis.yml
- Dockerfiles/Dockerfile.bcda
- Dockerfiles/Dockerfile.bcdaworker
- Dockerfiles/Dockerfile.documentation
- Dockerfiles/Dockerfile.package
- Dockerfiles/Dockerfile.ssas
- Dockerfiles/Dockerfile.tests
This branch updates the golang base docker images to use the latest (1.14.1) version.
It also updates the version that Travis uses in CI.
* Updating golang from 1.11.5 to 1.14.1
* Updated the golang alpine images to use the latest version available
* Updated debian stretch to buster where applicable
* Updating `Dockerfile.package` to use the alpine image instead of normal image
* Does it make sense to use the full buster image for the tests?
* Does it make sense to use the alpine image for the package?
> Updating golang version in docker base images

- .github/pull_request_template.md
Add checkbox to PR template to address any PHI/PII changes.
Any other details to include in the PR template?
> BCDA 2977: Tweak security section PR template to address PHI/PII change

- bcda/models/SwaggerStructs.go
- bcda/web/api.go
- bcda/web/api_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
Changed the validation for since parameter to reject malformed or inputs
* Changed since validation to use regex provided by the FHIR specification
* Added unit tests to cover edge cases of since parameter
No PII/PHI implications
Tested locally and got a appropriate acceptance or rejection for different `_since` parameters
> BCDA 3048: Since parameter validation

- test/smoke_test/bcda_client.go
Change the logging for smoke tests to be more descriptive
* Changes to logging for smoke tests
Deployed with Jenkins, https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1564/
> BCDA-2540 Updated logging for smoke tests

- bcda/models/models.go
- bcda/models/models_test.go
- bcda/web/api.go
- docker-compose.test.yml
- docker-compose.yml
Applies a priority weight to every job based on what the parameters of query. The lower the priority number, the sooner the job will be completed relative to other jobs in the queue
The `Job` model has a new field `Priority` that is used by que-go when determining the order to start jobs. The value for priority is generated when jobs are added to the queue
* Added priority to the job enqueuing function
* Updated tests to also test for priority
Deployed to dev: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1565/
Is the best place for the logic to determine a job priority? Should it be with the model or somewhere else? Any other tests that should be part of this?
> BCDA-3140: Priority weighting given to jobs

- bcda/models/models.go
Fixing a code smell issue in sonar qube
Cleaning up nested if/else logic
Do we want to merge these changes in or are they unnecessary?
> BCDA-2991: Fix nested if statement code smell

- bcda/responseutils/writer.go
Solves conformance issues with Capabilities Statement
changes export to group export
changes export to patient export
adds bulk data url to instantiates object
removes SMART on FHIR from security
None
- [ N/A] security checklist is completed for this change
- [ X] no PHI/PII is affected by this change
yes
✔ The CapabilityStatement instantiates the bulk-data CapabilityStatement 
✔ Check if "patient-export" operation is defined in the CapabilityStatement 
✔ Check if "group-export" operation is defined in the CapabilityStatement
> BCDA-3114: Fix FHIR Conformance Issues in CapabilityStatement

- bcda/responseutils/writer.go
Errors in the Capabilities statement reported by Aegis testing tool and confirmed via spec reading.
This only changes the errors in bullets 3&4 of the ticket.  bullets 1 &2 were resolved in BCDA 3114
added implementation description
change capabilities statement type to instance
cpb-2: A Capability Statement SHALL have at least one of description, software, or implementation element. (expression : (description.count() + software.count() + implementation.count()) > 0, xpath: count(f:software | f:implementation | f:description) > 0)
CapabilityStatement.implementation.description
Definition 
Information about the specific installation that this capability statement relates to.Control 1..1
Type string
Summary true
bullet 4 is
"kind": "capability",
should be changed to 
"kind": "instance"
per …
> BCDA-3146: Fixed Capabilities Stmt issues for FHIR conformance

- Gopkg.lock
- vendor/github.com/eug48/fhir/models/extension.go
- vendor/github.com/eug48/fhir/utils/http.go
Recent changes to `eug48` FHIR library, from [here](https://github.com/eug48/fhir), are necessary for our application to render a valid Capability Statement.
- Updated `vendor` directory with latest `eug48/fhir` library.
> Minor update to an existing dependency.
Local CI and Travis CI tests are passing.
Please review.
> Update eug48 FHIR library

- bcda/responseutils/writer.go
- vendor/github.com/eug48/fhir/models/extension.go
The Capabilities Statement should have the syntax like this:
we need our output to look like this:
```
"security": {
"extension": [
{
"url": "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris",
"extension": [
{
"url": "token",
"valueUri": "https://bcda.cms.gov/auth/token"
}
]
}
],
```
add a function to the Capabilities stmt to produce the complex extension to the above spec
No
No new dependencies but eug48/fhir was updated by the vendor to fix the errant Extension model.
No
No
No
No
N/A
No
- [ X] no PHI/PII is affected by this change
```
{"resourceType":"CapabilityStatement","status":"active","date":"2020-07-13","publisher":"Centers for Medicare \u0026 Medicaid Services","kind":"instance","instantiates":["https://prod-sbx.bfd.cms.gov/baseDstu3/metadata/","http://hl7.org …
```
> BCDA-1799: Added Complex Extension to Capabilities Statement to Make Token Endpoint Discoverable per Spec

- bcda/responseutils/writer.go
remove invalid operation definitions,and set proper operation definition resource to the valid uri.
FHIR conformance fixes to the metadata operations section.
- change uri of group export operations definition resource
- change uri of patient export operations definition resource
- remove jobs (not an operation)
- remove metadata (not an operation)
- remove version (not an operation)
- remove data (not an operation)
https://chat.fhir.org/#narrow/stream/179250-bulk-data
https://www.hl7.org/fhir/operations.html - Note that metadata, jobs, data, and version are not operations because they don't use $.
No
No
No
No
No
No
- [ X] no PHI/PII is affected by this change
Yes
Nothing specific, but understanding of what constitutes an operation should be understood by the team.
> BCDA 3453 - remove invalid operation definitions,and set proper operation definition resource to the valid uri.

- bcda/models/models.go
This is a follow-up to the first iteration of de-duplicating beneficiaries that might show up in an ACO's attribution list.  The first iteration can be found here: https://github.com/CMSgov/bcda-app/pull/506
In this follow-up iteration, the de-dup query has been optimized to use a sub-query.  This ensures that a large array is not used in the SQL computation, which could result in the following Postgres error:
```
got xxxxxx parameters but PostgreSQL only supports 65535 parameters
```
Details on proposed guidance acquired from [here](https://stackoverflow.com/questions/52712022/what-is-the-most-performant-way-to-rewrite-a-large-in-clause).
Updated de-dup logic to use `id IN (subquery)` instead of `id IN (value [, ...])`
The updated/refactored query handles PHI/PII data.  It has been …
> BCDA-2751: Optimize Beneficiary De-Dup Query to Use a Subquery

- bcda/cclf/cclf.go
1. Need to emit timing metrics for cleaning up CCLF files.
1. Create a new parent timer to measure the time it takes to clean up all CCLF files. This was failing before because the supplied context did not have a timer associated with it.
Validated that cleanupCCLF metrics are appearing on NewRelic
> BCDA-3428 - Adding timing metrics for cleanupCCLF

- unit_test.sh
There are some failing unit tests due to race conditions in the test setup.  This PR will un-block the failing build.  Additional work to parallelize the tests is planned for https://jira.cms.gov/browse/BCDA-3725
```=== Failed
=== FAIL: bcda/client TestBBTestSuite/TestValidateRequest/GetExplanationOfBenefit (2.12s)
bluebutton_test.go:448: 
Error Trace:	bluebutton_test.go:448
Error:      	Received unexpected error:
Blue Button request 21f39f09-dd5c-4806-9b44-156b5ca6b1b5 failed 3 time(s)
Test:       	TestBBTestSuite/TestValidateRequest/GetExplanationOfBenefit
--- FAIL: TestBBTestSuite/TestValidateRequest/GetExplanationOfBenefit (2.12s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference …
```
> Run unit tests in serial

- bcda/web/api.go
- bcda/web/api_test.go
The 500 error response for the job status endpoint was vague and did not provide users with an understanding of what went wrong. This adds a more complete response so users can understand what is happening
* Changed 500 response to include a meaningful response body
> BCDA-3485 Added better 500 HTTP error response

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
Add IncludeAddressFields:true header on patient requests.
See the [request options page](https://github.com/CMSgov/beneficiary-fhir-data/blob/9abb6cb0be85fd5b691be60eb98016a527ebec10/docs/request-options.md) for more information.
1. Added IncludeAddressFields:true header on patient requests.
By supplying this header, we expect to receive detailed address data for the requested beneficiary. See [this page](https://github.com/CMSgov/beneficiary-fhir-data/blob/9abb6cb0be85fd5b691be60eb98016a527ebec10/docs/request-options.md) for more details.
More detailed address data will be returned when callers request the resourceType=patient.
Update our request tests to ensure that IncludeAddressFields:true header is included only on Patient requests.
> BCDA-3903 - Add IncludeAddressFields:true header on patient requests

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
Due to CCLF files not being dropped until halfway through a month there will be an interim period in January were we would be missing Runout CCLF files. To prevent the API from consuming incorrect data, we need to generate these runout files before the end of December using the December CCLF files.
Create a CLI option in `bcdacli` that will take a directory containing CCLF files and clone these files to produce CCLF Runout files (using the proper nomenclature). A jenkins job can then be created and hook into this CLI option (done via a separate ticket).
- Create CLI option `generate-cclf-runout-files` that takes a `--directory` argument
- Create helper functions to Clone the zip files by reading all the CCLF files and generating a new zip file with the proper runout name.
- Read in the …
> BCDA-3968 Feature: CLI for creating CCLF runout files from CCLF Zips

- bcda/cclf/fileprocessor.go
- bcda/cclf/fileprocessor_test.go
- bcda/cclf/testutils/cclfUtils.go
- bcda/cclf/testutils/cclfUtils_test.go
Previously, we updated the ACO config to support a new [TEST ACO pattern](https://github.com/CMSgov/bcda-app/pull/726).  To fully test out that functionality, we will need the ability to create testing CCLF attribution files.  This PR introduces minor changes to the CCLF processing utilities to support the new ACO ID format. 
- update CCLF file processing to support the `TEST\d{3}` ACO ID pattern
> DCGEO-211: updating CCLF parsing to work with the new TEST ACO

- bcda/responseutils/v2/writer.go
- bcda/responseutils/v2/writer_test.go
- Update task endpoint to v2 endpoint
> BCDA-5560: Updated task to v2 endpoint

- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/web/router.go
- Adds the "request_id" field to logs
- Utilizes go-chi middleware with router to create a unique RequestID per request
- Verify logs output field "request_id"
> [BCDA 5671] Added the field request_id to logs

- bcda/client/bluebutton.go
- Removes deprecated method call in tls config
> Removed tls config deprecated method

- bcda/api/requests_test.go
- bcda/api/v1/api_test.go
- bcda/api/v2/api.go
- bcda/api/v2/api_test.go
- bcda/client/bluebutton.go
- bcda/models/fhir/alr/v1/alrfhir.go
- bcda/models/fhir/alr/v2/alrfhir.go
- bcda/responseutils/v2/writer.go
- bcda/responseutils/v2/writer_test.go
- bcda/responseutils/writer.go
- bcda/responseutils/writer_test.go
- go.mod
- go.sum
- Updates go.mod, go.sum to latest fhir go library
- Updates corresponding fhir library code to current practice
- Builds properly
- Unit tests pass
> BCDA-5838: Update go dependencies / FHIR library 

- go.mod
- go.sum
updates sqlbuilder to the latest version. 14.0 had breaking changes
sql-builder version updated to v1.14.1
This can be tested by running :
1. make docker-build  
2. docker compose up
3. use an endpoint on localhost (i.e ([http://localhost:3000/_health]) )
> BCDA-5839 Identify Refactoring Approach for SQL Builder Go Library dependencies that break changes

- ops/release.sh
Post Jenkins update, git tag started failing the release tag build.
- Remove call to `git tag` command
Successful run of Tag and Release
> Remove unused git tag command

- bcda/api/testdata/acos.yml
- bcda/api/testdata/cclf_beneficiaries.yml
- bcda/api/testdata/cclf_files.yml
- bcda/service/testdata/acos.yml
- bcda/service/testdata/cclf_beneficiaries.yml
- bcda/service/testdata/cclf_files.yml
- codecov.yml
- docker-compose.debug.yml
- docker-compose.test.yml
- docker-compose.yml
adding the missing document start "---" (document-start) for yaml files (sonarqube finding)
unit tests pass and docker able to compose
> BCDA-5886: resolve YAML start line code smell in files

- bcda/auth/middleware_test.go
- bcda/auth/ssas_test.go
- bcda/cclf/metrics/metrics.go
- bcda/logging/middleware_test.go
- bcda/web/middleware/middleware_test.go
- bcda/web/middleware/ratelimit_test.go
- Add nested comments to describe empty functions
- Empty functions are properly described
> BCDA 5885 - Resolve Empty Functions

- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- bcda/constants/constants.go
- bcda/errors/errors.go
- bcda/responseutils/writer.go
- bcda/testUtils/utils.go
Cleaning up response interpretation from SSAS introspect call, as well as more detailed error handling (and more specific Status Code(s) returned for the error scenario)
Created custom error types to return from VerifyToken call and be handled via switch statement to return back BCDA API response. Cleaned up VerifyToken and VerifyPublicToken functions (naming convention, broke up logic into smaller functions). Added Retry After Header logic when code is 503 (default value 1 second).  
Added test coverage for each of the different scenarios of error handling along with expected status code response.
Added test coverage for underlying functions
> BCDA-5903: Response interpretation cleanup from SSAS

- bcda/auth/api.go
- bcda/auth/api_test.go
- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/mock_provider.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_middleware_test.go
- bcda/auth/ssas_test.go
- bcda/constants/test_constants.go
- bcda/models/SwaggerStructs.go
- test/smoke_test/bcda_client.go
- Add new key "expires_in" to /auth/token endpoint response to follow https://tools.ietf.org/html/rfc6749#section-5.1 recommendations
- Example response below in postman
- Tests pass
- Verify response in postman
- (`make credentials` command allows you to create credentials for local env)
> BCDA-6022: Provide expires_in value in Response Body for /auth/token

- Dockerfiles/Dockerfile.tests
Update docker image version
Successful execution of make test target
> Version update for docker image

- bcda/auth/client/ssas_test.go
- Swap lines to set SSAS_TIMEOUT_MS back to 500 after request timeout test
> Update test order for TestGetToken

- bcda/auth/api.go
- bcda/auth/client/ssas_test.go
- bcda/constants/test_constants.go
- bcda/testUtils/utils.go
- Remove last return in GetAuthToken
- Convert test values to constants
> BCDA-6291: Remove last return in GetAuthToken and convert to constants

- Makefile
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
Add PACA test scenario coverage (for test ACO ID with fully adj access only) inside Postman end to end collection
1. Add PACA test scenario coverage (for test ACO ID with fully adj access only) inside Postman end to end collection
2. Additionally updated Makefile for local postman test execution to not have alrEnabled = true (match Jenkins job execution for smoke tests executed in env setting).
Tested the changes within Postman as well as makefile command line executing the collection
> BCDA-6518: add PACA test scenario coverage

- db/migrations/manual/20221231-runout.sql
> BCDA-6530: 2022 manual sql file for EOY

- db/migrations/manual/20221231-runout.sql
This fixes the small typo observed during the enabling of end of year (EOY) mode on Dec 31, 2022. A close parenthesis character was missed. This was updated during manual execution in PROD but we updating the sql file in repo for historical record keeping purposes.
This is also noted in Confluence in the comments sections on 2022 End of Year Checklist: https://confluence.cms.gov/display/BCDA/End+of+Year+Checklist%3A+2022
> BCDA-6530: Fix small typo in SQL statement

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
Update test execution order so /Group/runout gets a chance to be executed before the Job Completion Status section in end to end postman collection. 
Executed locally and also pointing to PROD env with ACO Dev creds
> BCDA-6654: update test execution order for end to end postman collection

- bcda/auth/api.go
- bcda/auth/api_test.go
- bcda/testUtils/utils.go
Small correction for /auth/token - ensure http.StatusText written to response body
Added within unit tests:
*Assertions on expected response body
*Assertions on what messages are logged to application log
Spun up application locally & made api call to auth/token to confirm response body output
> BCDA-6678: http status text for /auth/token err handling

- db/migrations/manual/20230106-synthetic-runout-file-creation.sql
- db/migrations/manual/20230106-test-data-for-synthetic-runout-file-creation.sql
- db/migrations/manual/20230106-verification-checks-for-synthetic-runout-file-creation copy.sql
See the script to generate test data that was used to test out the synthetic runout file script in lower environment (DEV) for different scenarios
> BCDA-6660: synthetic runout file script & test data

- Dockerfiles/Dockerfile.package
- Switched from Debian to Alpine docker base image
- Included missing dependencies to execute packaging process
- Update to git config to fix VCS stamping warning
- Set environment variable CGO_ENABLED=0 to disable dynamic linking of native os lib for go build
- Handles issue seen here https://github.com/CMSgov/bcda-app/pull/61
Successful build and execution of package container on lower environments. Also verify that Snyk findings reported has been reduced.
> BCDA-6627 updating base docker image used for packaging

- bcda/models/fhir/alr/alr_test.go
Current BCDA app build jobs are failing due to a recent update to golangci-lint
correct linting issue for resources in alr_test.go by adding resources variables in the function
> BCDA-6748 BCDA app build failure

- db/migrations/manual/20230214-runout-undo-aco-reach-entities.sql
Undo runout for ACO REACH (Dec 22 CCLF served as file for runout to using newly ingested Feb 2023 runout file)
> BCDA-6535: undo runout - aco reach

- db/migrations/manual/20230307-runout-undo-entities.sql
We received the runout files for SSP ACOs on Feb 15, 2023. This was confirmed via the database, so we can convert the December files back to normal filetypes (type=0).
The ACO REACH files have already been undone.
> BCDA-6536: Undo December runouts

- .github/pull_request_template.md
https://jira.cms.gov/browse/BCDA-6858
1. Remove the PR Hygiene Checklist (some of it is optional, and some of it can be moved into the acceptance validation section. Also, it takes up a lot of space overall.)
2. Rename "Proposed Changes" --> "Changes"
3. Rename "Change Details" --> "Context for Reviewers"
4. Move security checklist to the bottom since it takes up the most space.
5. Merge "Feedback requested" into "Context for Reviewers"
6. Simplify instructions to improve usability of the template for PR authors.
7. Add emojis and section dividers (🤷)
1. Merge "new data is stored or transmitted" with "does the change deal with PHI/PII".
2. Simplify formatting for readability when filling out the template.
3. Update wording to be imperative ("This change introduces X", "New data is stored …
> BCDA-6858: Refine pull request template

- bcda/api/requests.go
https://jira.cms.gov/browse/BCDA-6892
Added a logging statement to the function `validateRequests` to gain better visibility into intermittent failures during smoke tests.
Our Integration/Smoke tests have been failing intermittently and we have been able to replicate the behavior manually. To gain additional visibility beyond the build console and in case the issue occurs in production, we should add a log statement to that function in the event of an error.
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
> BCDA-6892: Smoke test pipeline intermittent failures - add logging 

- .github/pull_request_template.md
https://jira.cms.gov/browse/PLT-77
Shortened security implications section in PR template to match standard.
Addendum to #843.
Final wording checked with @bhodges-navapbc.
> PLT-77 Shorten security implications section

- README.md
https://jira.cms.gov/browse/BCDA-xxx
Restructured the readme to follow logical flow of first time setup, clarified some sections like prereqs for running tests, and added a section on how to run and interact with the api locally.
general improvements to readme.
--
> readme: reorganization and additional instructions

- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-7135
Added tests to improve code coverage; https://github.com/CMSgov/bcda-app/pull/869 had 70% coverage on new code. 
Additional testing may require refactoring, since much of the uncovered lines are i/o or os operations.
tests pass.
> BCDA-7135: Worker.go test cov

- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/constants/constants.go
- bcda/responseutils/v2/writer.go
- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-7123
Updated unit tests for BCDA-7123: bcda/api/requests.go
Scrubbed unnecessary information that was sent to a client (go overflow error)
Most of these are straightforward, adding on use cases to the existing tests and covering functions more fully.
Unit test coverage on this file is now 85.1%; this can be increased in the future by implementing the MockRepository.
Awaiting the CodeCov report, as it should be closer to 90% coverage for the entire file now. 
> BCDA: Improve coverage for "bcda/api/requests.go"

- README.md
https://jira.cms.gov/browse/BCDA-7488
Changed README to add instructions for running tests locally in vscode.
Simple update to the README on running single tests, as the preferred pattern (go test) is not set up to work out of the box with this repo. 
Verified README is formatted correctly for the new section. 
> BCDA-7488: Add single test / single file instructions

- bcda/api/requests.go
- bcda/api/requests_test.go
https://jira.cms.gov/browse/BCDA-7811
Added tests + logic to differentiate between a row not being found, and any other type of issue. 
BCDA has received reports of jobs not being found that are clearly in our database, this will create different levels of logging for those that are truly not found vs. something else, so we can better address that. 
Added unit tests, all tests pass. 
> BCDA-7811: Update logging to differentiate reasons for job not found

- bcda/web/middleware/ratelimit_test.go
https://jira.cms.gov/browse/BCDA-7889
Fixed missing string in unit test
Verified unit test locally triggered failure condition.
> BCDA-7889: Update requestURL in test

- .github/workflows/ci-workflow.yml
- go.mod
https://jira.cms.gov/browse/BCDA-7863
- Add automated testing for unused modules
Adds automated testing for unused modules so we can remove the weekly task. After this is approved, I'll copy these changes over to the SSAS repo.
- Failed run: https://github.com/CMSgov/bcda-app/actions/runs/8425003643/job/23070143967
- Successful run after committing tidy changes: https://github.com/CMSgov/bcda-app/actions/runs/8425019284/job/23070187330
Including @StewGoin as FYI.
> BCDA-7863: Add CI for tidying modules

- .github/workflows/ci-workflow.yml
https://jira.cms.gov/browse/BCDA-7864
- Add Sonarqube quality gate to pull request check
We run Sonarqube quality gates as part of builds and deployments, but not as part of PRs, so sometimes we'll merge a change and break the build/deploy.
We also have some security checks that we manage manually at the moment using a scheduled task. We can automate this within the pipeline.
See checks.
> BCDA-7864: Add Sonarqube quality gate check to PRs

- .github/workflows/ci-workflow.yml
- Makefile
- README.md
- bcda/main.go
- ops/Jenkinsfile.build_trigger
- swagger.json
https://jira.cms.gov/browse/PLT-326
Reference to master branch was changed to main
Github repository master branch renamed to main. changes made to reference main in jenkins instead of master
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
> modify reference of  master branch to main

- Dockerfiles/Dockerfile.bcda_prod
- Dockerfiles/Dockerfile.bcdaworker_prod
- Dockerfiles/Dockerfile.documentation
- Dockerfiles/Dockerfile.ssas
- Dockerfiles/Dockerfile.tests
https://jira.cms.gov/browse/BCDA-8187
Update alpine distros from 3.15 to 3.18
The finding references bcda-ssas-app, but we'll need to do this for bcda-app, as well, or else we'll run into new findings when moving to ECS
CI passes
> BCDA-8187: Update Alpine distro 

- .github/workflows/ci-workflow.yml
N/A
- Add env var to fix self-hosted Github Actions steps.
See https://github.com/actions/checkout/issues/1809 for technical context.
Sonarqube quality check passes on this PR.
> Fix Github Actions on self-hosted

- Makefile
- README.md
- scripts/unit_test.sh
- shared_files/README.md
- test/smoke_test/smoke_test.sh
N/A
- Did a find-replace for `docker-compose ` to `docker compose `
See https://github.com/orgs/community/discussions/116610 for relevant discussion.
See PR checks and [this deployment](https://management.bcda.cms.gov/job/BCDA%20-%20Build%20and%20Package/4316/) which uses the kev/ci branch across our app and ops repos.
> Update docker-compose commands

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
An extension of https://jira.cms.gov/browse/BCDA-8230
Converted patient request body to url encoded params as requested by BFD.
Local linting and testing.
> Convert patient request body to url encoded params

- .github/workflows/migrate-db.yml
https://jira.cms.gov/browse/BCDA-8760
Added migrate DB workflow
Part of moving off of jenkins.
Local testing, linting
> BCDA-8760: First pass simplified migrate DB workflow

- bcdaworker/queueing/river.go
https://jira.cms.gov/browse/BCDA-8810
Fixed err override in cleanupjob
Small issue I noticed when reviewing some code.  Low impactish risk/impact, but also a very quick fix.
Local linting and testing
> BCDA-8810: Fix err override in cleanupjob

- .github/workflows/smoke-tests.yml
https://jira.cms.gov/browse/BCDA-8637
Modified the portion that checks which ACO was selected. Evaluating input parameters in `run` was failing, so moved it to an `if` section under the step.
Could not test calling the workflow with parameters until the original PR was merged; doing troubleshooting to make sure input parameters working as expected.
Ran test against dev in GHA and all steps completed successfully.
> BCDA-8637: Input updates

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8909
Update environment on deploy job to allow for auto scheduled deployments
Previously failing
Tested on push with feature branch
> BCDA-8909: add default env to deploy

- .github/workflows/ci-checks.yml
https://jira.cms.gov/browse/BCDA-8944
Adjust sonarqube workflow quality check.
Sonarqube workflow quality check is currently very flaky. It often reads thousands of new lines of code being introduced even though there will sometimes be nothing new.
Workflow testing.
> BCDA-8944: Adjust sonarqube quality check

- .github/workflows/ci-checks.yml
https://jira.cms.gov/browse/BCDA-8944
Use default branch of checkout to make sure we are comparing the right code.
Sonarqube failures :(
Workflow run testing.
> BCDA-8944: Use default branch for sonarqube quality check

- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- bcda/lambda/admin_create_aco_creds/README.md
- test/smoke_test/smoke_test.sh
https://jira.cms.gov/browse/BCDA-9008
- Updated the ssas client configuration to trim its url value
- Included the expiry date in the simple string message returned on credential creation 
- Updated the create-creds lambda function readme with a link to a confluence how-to guide
Additional unit tests! (and removed superfluous old ones)
> BCDA-9008: Make small updates to Credential Creation workflow

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8967
Slight adjustments to deploy workflow, messed up the env var name, and need to remove the one exit clause.
Fix deploy workflow verification checks.  This work is a slight adjustment to previous work.
Workflow testing
> BCDA-8967: Fix workflow deploy scripts

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8967
Need env set for each job otherwise they wont be able to access env vars.
Need env set for each job otherwise they wont be able to access env vars.
> BCDA-8967: Add env to new verification jobs

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8967
Trim quotes from response, was tripping up on r257 != "r257".
Deploy verification failing on equality check.
> BCDA-8967: Trim quotes from jq response

- .github/workflows/build-ami.yml
- .github/workflows/build-and-package-all.yml
- .github/workflows/ci-checks.yml
- .github/workflows/deploy-all.yml
- .github/workflows/migrate-db-gf.yml
https://jira.cms.gov/browse/BCDA-9143
Disable auto run of various legacy workflows.  Add migrate-db-gf workflow.
GF migration updates to workflows.
Workflow testing
> BCDA-9143: Dont auto-run legacy workflows, add migrate db gf

- .github/workflows/admin-create-aco-creds-deploy-GF.yml
- .github/workflows/admin-create-aco-creds-integration-test-GF.yml
- bcda/lambda/admin_create_aco_creds/aws.go
- bcda/lambda/admin_create_aco_creds/aws_test.go
- bcda/lambda/admin_create_aco_creds/main.go
- bcda/lambda/admin_create_aco_creds/main_test.go
https://jira.cms.gov/browse/BCDA-9143
> BCDA-9143: Migrate ACO Lambdas

- .github/workflows/deploy-all-gf.yml
- .github/workflows/tag-and-release.yml
https://jira.cms.gov/browse/BCDA-9010
Update runner on tag and release workflow.  Update migrate-db ref to GF version in deploy workflow.
Post GF cleanup and fixes for deployment related workflow issues.
Workflow run.
> BCDA-9010: Update tag and release workflow

- .github/workflows/admin-create-aco-deploy-GF.yml
- .github/workflows/admin-create-aco-integration-test-GF.yml
- .github/workflows/admin-create-group-integration-test-GF.yml
- .github/workflows/build-ami-gf.yml
- .github/workflows/build-and-package-all-gf.yml
- .github/workflows/cclf-import-integration-test-GF.yml
- .github/workflows/deploy-all-gf.yml
- .github/workflows/fhirscan-GF.yml
- .github/workflows/migrate-db-gf.yml
- .github/workflows/opt-out-import-integration-test-GF.yml
- .github/workflows/package-rpms-gf.yml
- .github/workflows/refresh_test_attribution.yml
https://jira.cms.gov/browse/BCDA-9145
Made some minor fixes to greenfield workflows, including fixing incorrect references and updating dependency versions.
> BCDA-9145: Update workflows for greenfield

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8988
Update tf install step with proper directory
We recently removed the `terraform` dir which is breaking this workflow.
Workflow testing
> BCDA-8988: Update tf install with directory input

- bcda/api/requests.go
- bcda/api/requests_test.go
https://jira.cms.gov/browse/BCDA-9385
- updated response when attribution file is not found from HTTP 500 -> 404.
- updated tests
HTTP 500s should be reserved for serious, unexpected errors. This was a result of requesting expired runout data, which caused alerting to trigger; this is an expected outcome around this time of the PY and should be handled more gracefully. 
An additional ticket has been created to give a more informative/helpful response to our entities when runout data has been requested past its expiry date: https://jira.cms.gov/browse/BCDA-9386
Tests updated and passing.
> BCDA-9385: Update bulk request response when attribution file not found
