- ops/github_release.py
- ops/release.sh
Adds `ops/release.sh` and `ops/github_release.py`. Used together, these scripts create a release tag and github release complete with release notes based on git commit history.
The `release.sh` script inspects git tags to determine the previous release tag/number, increments by 1 and creates a new tag and release based on the updated number. 
This script also calls `github_release.py`. The github release script requires python 3+ to work properly.
Usage:
```sh
GITHUB_ACCESS_TOKEN=<gh_access_token> ./ops/release.sh
```
> BCDA-30: Scripts to generate release tags and create github release 

- LICENSE.md
- Adds a license doc indicating the project is public domain in the United States and worldwide under CC0 1.0
- Points would-be contributors to the BCDA Google Group for feedback and questions
> BCDA-96: Add a license doc

- Dockerfiles/Dockerfile.unit_test
- Makefile
- README.md
- docker-compose.test.yml
- docker-compose.yml
- unit_test.sh
The intent of BCDA-234 is to:
1) Containerize the unit tests to ensure they are run in an environment that we know is stable through automation.  This removes the need to install extraneous dependencies on host machine.
2) Remove local dependency on `psql` (which is bloated) and replace with `usql` (which is lean)
3) Beef up README with more details on how to set up environment, how to run tests, and how to interact with the app
> BCDA-234: Containerize Unit Tests

- .gitignore
- Makefile
- README.md
- bcda/database/connection_test.go
- bcda/logging/middleware_test.go
- bcdaworker/main_test.go
- docker-compose.test.yml
- unit_test.sh
Test coverage metrics and reports are generated as part of `make test`, and the resulting reports are output in the `test_results` folder on the host (individual timestamped folders are created in `test_results` in order to separate the metrics by test run).  
The files that are generated are:
1) `testresults.out` -- Results of test case execution
2) `testcoverage.out` -- Generic test coverage file generated by `-coverprofile`
3) `testcov_byfunc.out` -- Test coverage metrics by function
4) `testcoverage.html` -- Highlighted test coverage analysis for each go file
See attached to see examples of the outputs.
[testcovfiles.zip](https://github.com/CMSgov/bcda-app/files/2371227/testcovfiles.zip)
Two additional things to note:
1) Empty test files were created in some of our packages which did …
> BCDA-235: Generate test coverage metrics/reports 

- .gitignore
- Dockerfiles/Dockerfile.bcda
- Dockerfiles/Dockerfile.bcdaworker
- Makefile
- docker-compose.debug.yml
- docker-compose.yml
- Adds the [delve](https://github.com/derekparker/delve) debugger to docker images for api and worker services
- Sets a liberal `security_opt` in docker-compose.yml to allow the debugger to function properly
- Adds some make commands to start delve: `make debug-api` and `make debug-worker`
- Is this a good idea/would anyone find this useful?
~~- [ ] Create and use `docker-compose-api-debug.yml` (and similar for worker) for a sane way of setting environment variables, volumes and ports~~ EDIT: turns out we don't need this
- Running `make debug-api` or `make debug-worker` drops you into a `(dlv)` prompt where you can set breakpoints, examine function arguments, print the results of an expression, etc (see: [delve cli docs](https://github.com/derekparker/delve/tree/master/Documentation/cli)) …
> Proposal to add delve debugger commands

- bcda/api.go
- bcda/api_test.go
- bcda/auth/models.go
- bcda/database/connection.go
- bcda/main.go
- bcda/models/models.go
- bcdaworker/main.go
A couple bug fixes and code style/naming changes.
- Fixes error checking when creating a new job record
- Removes redundant bcda from name of models package
- Removes duplicate `Job` definition from `auth/models.go`
- Auto runs gorm migrations when env var `DEBUG=true` (e.g., local dev env)
- Changes `bcda sqlMigrate` to `bcda sql-migrate` to match the rest of the cli commands
> GORM bug fixes, style changes

- bcda/database/connection.go
- bcda/database/connection_test.go
Fixes [BCDA-256](https://jira.cms.gov/browse/BCDA-256)
Problem:
Created unit test for our database connectivity. Previously there were none.
Added a test suite to connection_test.go (bcda/database/connection_test.go)
None.
I wasn't able to fully get the unit test coverage to 100% due to the inability to properly test log statements. Not sure how to do that other than writing unit test for our logger itself which seems kinda excessive.
Take a look at this screenshot:
Any feedback. How can we get our test coverage to 100% with this problem? It's not just this test but for all of our test.
> BCDA-256 Feature: Unit test for db connections

- bcda/logging/middleware_test.go
We have no unit tests for `logging/middleware.go`.
* Add tests to cover creating a structured logger and writing a structured log entry.
* The work done so far achieves 97% coverage. Reaching 100% is the goal of https://jira.cms.gov/browse/BCDA-344
None.
Coverage went from 0 to 97.1%
Any!
> BCDA-257: Develop unit tests for bcda/logging/middleware.go

- Dockerfiles/Dockerfile.unit_test
- bcda/api_test.go
- bcda/main_test.go
- unit_test.sh
Test status was not being propagated correctly.  See here: https://travis-ci.org/CMSgov/bcda-app/builds/436835705
Additionally, cleaning up some test cases and making sure our tests have the appropriate env vars.
- Use `bash` instead of `sh` for better error handling control.
- Ensure appropriate environment variables are pre-set in unit test image.
- Fix some flaky test cases.
- Update Dockerfile to executed unit test script with `bash`
- Update unit test script to `set -o pipeline` to ensure the worst status code from a pipeline is propagated
- Updated Dockerfile with additional pre-set environment variables (as the system would have)
- Fixed some test cases
None
Tests are passing in Travis.
> Testing Env Vars, Status Propagation, and Test Case Cleanup

- bcda/api.go
- bcda/responseutils/writer.go
- bcda/router.go
Fixes [BCDA-231](https://jira.cms.gov/browse/BCDA-231)
Problem:
We needed a capability statement (FHIR compliant) as to what our API can do. And now we have one!!
router.go - added metadata endpoint
api.go - added http handler function to call for the creation of the capability statement
writer.go - added function for creating a capability statement and for writing the response.
Security Implications
None
Acceptance Validation
Try to hit the "/api/v1/metadata" and see if a capability statement is generated.
Any
> BCDA-231 Feature: Implemented metadata endpoint for capability statement

- Dockerfiles/Dockerfile.release
- Makefile
- ops/release.sh
Allow tag/release process to be executed from Jenkins job in an automated fashion, which can optionally deploy the release to specified environment by calling the relevant downstream jobs.
App-related changes are in this PR.  Another PR is open for the ops-related changes.
In app, we will be creating a `Dockerfile` so that the release process can run in a containerized fashion.
- Created a `Dockerfile` so that the release process can be run from a container
- Updated `Makefile` so that release process can be run by executing a `make` command
- Update `release.sh` to accomodate the security validation required when creating tags from within a container.
I have create a GPG key and added it to my Github account, which allows user "BCDA CI" to create tags.  When environment variables are …
> BCDA-341: Automate tag/release process

- Dockerfiles/Dockerfile.bcdaworker
- bcda/api.go
- bcda/auth/middleware.go
- bcda/client/bluebutton.go
- bcda/responseutils/issuedetail.go
- bcdaworker/main.go
- bcdaworker/main_test.go
To comply with FHIR bulk spec, when errors occur in generating export files, they must be compiled into an NDJSON file of OperationOutcome resources.
* Write OperationOutcome resources to file if errors occur while ExplanationOfBenefit data is being retrieved and written to a file
* Add configurable (env var `BB_TIMEOUT_MS`) timeout to Blue Button requests
* Add `appendErrorToFile()` function in bcdaworker/main.go
* Called when an error is returned from `BlueButtonClient.GetExplanationOfBenefitData()`
* Include error NDJSON file in `jobStatus()` response
* Tests in bcdaworker/main_test.go
Beneficiary ID and ACO ID included in the OperationOutcome text.
Does the approach of checking for the existence of an error file make sense, or should we store something (e.g., error count per job) in …
> BCDA-293: Error Persistence - Connection Error

- bcda/responseutils/issuedetail.go
- bcdaworker/main.go
- bcdaworker/main_test.go
We are currently retrieving ExplanationOfBenefit data for only one beneficiary per ACO.
* Retrieve ExplanationOfBenefit data from the Blue Button backend sandbox for all beneficiary IDs in an ACO
* Now that we have a small ACO to test with, we can see that a job for an ACO with 50 beneficiaries takes approximately 9s
* Adjustments to tests that include two beneficiary IDs
None; all synthetic data
Can be confirmed by looking at resulting NDJSON file, which will contain as many EOB Bundles as there are beneficiaries in the ACO.
Any
> BCDA-355: Fetch data for more than one beneficiary from the BB backend sandbox

- bcda/logging/middleware_test.go
- bcdaworker/main_test.go
Test coverage for logging/middleware.go is not quite 100%.
* Update test suite to reach 100% coverage
* Added test for logging/middleware.go `Panic()` function
* Also added line in bcdaworker/main_test.go to clean up a test NDJSON file
None
Any
> BCDA-344: Full test coverage for logging/middleware.go

- Dockerfiles/Dockerfile.bcda
- Dockerfiles/Dockerfile.bcdaworker
- README.md
- bcdaworker/main.go
- bcdaworker/main_test.go
- ~~Moves `waitForSig` to the end of `setupQueue` function to prevent deferred actions in the latter from closing the db connection to worker queue.~~
- Make `setupQueue` return the queue db connection, defer closing it in bcdaworker's `main()`. This should ensure it works properly with unit tests _and_ actually running the app.
- Remove env var definitions from Dockerfiles so that error and debug messages are easily visible via docker-compose output.
- Add a list of available env/config vars to the readme.
- Fixes file paths for keys and certs in Dockerfiles.
> A few misc. bug fixes

- README.md
- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/main.go
- bcda/main_test.go
- Adds a 'create-alpha-token' command to the CLI
- Implements that command in auth/backend.go
The plan is that a human will use the CLI to create tokens for our alpha participants in the alpha sandbox. For more details and discussion, see the Jira Ticket.
- Creates an ACO entry with a fixed name format like 'Alpha ACO #'.
- Creates a User entry with a fixed name format like 'Alpha User#' and email like alpha.user.#@nosuchdomain.com
- Copies the 50 beneficiaries associated with 'ACO dev' and associates those copies with the new ACO
- Creates an authentication token
- Displays the ACO name and user name in plain text, and the token in base64 encoded string form
We chose to generate synthetic ACO and User names and email addresses to avoid any issues with PII.
Also, since we generate the …
> BCDA-415 Create Access Tokens for Alpha Partners

- Dockerfiles/Dockerfile.package
- ops/build_and_package.sh
App-packaging scripts related to the ops changes defined in this PR: https://github.com/CMSgov/bcda-ops/pull/26
The build/package Docker image is based on Alpine, which uses lib-ld-musl instead of libgc.  To avoid compatability issues, I'm switching to Debian Linux Docker image so that the RPMs run successfully on RHEL.
- Updated packaging Dockerfile to use Debian instead of Alpine
- Update build/package script to adjust path (/usr/local/bin instead of root dir)
None.
- Build/Package Jenkins job succeeded when run with feature branches that contain the app and ops changes: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/52/parameters/
- BCDA is running in dev: http://bcda-api-dev-837966021.us-east-1.elb.amazonaws.com/
- Screenshot below to show that it is running from …
> BCDA-353: Update RPM build process to avoid using lib-ld-musl

- Makefile
- ops/build_and_package.sh
Swagger doc endpoint is working on localhost, but not working in AWS.  The changes brought forth in this PR ensure that the swagger doc endpoint works in AWS environments.
Package the swagger directory as part of the RPM.
- Slight modifications to Dockerfile to ensure that the documentation has been generated as part of packaging process.
- Update to build/package script to ensure that the swagger doc directory is included in the RPM packaging.
None
Built and tested in AWS dev environment.  See screenshot (not the AWS dev env URL):
Please provide feedback.
> BCDA-392: Swagger endpoint in AWS

- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/main.go
- bcda/main_test.go
With our [process for distributing alpha tokens](https://confluence.cms.gov/display/BCDA/Distributing+Alpha+Partner+Tokens) now formalized, we need an additional option and different output from the CLI command.
The command now supports an optional --ttl argument to set a custom TTL on an alpha token.
The output now contains the expiration date and alpha token id, instead of the fake ACO name and fake user name.
The [initial implementation PR](https://github.com/CMSgov/bcda-app/pull/58) may be useful as a reference.
Command is only accessible via the CLI.
Unit tests and hand testing output.
> BCDA-507: Tweak CLI's create-alpha-token command

- .travis.yml
- bcda/api.go
- bcda/middleware.go
- bcda/router.go
- test/bcda_client.go
Since we are routing requests to two different instances of `http.Server`, we can not support persistent connections and must set a `Connection: close` header in our responses.
The consequence of not setting this header is that, when a client makes back-to-back requests for endpoints handled by separate `http.Server` instances, the app will be unable to route the request properly and send back a false `404` error.
The [HTTP/1.1 whitepaper](https://tools.ietf.org/html/rfc2616#section-14.10) indicates setting the `Connection` header is acceptable (and, in fact, required) when the application does not support persistent connections.
- Adds a `ConnectionClose` middleware and uses it with the api and data server routers
- Note: since we are deploying the app behind AWS ELB, the "client" in our …
> Set connection: close response header

- bcda/api.go
- bcda/main.go
- bcdaworker/main.go
- docker-compose.yml
This change adds a check for `?encrypt=true` appended to `/api/v1/ExplanationOfBenefit/$export` and executes the file encryption routine when it is present.
This is necessary since we do not plan to share and discuss file encryption functionality with our pilot users in research sessions. We'll hold off on sharing it until after the first round of research is done and we have documentation explaining how they're meant to interact with the encrypted files (see: https://jira.cms.gov/browse/BCDA-512).
At the same time, we need a way to allow security auditors to test/validate that our file encryption is present and works properly. This should help accomplish that goal.
As stated above, this adds a check for `?encrypt=true` in requests for bulk data. When this query parameter is present, the …
> Add a (temporary) way for clients to request file encryption

- Makefile
Jenkins was using cached images for `unit_test` and `smoke_test`
Force a rebuild of the images within the `Makefile` targets
Added `--build` to force the rebuild of the `unit_test` and `smoke_test` images
None.
Tested locally and ensured the image is rebuilt.
Please review.
> Rebuild test images each time they are executed

- .gitignore
- bcda/main.go
- bcda/main_test.go
- docker-compose.yml
When a job is expiring due to age, its files are moved to an inaccessible location. See [BCDA-441](https://jira.cms.gov/browse/BCDA-442) for more about this. The work of this ticket is to cleanup that inaccessible location by removing files for jobs that have not been touched for a certain period of time.
Add a CLI command to cleanup the archive location. To run locally in docker:
docker exec -it bcda-app_api_1 bash -c 'tmp/bcda cleanup-archive --threshold 30'
--threshold is required, because I don't think it's appropriate for this argument to have a default.
1. Renamed the original status associated with moving files to the archive location from 'Expired' to 'Archived'
2. When a job has been in 'Archived' state for `threshold` hours, remove the files from the archive and set the job …
> BCDA 442: Cleanup files for expired jobs

- API.md
- bcda/servicemux/servicemux_test.go
Some information in our narrative documentation is out of date.
* Update paths that have changed
* Add clarifying details and incorporate tester feedback
* Uses latest version of CapabilityStatement
* Replaces {host} placeholder in example URLs with sandbox host
* Adds note about `$export`
* Adds job ID to example URLs, with integer to show how the URLs look
* Not using placeholders for the examples as the intent is to show what someone might actually see. We have the URL formats with placeholders in the Swagger docs
* Explains what the huge blob of JSON is at the end
Sandbox URL is now public, but it contains no PII or PHI and we have access restrictions in place.
Also made these changes in the Google doc version.
Any
> BCDA-543: Update our Getting Started documentation

- bcda/client/bluebutton.go
- bcda/logging/middleware.go
- bcda/main.go
- bcdaworker/main.go
Splunk is unable to see files with permissions of 600.  
Update necessary log files to have permissions of 640.
- Update log file permissions to be 640 instead of 600
- Identify in code commentary why we are circumventing a `gosec` rule 
Group now has `read` privileges.
> Ensure Splunk can see log files

- Dockerfiles/Dockerfile.integration_test
`git` is being leveraged in our test container and sporadically fails if not configured.  This PR configures `git` appropriately.
> Configure git for usage in the container

- bcda/auth/backend.go
- bcda/database/connection.go
- bcda/responseutils/writer.go
- bcda/servicemux/servicemux.go
- bcda/testUtils/utils.go
- bcdaworker/main.go
- unit_test.sh
GoSec currently isn't running test G104 which looks for unhandled errors.  This PR adds in error handling for all places it was missing and enables that test 
Handled potential error with opening of Key FIles
Handled potential error with setting of environment variables
Handled potential error with closing of files
Handled potential errors with marshalling of JSON data
Handled potential errors with opening DB connection
Handled potential errors with closing of serviceMUX
handled potential errors with flushing of writer
handled potential errors with removing directory
Most errors are handled in ways similar to other errors within the function.  As these errors were previously unhandled it shouldn't cause any problems to now handle them explicitly
no PII should be affected
Run make test and …
> knollfear/bcda-554 Handling errors in order to allow for the running of Gosec test G104

- bcda/client/bluebutton.go
- bcda/logging/middleware.go
- bcda/main.go
Makes `bcda` use "append" mode when opening log files to prevent the issue described here: https://serverfault.com/questions/642286/logrotate-continuous-write-issue
- Update locations where `bcda` opens `BB_ERROR_LOG`, `BCDA_REQUEST_LOG` and `BCDA_ERROR_LOG` to use `os.O_APPEND` mode.
> BCDA-624: Use os.O_APPEND mode for error/request logs

- Dockerfiles/Dockerfile.integration_test
- bcda/api.go
- bcda/api_test.go
- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/main.go
- bcda/responseutils/issuedetail.go
- bcda/router.go
- bcdaworker/main.go
- bcdaworker/main_test.go
- docker-compose.yml
- test/integration_test/patient-notoken.json
- test/integration_test/patient.toml
- test/smoke_test/bcda_client.go
We need a way for ACOs to retrieve patient data as found in CCLF-8.
* Add endpoint for starting a patient data export job
* Adds `/Patient/$export` route
* Adds resource type parameter to `bulkRequest()`
* Uses environment variable `ENABLE_PATIENT_EXPORT` to determine whether endpoint is accessible. Enabled only if that value is true.
Retrieves PII from Blue Button and returns it in the generated data file.
Includes smoke and integration tests. Does *not* include Swagger docs because we can't seem to control that with an env var. There is a separate ticket for narrative documentation, which we can roll this into.
Any
> BCDA-395: Add /Patient endpoint for bulk export of patient data

- bcdaworker/main.go
Encrypting data files for delivery broke after a recent commit.
In PR-85 we added a bunch of missing error handling. That error handling caught a previously silent error that was occurring only when we were delivering encrypted files.
The steps were:
1. Get BB data and put it in a staging directory
2. encrypt that data in memory
3. write the encrypted data to a file in the data directory
4. remove the staging directory  <<< PR-85 catches the error here
The steps are now:
1. Get BB data and put it in a staging directory
2. encrypt that data in memory
3. write the encrypted data to a file in the data directory
4. remove the bb data files from the staging directory <<< this PR adds this missing step
5. remove the staging directory 
None
Hand testing only by sending an encrypt=true parameter …
> fix the bug

- bcda/responseutils/writer.go
Fixes [BCDA-609](https://jira.cms.gov/browse/BCDA-609)
Problem:
Capability statement was out of date with our latest code changes, specifically the Patient endpoint that was recently added.
This will adjust our capability statement to correctly reflect all of our endpoints (in their respective environments)
bcda/responseutils/writer.go -- updated capability statement with the "Patient" endpoint
No PII/PHI but this statement should only show the Patient endpoint when that environment is configured to expose that resource.
Be sure capability statement shows the correct metadata in the correct environments.
Any
> BCDA-609 Feature: Updated capability statement with Patient endpoint

- bcdaworker/main.go
We want be able to monitor workers in new relic.
- import our monitoring package into bcdaworker/main.go
- record processJob as a transaction and its nested functions as segments in new relic
None really.  High security mode is turned on in new relic
you can see what is being reported in new relic here: https://rpm.newrelic.com/accounts/2057345/applications/128793549/transactions?type=other#id=5b224f746865725472616e73616374696f6e2f476f2f70726f636573734a6f62222c22225d
> bcda-602 add new relic monitoring to worker job processing

- bcda/router.go
When making repeated API requests, there are sometimes unexpected 404s. Repeatable when making a failed data request followed by an API request.
Adjust data router middleware to ensure that connections are closed.
* Moves `ConnectionClose` from `r.With()` to `r.Use()` in `NewDataRouter()`
None
To confirm, make a request to download data with no token (to cause an error response), followed by a request to any API endpoint. This should cause a 404 for the API request without this change, but a success response for this branch.
Any
> BCDA-659: Ensure that ConnectionClose middleware is always called

- test/Beneficiary Claims Data API Tests, Sequential.postman_collection.json
- test/Beneficiary Claims Data API Tests.postman_collection.json
We'd like to have a collection of Postman integration tests for BCDA.
Create a collection of tests that can be run locally or integrated into our CI/CD pipeline.
Two collections of tests have been created, one set meant as one-offs to be run individually (or together with the "Get token" test, depending on environment). Adjustments will need to be made to work with our build and deploy process (e.g., need to save a token to the Postman environment in application environments that don't have the token endpoint).
None
The sequential set of tests may be imported into Postman and run together, with an environment configured with the variables below. Other variables are added into the environment as the tests run.
* `host`: `localhost:3000`
* `scheme`: `http`
* `env`: `local`
* `jobId`: any …
> BCDA-598: Develop a collection of Postman integration tests

- bcda/api.go
- bcda/api_test.go
- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/auth/models.go
- bcda/auth/models_test.go
- bcda/encryption/encryption_test.go
- bcda/main.go
- bcda/main_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcda/secutils/secutils.go
- bcda/secutils/secutils_test.go
- docker-compose.test.yml
Our ACO and User models are in the auth package, but the API needs them to exist independent of the auth implementation. Since we are preparing to more rigorously separate auth from the api, we need to move these models to the bcda/models package. The token model remains in auth.
- ACO model and tests moved to bcda/models
- User model and tests moved to bcda/models
- Extracted shared code for reading PKI keys into secutils package
- Added some missing tests
None
All tests pass.
Did I miss anything?
I had to change the docker-compose.test.yml file to correct an env path var that had (apparently) not been used by tests before.
> BCDA-628: Move models from auth to bcda

- Dockerfiles/Dockerfile.integration_test
- bcda/api.go
- bcda/api_test.go
- bcda/database/connection.go
- bcda/database/connection_test.go
- bcda/router.go
- test/Beneficiary Claims Data API Tests, Sequential.postman_collection.json
- test/Beneficiary Claims Data API Tests.postman_collection.json
- test/integration_test/health.json
- test/integration_test/health.toml
We need a way to check the health of the API.
Add a health check endpoint that returns a response based on database connectivity. Note that this ticket originally included Blue Button connectivity, but that will be checked by the worker application instead.
* Creates unauthenticated endpoint, `/_health`
* Checks database with GORM`Ping()`
* Returns `200 OK` if database is accessible and `502 Bad Gateway` if not
* Includes tests in api_test.go
None
Any
> BCDA-645: Create /_health endpoint

- bcda/client/bluebutton.go
…that we are alerted to issues with BB not working.
New Relic can monitor the health of Blue Button, notifying us if there are any issues.  We need to actually monitor each request to the blue button backend and send the results to New Relic. 
Added monitor to getData method of BlueButton client.
Just implemented the monitor.  By doing it in this location all paths to BlueButton will automatically report to New Relic with no additional coding
THis is reporting metrics so no PII is affected, it should confirm that no PII is sent to New Relic
I added the New Relic Key to my docker-compose.yml file
I ran a bulk export job locally
I confirmed that data was in fact sent to New Relic
I have specced out the rules at New Relic, but I have not implemented them yet.
> knollfear/bcda-606 New Relic monitoring on BB data collection

- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
- bcda/auth/provider.go
We'd like to have an interface to be implemented by auth plugins.
Create an auth provider interface and alpha plugin.
* Adds auth/provider.go, an interface of provider operations
* Adds auth/alpha.go, an implementation of the interface (returns only "Not yet implemented" errors)
* auth/alpha_test.go is a suite of simple tests for the plugin
None
All tests pass.
I'm a bit out of the loop on auth; happy to make any adjustments you need for this to work with your implementation.
Any opinions on using pointer vs value receivers here? My inclination is pointer, but value could be preferable if we're not modifying the plugin in any of the methods. https://golang.org/doc/faq#methods_on_values_or_pointers
> BCDA-629: Add an auth provider interface and an alpha plugin

- bcda/api.go
- bcda/monitoring/monitoring.go
- bcda/router.go
Fixes [BCDA-648](https://jira.cms.gov/browse/BCDA-648)
Problem:
We needed a way to capture more properties for our nrql queries and wrapping our html handlers provides those additional bits of information.
bcda/monitoring/monitoring.go - added a wrapper function for the new relic handler
bcda/router.go - added handler wrapping for our routes
bcda/api.go - removed old way of capturing a transaction
None
Running new relic with the changes gives us additional query parameters for our transactions
Any
> BCDA-648 Feature: Wrapped http handlers for monitoring

- API.md
- bcda/api.go
We don't yet have narrative or Swagger documentation for our new Patient data export endpoint.
Note: This will not be merged until we are ready to release the new endpoint.
Create narrative and Swagger docs for /Patient/$export
* Adds Patient export example to API.md
* Adds Swagger-generating comment to `bulkPatientRequest()` in api.go
None
Narrative documentation can be seen in Markdown file.
Swagger:
Any
> BCDA-610: Narrative Documentation: /Patient endpoint for bulk export of patient data

- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
adds a working `decodeAccessToken()` func and an associated unit test for the alpha plugin
- make `decodeAccessToken()` work
- write a simple unit test to test it
test passes!
> bcda-630: add decodeAccessToken and unit test for alpha plugin

- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
`RevokeClientCredentials()` is not yet implemented in our alpha plugin.
Implement `RevokeClientCredentials()` in alpha.go.
* Looks up ACO by client ID, users by ACO, and tokens by users. Calls `RevokeToken()` on any tokens found.
* Test added in alpha_test.go that will need to be fully implemented with `RevokeToken()`.
No changes.
Input is the same. Currently returns an error due to `RevokeToken()` not being implemented yet.
Do we want to return errors in the case of the ACO, users, or tokens not being found? Or should it return nil because if they're not found, there's nothing to revoke?
> BCDA-637: Implement RevokeClientCredentials() on alpha plugin

- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
GenerateClientCredentials() needs to be implemented on the alpha plugin. The intent of this method is to generate new or to replace existing credentials with new ones.
Verifies that ACO has a ClientID (i.e., RegisterClient() has been called for the ACO previously).
Will use RevokeClientCredentials() to revoke any existing credentials (needs merge of BCDA-637)
Uses CreateAccessToken() to generate credentials.
Returns a token string.
Adds tests. 
No changes.
All tests pass.
Any objections to revoking existing credentials as part of this call?
> BCDA-636: implement GenerateClientCredentials on Alpha plugin

- bcda/api.go
Uh oh. We never close the database connection in the health check function.
Add a new `isDatabaseOK()` function instead of unnecessary call to `GetGormDbConnection()` and make sure it closes the connection
None
Health check still works. We will want to check the connection count in AWS after this is deployed.
Any. Angry reminders to always close connections are welcome.
> Close db connection in `healthCheck()`

- .travis.yml
- Makefile
- bcda/api_test.go
Local/development testing requires executing multiple test targets from `Makefile`.
Wrap all of the test-related targets into one `test` target.
- Renamed `test` target to `unit-test`.
- Created a new `test` target which wraps all of the test-related targets in `Makefile`
- Updated Travis configuration to use the new `test` target.
- Ops changes here: 
None.
Tested locally and in Travis.
Please review.
> BCDA-683: Wrap all test targets into one `make test` target

- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/auth/middleware_test.go
- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
- bcda/auth/provider.go
- bcda/main.go
- test/smoke_test/bcda_client.go
The `RevokeAccessToken()` function in our alpha plugin is not yet implemented.
Implement `RevokeAccessToken()` and use it in the CLI.
* Implements `RevokeAccessToken()` and tests
* Uses `RevokeAccessToken()` for the `revoke-token` CLI command
* Removes old token revocation code and tests
* Adds `revokeAccessTokenByID()` to the plugin, called by `RevokeAccessToken()` and `RevokeClientCredentials()`
No changes.
Tokens can still be successfully revoked from the CLI.
Are we okay with the approach of the having a private function to revoke a token that accepts the ID, or do we want to change the parameter(s) for the public function? Any other thoughts?
> BCDA-635: Implement RevokeAccessToken()

- bcda/main_test.go
After recent issues with the command line interface holding up a release, we'd like to feel more confident in our CLI testing.
Add more unit tests for CLI functions.
* Add more test cases
* Check buffer contents and error messages when available
None
All tests pass
Any
> BCDA-671: Expand CLI unit tests

- bcda/api.go
- bcda/api_test.go
- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
- bcda/main.go
- db/fixtures.sql
Replaces uses of auth/backend.CreateToken function with the auth/Provider.RequestAccessToken function.
CLI and /api/v1/token endpoint now use auth provider method.
middleware uses of backend will be addressed by BCDA-764.
CLI and token end point.
No new security concerns
All tests continue to pass.
* added a fixture user that is assigned to 'ACO Dev'
* reworked some tests because RequestAccessToken() requires that the User be associated with the ACO (CreateToken did not).
> Replace [most] uses of backend.CreateToken

- API.md
- ENCRYPTION.md
- bcda/api.go
- bcda/main.go
- test/smoke_test/bcda_client.go
- test/smoke_test/smoke_test.sh
Encryption is currently not enabled by default.  An explicit parameter must be passed in order to enable encryption.
Update the application so that all bulk requests encrypt the ndjson file by default, and permit a parameter to be passed to the endpoints to bypass the encryption (for now).
- Updated the example request in ENCRYPTION.MD 
- No changes in API.MD - instead using the writeup from here: https://github.com/CMSgov/bcda-app/pull/143
- Updated the API to enable encryption by default, and only disable it if a parameter is passed to the endpoint (`?encrypt=false`)
- Update the smoke test appropriately
- Ops-related changes performed in this PR: https://github.com/CMSgov/bcda-ops/pull/113
Client user has the ability to disable encryption, resulting in unencrypted files living on our …
> BCDA-720: Encryption enabled by default

- API.md
We currently provide users with our narrative documentation, but it does not include information about encryption or the Swagger documentation.
Add links to encryption doc and Swagger UI to our narrative documentation.
None
Preview: https://github.com/CMSgov/bcda-app/blob/bffbcf58dcf54a1e39f1141bf07bed504ca02896/API.md
These are just proposed changes. I'm open to any suggestions! If we do want to add this information, we should hold off on merging until after @msnook's encryption ticket https://jira.cms.gov/browse/BCDA-720. Do we need to make a note about the Swagger documentation being accessible only to our alpha partners right now?
> BCDA-732: Update User Guide documentation

- bcda/api.go
- bcda/api_test.go
- bcda/client/bluebutton.go
- bcda/responseutils/writer.go
- bcda/router.go
- bcdaworker/main.go
- docker-compose.yml
- test/postman_test/BCDA_Tests.postman_collection.json
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
- test/smoke_test/smoke_test.sh
Fixes [BCDA-396](https://jira.cms.gov/browse/BCDA-396)
Problem:
Added new endpoint.
bcda/api.go - added "coverage" option for a bulk request.
bcda/api_test.go - added test case for new endpoint
bcda/client/bluebutton.go - added new function for APIClient interface
bcda/router.go - added new coverage endpoint
bcdaworker/main.go - added new case for coverage function
docker-compose.yml - added ENABLE_COVERAGE_EXPORT config var
test/postman_test/BCDA_Tests.postman_collection.json- added postman tests
test/postman_test/BCDA_Tests_Sequential.postman_collection.json - added postman tests
test/smoke_test/smoke_test.sh - added smoke tests
Security Implications
None, but env flags should be used to control enabling/disabling of this endpoint
Yes
Feedback …
> BCDA-396 Feature: Add Coverage endpoint for bulk export of patient data

- bcda/api.go
- bcda/api_test.go
- bcda/auth/backend.go
- bcda/auth/backend_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/models.go
- bcda/auth/models_test.go
- bcda/auth/plugin/alpha.go
- bcda/database/utils.go
- bcda/encryption/encryption.go
- bcda/encryption/encryption_test.go
- bcda/health/health.go
- bcda/main.go
- bcda/main_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
we don't always close db connections when we open them right now.  this closes them all and logs an error if we are unable to close the connection.
add `utils.go` to the database package with a function that closes a db connection and logs an error if unable to do so.
> bcda-762 make sure all database connections are closed

- bcda/api.go
- bcda/api_test.go
- bcda/auth/backend.go
- bcda/auth/models.go
- bcda/auth/models_test.go
- bcda/auth/plugin/alpha.go
- bcda/auth/plugin/alpha_test.go
- bcda/auth/provider.go
- bcda/encryption/encryption_test.go
- bcda/main.go
- bcda/main_test.go
- bcda/models/models.go
- bcdaworker/main.go
- bcdaworker/main_test.go
Tokens would be easier for us to work with if we had more fields than those provided by `jwt.Token`. NB: Work related to this is being done in https://jira.cms.gov/browse/BCDA-764, so the move to using `auth.Token` is ongoing, particularly as it relates to middlewares.
Expand our own `auth.Token` model and replace current usage of `jwt.Token` where appropriate.
* Adds `IssuedAt` and `ExpiresOn` fields to `auth.Token` so we can recreate JWT strings
* Changes `RequestAccessToken()` to return `auth.Token`
* Creates new `GenerateTokenString()` in auth/models.go that accepts additional fields
* `RequestAccessToken()` now uses new `GenerateTokenString()`
* Removes `auth.Token` model `BeforeSave()` because we will no longer store the value and add new `AfterFind()` for recreating the string …
> BCDA-763 Improve handling of auth tokens with auth.Token type

- bcda/api.go
- bcda/main.go
- bcda/models/SwaggerStructs.go
We'd like to make it clearer to users what each response to the job status endpoint means.
Add more detail to job status response descriptions in the Swagger documentation.
* Adds some new Swagger response models for specific HTTP response codes that share the OperationOutcome model for body content
* Uses new models in job status endpoint and others where applicable
None
Changes can be reviewed in the Swagger UI at /api/v1/swagger
Any
> BCDA-738: Review and add detail to job status responses in Swagger

- bcda/auth/plugins/alpha.go
- bcda/auth/plugins/alpha_test.go
- bcda/auth/plugins/okta.go
- bcda/auth/plugins/okta_test.go
- bcda/auth/provider.go
- bcda/main.go
Adds a skeleton implementation of the Okta auth plugin. All methods currently return a 'not yet implemented' error.
Okta plugin with all provider methods implemented.
None. All methods do is return a 'not yet implemented' error.
Tests included that prove all methods return an error.
> Skeleton implementation of Okta plugin

- bcda/main.go
- bcda/middleware.go
- bcda/middleware_test.go
- bcda/router.go
- bcda/router_test.go
- docker-compose.yml
Adds an http server and router to enable redirection of all `http` requests to `https`.
- Adds a simple `http.Server` definition, uses `NewHTTPRouter()` to define the server's handler.
- The `http.Server` is configured to listen on port `3001`.
- `NewHTTPRouter()` returns an http handler configured with:
- New Relic APM transaction monitoring
- Standard BCDA structured logging for http requests
- BCDA's `ConnectionClose` middleware
- Responds to `/*` requests
- Sets `Strict-Transport-Security` header to instruct browsers to use `https` only going forward
- Uses `301` status to indicate permanent redirect
The only way for this to be useful in any of our deployment environments is for the envs ELB to be configured to forward port `80` requests to the `http.Server` on port `3001`.
Accepting …
> BCDA-542: Add a simple http router that redirects http requests to https

- bcda-site-static/_includes/footer.html
- bcda-site-static/index.md
Changes links that lead to external sites to use `target="_blank"`, ensuring they open in a new browser page/tab.
> BCDA-878: Make sure links to external sites open in a new page/tab

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/moktaclient.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
- bcda/main.go
- bcda/main_test.go
- bcda/models/models_test.go
This is the first method of the auth Provider interface to be given a working implementation in the Okta Plugin. All other tickets are dependent on it, as one must have credentials in order to acquire a token.
1. Changed method signature to use specific typed parameters. Originally we thought the arguments might vary with plugin, so we used json for parameters. However, the parameters won't vary.
2. Use value semantics for the receiver in plugin implementations. The types are based on the empty struct so there is nothing to modify, hence no need for pointer receivers.
3. CreateAlphaToken() handles either plugin.
4. Simple support for changing the plugin at runtime added to Provider. This is done for testing support. See BCDA-882 for more details.
5. Because the okta client (BCDA-808) is …
> BCDA-812: implement registerClient() method for Okta auth plugin

- bcda/auth/alpha_test.go
- bcda/auth/client/oktaclient.go
- bcda/auth/mokta.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
Validate an access token issued by Okta.
1) Implements the ValidateJWT() method for Okta. Although mostly self-contained, it did need a method added to the OktaBackend interface to validate the issuer (the Okta server id).
2) Add testing support for manufacturing test tokens in Mokta
3) Move tests into auth package itself from auth_test. The auth_test package only exists to eliminate an otherwise cyclic import among the alpha test files.
4) Tests added for important Okta-specific token claims. 
* Unlike the alpha token, the Okta token does not carry around with it the ACO ID. Instead, the code looks the ID up every time it's needed. We want to address this with some kind of caching before going live.
* A related question is should we now start using the auth.Token wrapper around the JWT …
> BCDA-815: ValidateJWT() Implementation

- bcda/api.go
- bcda/api_test.go
- bcda/auth/provider.go
- bcda/models/SwaggerStructs.go
- bcda/router.go
Since we are going to be adding an Ansible script to change the provider env var dynamically (for testing purposes), we will need a way to determine the auth provider at any point in real-time.  This new endpoint will give us that capability.
Add a `/_auth` endpoint which gives us the `auth_provider` in real time.
- Added a new convenience function in `provider.go` to return the provider name.
- Added the `/_auth` route and accompanying handler function.
- Added unit tests for the new route and handler function,
- Updated the SwaggerStructs template to include details for the new route.
None.
Please review.
> BCDA-882: Add /_auth endpoint to acquire the auth_provider mode.

- ops/Jenkinsfile.build_trigger
Build and deploy daily, each morning, to serve as an early warning system for changes in dependencies (AWS, tools, etc).
> Make sure we're building daily 

- bcda/auth/client/oktaclient.go
- bcda/auth/mokta.go
- bcda/auth/okta.go
- bcda/auth/provider.go
- bcda/main.go
We need the client name in the output.
For Okta, replaced first line of output with client name
No change in security posture.
All unit and integration tests run.
To hand test:
`make docker-bootstrap`
edit docker-compose.yml and set these env variables:
BCDA_AUTH_PROVIDER=okta
OKTA_OAUTH_SERVER_ID=_server id_
OKTA_CLIENT_TOKEN=_token_
`docker-compose up`
`docker exec -it bcda-app_api_1 sh -c 'tmp/bcda create-alpha-token --size Dev'`
Any.
> Modify Okta create-alpha-token output to include client name

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/client/oktaclient.go
- bcda/auth/client/oktaclient_test.go
- bcda/auth/mokta.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
implements a func to revoke a client application's access in okta and satisfy the provider interface
- write a couple of funcs in `oktaclient.go` to deactivate and delete a client application in okta
- change `RevokeClientCredentials()` to accept a `clientID string` instead of a `params []byte`
- implement `RevokeClientCredentials()` in `okta.go`
- test everything
the mokta method used for testing is very naive.  any feedback for improving the test?  oktaclient_test looks good and passes at least
> BCDA-818 implement RevokeClientCredentials() for okta

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
- bcda/main.go
- bcda/main_test.go
For ops purposes, we need to be able to get an Okta token.  This PR extends the existing CLI command `create-token` to work when using an OktaAuthPlugin auth provider.
- Change the `--user-id` argument to `--id` to account for both user-id's and client-id's
- Add a `--secret` argument, which is ignored when using the AlphaAuthPlugin auth provider.
- Too many `switch` statements in the code and tests!
This is strictly a dev-only tool.  There should be no change to the security posture with this PR.
Get a token by running:
`docker exec -it bcda-app_api_1 sh -c 'BCDA_AUTH_PROVIDER=okta OKTA_OAUTH_SERVER_ID=<okta_server_id> OKTA_CLIENT_TOKEN=token_not_used_but_required tmp/bcda create-token --id <a_valid_client_id> --secret <this_client_secret>'`
and (using an alpha token included in the test …
> BCDA-956 Feature: add Okta token generation to cli "create-token" command

- bcda/cli.go
- bcda/cli_test.go
- bcda/main.go
- bcda/main_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- db/api.sql
- db/fixtures.sql
For attribution using CCLF8 and CCLF9, beneficiaries are associated with ACOs by their CMS IDs. We'll need to store this ACO ID value (AXXXX). (Beneficiary IDs handled by separate ticket.)
Add CMS ID to ACO model while retaining our internal ACO UUID.
* Adds string/char(5) `CMSID` to `ACO` model/table
* Updates `create-aco` CLI command to accept optional CMS ID
* Moves `createACO()` from main.go to cli.go (recently added file for CLI functions)
None
ACO can be created from CLI with or without CMS ID (if valid format).
Any
> BCDA-957: Add CMS-format ID to ACOs

- bcda/api.go
- bcda/api_test.go
Adjustment to query for beneficiaries in `bulkRequest()` to improve performance.
Replace GORM `Preload()` for beneficiaries with separate queries per ACO-Beneficiary relationship. Includes some corrections to error logging.
Tests continue to pass. @msnook confirmed that the timeout we previously saw is no longer happening in dev with this branch.
Any
> BCDA-963: (Part 3) Remove Preload() from ACO/Beneficiary retrieval

- Makefile
- bcda/api.go
- bcda/api_test.go
- bcda/auth/alpha.go
- bcda/auth/middleware_test.go
- bcda/auth/okta.go
- bcda/auth/provider.go
- bcda/main_test.go
- bcda/models/SwaggerStructs.go
- bcda/router.go
- bcda/router_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
We need an API endpoint for ACO's to get temporary access tokens.  They will present a client id and secret, and our auth provider(s) will verify and give a token if authorized.
- A new function `GetAccessToken()` is used instead of `RequestAccessToken()` because `RequestAccessToken()` in alpha does not require a secret, and does require a TTL
- A number of testing updates solved issues that cropped up during development (especially trying to test with Okta as auth provider)
- Add endpoint to Swagger
Since this will be open to all visitors in the public sandbox, and that token is the gateway to all data, any path that leads to releasing a token needs to be carefully reviewed.
- Are we using the right return values and parameter names?
- Is there more test coverage that we could/should …
> BCDA-973 Feature: Add /auth/token endpoint

- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
It's possible for Bearer tokens to end up in our Splunk logs if provided in the query string (malformed request).
Replace `[string]` with `<redacted>` when `Bearer%20[string]` is found in a request URL before writing it to the log.
This will prevent a security incident if a user places a Bearer token in the query string.
Includes tests and can be seen in log entries.
Any
> BCDA-534: Redact Bearer Token from URL Logs

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- docker-compose.test.yml
- docker-compose.yml
The Blue Button dev environment certificate can change. Currently we are checking the certificate (or not) based on URL, but using an environment variable instead would allow us to configure it by environment, regardless of BB URL.
Add `BB_CHECK_CERT` environment variable that, when `false`, indicates that the Blue Button backend certificate should not be checked.
* Creates `BB_CHECK_CERT` that is used in bluebutton.go. If not explicitly set to false, the certificate will be checked.
* Adds tests for missing or invalid keypair and CA cert files
By default, the Blue Button backend certificate will be checked. `BB_CHECK_CERT` needs to be set to `false` to skip adding the certificate to the Blue Button client TLS config.
Tests pass.
Any.
> BCDA-336: Check Blue Button backend certificate

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/middleware.go
- bcda/auth/models.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
We need a way to delete a client in the alpha auth plugin so that Eric and Jason can sleep at night.
- implement  the DeleteClient() func for alpha
Since registering a client in alpha is really just generating a clientID and an alphaSecret on the ACO model, to delete the client, we will simply set these values on the db record for the ACO back to an empty string
Anything you can think of!
> BCDA-1032 implement delete client func for alpha

- bcda/router_test.go
router_test.go does not contain tests for all API routes.
Add tests for all API routes.
* New tests for:
* /api/v1/ExplanationOfBenefit/$export
* /api/v1/Patient/$export, with multiple values for env var `ENABLE_PATIENT_EXPORT`
* /api/v1/Coverage/$export, with multiple values for env var `ENABLE_COVERAGE_EXPORT`
* /api/v1/jobs/{jobId}
* /api/v1/metdata
* /api/v1/token, with multiple values for env var `DEBUG`
* /_health
* /_version
* New helper functions in router_test.go
* Change `RouterTestSuite` struct to include API and data router `http.Handler`s rather than `httptest` servers
None; tests only
Tests pass
Any
> BCDA-846: Add testing of api routes in router_test.go

- bcda/models/SwaggerStructs.go
Fixes [BCDA-777](https://jira.cms.gov/browse/BCDA-777)
Problem:
When running a coverage request via swagger a missing header was found.
bcda/models/SwaggerStructs.go - added bulkCoverageRequest to the BulkRequestHeaders struct.
This should fix the structural issue with the prefer header
None
Ran locally and didn't see the structural issue for the prefer header.
Any and all
> BCDA-777 part 2 Feature: added Coverage as a swagger parameter to the BulkRequestHeader

- bcda/health/health.go
Although we have a health check log for bcdaworker, it does not indicate the cause of errors reported.
Log database and Blue Button connection errors from worker health checks.
* Adds `log.Error()` calls in `health.IsDatabaseOK()` and `health.IsBlueButtonOK` for error scenarios. These write to the standard worker log.
No PII involved. This logs errors encountered when checking connectivity to the BCDA database and to the Blue Button metadata endpoint.
Error examples:
* Invalid database driver:
* Database shut down:
* Blue Button key file does not exist:
* Invalid Blue Button URL:
Any.
> BCDA-1182: Log worker health check errors

- encryption_utils/C#/decrypt.cs
- encryption_utils/C#/decrypt.csproj
- encryption_utils/C#/runtimeconfig.template.json
- encryption_utils/Go/decrypt.go
- encryption_utils/Python/decrypt.py
- encryption_utils/Python/requirements.txt
Fixes [BCDA-1181](https://jira.cms.gov/browse/BCDA-1181)
Problem:
Files were correctly moved in our repo but this lead to broken links on our static site.
Added back encryption_utils file path with the correct files in order to fix the links.
Security Implications
None
Acceptance Validation
Not yet, changes have to be merged into master in order to fully test.
validate here: https://sandbox.bcda.cms.gov and https://test.bcda.cms.gov
Any and all
> BCDA-1181 Feature: Added back correct folder and file paths to fix static site links

- README.md
The BCDA application README uses `bash` in an example, but `bash` is no longer in the Docker container. This pull request changes the example command to use `sh`.
> Update README to reflect change in shell

- test/postman_test/opensbx.postman_environment.json
Our Postman test is still named `sbx` instead of `opensbx`.  That results in this failure: 
```
error: ENOENT: no such file or directory, open 'test/postman_test/opensbx.postman_environment.json'
```
Rename the test to reflect the correct environment.
- Renamed the Postman test for our Open Sandbox to be `opensbx` instead of `sbx`.
None.
Executed locally against `r20` in `opensbx`, and all tests passed.
Please review.
> Rename Postman test to reflect opensbx instead of sbx

- bcda/cli.go
- bcda/cli_test.go
- bcda/models/models.go
The CLI has a proof of concept for reading CCLF8 files, but does not yet store the file metadata or contents.
Create data model for CCLF8 file metadata and beneficiaries, and save to database as files are read.
* Creates two new data models and tables:
* `CCLF8File` model - `cclf8_files` table
* `CCLF8Beneficiary` - `cclf8_beneficiaries` table
* Saves file metadata, one row per file, into `cclf8_files`
* Saves beneficiary HICN and MBI, per row in file, into `cclf8_beneficiaries`
Note that the new tables currently stand alone, and our next steps for attribution will determine how they are used. We will likely need foreign key associations:
* `cclf8_files.aco_cms_id`-`acos.cms_id`
* `cclf8_beneficiaries.beneficiary_id`-`beneficiaries.id`
This change allows the storage of beneficiary …
> BCDA-964/BCDA-958: Save CCLF8 data into database

- bcda/api.go
Per the swagger documentation (see Ticket) there is a required attribute on license called "Name". We currently do not have this value set and it is causing an error at the bottom of the swagger page.
Added the name "Public Domain" to the license comment
Added the name "Public Domain" to the license comment
None.  All this does is change the name displayed on the link to the license.
No error at the bottom of the page
Good:
Bad:
Any
> BCDA-1216 adding a name to the Swagger license

- Makefile
When building/packaging the RPMs, we were previously generating swagger and static site data in docker-compose detached mode (which runs the containers and generates the data in the background).  To reduce the risk of race condition, we should ensure that the data is generated in the proper sequence, since it is a prerequisite for the RPM packaging.
Ensure that the data generation for swagger and static site is completed before packaging the RPMs.
No longer running the data generation containers for swagger and static site in detached mode.
This modification is strictly related to build/packaging scripts and does not affect security.
Build and deployed feature branch in Jenkins: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/599/
Please review.
> Fix race condition in RPM packaging

- bcda/auth/models.go
- bcda/auth/models_test.go
- bcda/models/models_test.go
BCDA needs a function in the auth package for generating a key pair for encryption, and assigning that key pair to an ACO.
Add function to generate a key pair and assign it to a system, which can be linked to an ACO by client ID.
* Adds function `GenerateSystemKeyPair` that creates a 2048 bit RSA key pair, saves the public key in the database, and returns the private key.
The newly added `GenerateSystemKeyPair` function uses Go's `rsa` library to create the key pair, as used elsewhere in the BCDA application. The new function is not currently called anywhere except for its tests.
Added two tests:
* `TestGenerateSystemKeyPair` - confirms that key pair is created successfully
* `TestGenerateSystemKeyPair_AlreadyExists` - confirms that function will return an error if encryption keys already …
> BCDA-1242: Update Auth Function for Key Pairs

- bcda/auth/models.go
- bcda/auth/models_test.go
We need a way to properly remove access of encryption keys for a system
- add func to auth/models.go that soft deletes an encryption key belonging to a system
- add test to validate functionality
No security implications with this PR yet.  It's just adding some functionality to inactivate a system's encryption keys.  These encryption keys are not being distributed or used yet.
I added a test to make sure that an encryption key is deleted without errors and that the deleted_at field is set (soft deletion)
Why am I failing the assertion I wrote to make sure that the deleted_at column is not null?
> BCDA-1245 add func to revoke encryption keys

- bcda/api.go
- bcda/cli_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
- test/performance_test/performance.go
- test/performance_test/performance_test.sh
- test/smoke_test/bcda_client.go
- test/smoke_test/smoke_test.sh
BCDA provided an option to use a query parameter to disable encryption (`encrypt=false`) of exported data for testing purposes. The option was intended to be temporary, and is now ready to be removed as we move toward production.
Remove `encrypt` parameter and tests of unencrypted requests.
* `bulkRequest()` no longer looks for `encrypt` query parameter
* `encrypt` parameter removed from `GetEnqueJobs()`
* `processJob()` always encrypts data; encryption cannot be disabled
* Tests using `encrypt=false` have been removed
These changes improve our security as they completely remove the option to retrieve unencrypted NDJSON files. All data returned from export jobs will be encrypted.
Tests are passing. Smoke and performance tests are no longer split into encrypted and unencrypted versions. …
> BCDA-1280: Remove option to turn off encryption

- bcda/cli.go
- bcda/cli_test.go
Fixes [BCDA-1194](https://jira.cms.gov/browse/BCDA-1194)
Problem:
We need to have logging for every part of our cli ingesting process. We had some in place but needed to make sure we covered everything. This ticket should take care of that.
bcda/cli.go - added logging and print statements for our entire cclf ingestion workflow
bcda/cli_test.go - modified test case to successfully run
No, there is no PII/PHI dealing with this change. However this ticket does log tasks that handle PII/PHI around our cclf ingestion process. There is **NO** logging of PHI/PII itself.
Yes
Screenshot:
Any and all
> BCDA-1194 Feature: Added ETL logging

- bcda/router.go
- bcda/router_test.go
Fixes [BCDA-1283](https://jira.cms.gov/browse/BCDA-1283)
Problem:
We had no way of limiting the user guide in production. Our desired state is to **not** have this shown at all when we launch to prod, this change does that.
bcda/router.go - disables access to the user guide in production
bcda/router_test.go - testing code that verifies a 404 response
No, this change does not deal with PII/PHI at all.
I was able to fully test this and confirmed the 404 error.
Any and all
> BCDA-1283 Feature: Update to router file to exclude user guide

- bcda/main.go
For the ETL process, we need a pending deletion directory to exist to move files to after they are ingested.
When `BCDA_ETL_MODE` is `true`, directory defined by `PENDING_DELETION_DIR` will be created when the BCDA application starts.
The directory created by this ticket will be used as a place for CCLF files to be moved into to indicate that they are ready to be deleted by the cleanup process.
We will need to confirm that the directory is created in the NFS.
Any. Is `744` the right permissions setting for this directory?
> BCDA-1255: Create Function to make the required directories for NFS

- bcda/auth/models.go
- bcda/auth/models_test.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
- bcda/cclf/testutils/cclfUtils.go
- bcda/models/models.go
- db/api.sql
- db/migrations/20190524-attribution.sql
Changes to the attribution process mean that the `beneficiaries` and `acos_beneficiaries` tables are no longer needed. Related models were removed with BCDA-1234.
Drop `beneficiaries` and `acos_beneficiaries` tables, and update functions that rely on them.
* SQL script to drop `beneficiaries` and `acos_beneficiaries`
* `beneficiaries` and `acos_beneficiaries` removed from api.sql
* CLI `create-alpha-token` changed to require a CMS ID for the ACO in the format `T****` (`T` + four digits)
* `AssignAlphaBeneficiaries()` removed due to reliance on dropped tables. To associate beneficiaries with an alpha ACO, synthetic CCLF files may be ingested.
No security impact. This script removes two tables that are not used and modifies the attribution process for an alpha ACO.
Tests updated. Will …
> BCDA-1259: Remove beneficiaries and acobeneficiaries table and associated structures/code

- bcda/models/models.go
- bcda/models/models_test.go
This is for BCDA's beta release: to set up ACO's, our process will be:
1. Create the ACO (using the CLI)
2. Upload the public key (step 1 of Jenkins job)
3. Create credentials (step 2 of Jenkins job)
Right now, this process fails because step 3 depends on the ACO having a `client_id`, and step 1 does not create it.  In the future there may be other ways to accomplish this, but for now, the simplest and least risky way to get to release is to have step 1 also set the `client_id`
When calling `models.CreateACO()`, set the `acos.client_id` equal to the string value of `acos.uuid`.
See ticket.
Unit testing confirms that the `client_id` is set.
Can anything be improved?
> BCDA-1365 Bug: When creating an ACO, set the client_id

- bcda/main.go
Swagger has been broken, not accepting tokens because the bearer token description was put in the `name:` field.  This PR fixes the issue.
* Use "Authorization" as the name of the bearer token authentication method
This change only affects Swagger documentation, essentially reverting it to a prior state, and thus does not negatively impact security.
Auth dialogue documentation:
Proof of functioning token:
* Does it run for you?
* Are there any other necessary changes?
> BCDA-1375: Bug fix: Swagger bearer auth now works

- bcda/auth/backend.go
- bcda/auth/backend_test.go
Our first benchmark of the `prod` environment suggests that we need many more iterations in our hashing to reach our target of at least 1 second spent creating each hash.  This PR increases the number of iterations from 90,000 to 130,000.
More hash iterations adds protection to the credentials we hash, making attackers work harder to use the credentials should they have access to our database.
All credentials in all environments will be invalidated by this change.  After merging this code, credentials used in Jenkins for smoke tests will be updated for `dev` and `test` environments.
Are there any glaring errors in this PR?
> BCDA-1393 Security Update: Increase Hash Entropy

- bcda/cclf/cclf.go
BCDA prints `cclfFileMetadata` inconsistently. Reviewing logged information would be easier with a consistent, simple format.
Always display `cclfFileMetadata` in the same format for printed and logged messages.
* Adds `String()` method on `cclfFileMetadata` that returns the file path if it exists, or name
* Uses string-formatted `cclfFileMetadata` in printed and logged messages in cclf.go
This will print paths or names of CCLF files, but no contents.
Messages can be seen when running CCLF file ingestion, which runs on synthetic files as part of our test suite. Example messages below.
Any. Do we need any other information for debugging?
> BCDA-1309: Print cclfFileMetadata in a more readable format

- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
When `cleanupCCLF()` fails, error details are not provided.
Add error value to printed and logged messages, and return an `error` from the function if one or more files was not cleaned up.
This adds more information to logs and messages printed by the CLI to include the causes of errors when files are being moved. No PII or PHI is included.
Messages can be seen in tests (where cleanup was already failing) and `TestCleanupCCLF()` asserts that the returned `error` is nil.
Any
> BCDA-1347: The CCLF Cleanup functionality does not report errors properly

- bcda/client/bluebutton.go
Log entries for Blue Button responses are missing values. 
Add missing values and remove fields where the value is unknown.
* Uses headers from the request to populate `bb_query_id`, `bb_query_ts`, `bb_uri`
* Removes `content_length` because Go will always set it to -1
* Adds `jobID` parameter to `getData` calls from `GetPatientData` and `GetCoverageData`
* Shortens messages to simply `request` or `response` (previously 'Blue Button request' and 'Blue Button response`) as these entries are part of the Blue Button request log and have other indicators that they are to/from BB
* Separates request and response logging into two functions, called before the request is made and after the response is received
No new information has been added; all values being logged in responses are already …
> BCDA-1417: Fix BB client logging statements for responses

- docker-compose.yml
Fixes [BCDA-1433](https://jira.cms.gov/browse/BCDA-1433)
Problem:
We would occasionally experience connection timeouts when making request, especially to our heavier data endpoints like EOB. This will hopefully keep our files from error-ing out so much.
docker-compose.yml - changed timeout from 500 --> 10,000 milliseconds
No, this change **does not** deal with any PII/PHI.
Yes, all of our tests pass. And since this error was less consistent, time will tell us if this bug is truly resolved. 
Any and all
> BCDA-1433 Feature: Increased the BB connection timeout to 10 seconds.

- decryption_utils/Go/decrypt.go
- encryption_utils/Go/decrypt.go
- test/smoke_test/bcda_client.go
There are intermittent decryption errors when the smoke tests are run, but not enough information to determine the cause.
Check for more scenarios that could cause decryption to fail and print errors to stdout.
* Go decryptor errors print to stdout
* bcda_client.go checks for `encryptedKey` and `privateKeyFile`, and prints an error and exits if either does not exist
No security impact. These changes apply to smoke tests, which run with synthetic data.
A few examples of errors from the Go decryptor and test client.
Any. Can you think of other places where the smoke tests or decryptors need to print more information?
> BCDA-1441: Additional error handling in smoke tests

- bcda/auth/models.go
- bcda/auth/models_test.go
- db/migrations/20190614-drop-tokens-table.sql
Since we are no longer saving tokens to the db, we don't need a tokens table.  There is also some related code that will not be used
- add migration to drop tokens table
- remove now unnecessary fields from the token model and some funcs using the token model as a receiver
No security impact here.  We already aren't saving the tokens to the db so removing the tokens table does not affect security of the app
Tests are passing and everything seems to work just as it did before removal
Is there anything more that can be deleted?
> BCDA-1204 Remove tokens table

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
When a request to Blue Button fails, an entry is added to the errors NDJSON file, with no way for users to re-request only the failed subset of data from BCDA. Some of these errors may be remedied by retrying failed BB requests.
Add retry mechanism in Blue Button client.
* Adds retry logic in `BlueButtonClient.getData()`, using new environment variables:
* `BB_REQUEST_MAX_TRIES` - Maximum attempts per Blue Button request
* `BB_REQUEST_RETRY_INTERVAL_MS` - Length of pause, if any, that should happen between requests
* Splits bluebutton_test.go into two tests suites, to separate those that make requests from those that don't
There is no change to how data is handled, but BCDA will now make more attempts to retrieve it from Blue Button if necessary.
Added tests with Blue Button client …
> BCDA-711: Introduce retry mechanism in data retrieval from BB

- bcda/auth/alpha_test.go
We were accidentally creating tokens that expired much later in the future than desired.  this has been fixed and deployed but we still need to add a test to make sure that the expiration dates are as intended on newly generated access tokens
- add unit tests to make sure that a newly generated access token has an expiration date less than 60 minutes from generation and never later than 60 minutes after generation
No negative security implications here.  The way we are generating tokens remains the same.  We get a little bit more secure by testing to make sure expiration dates are correct after this PR
The newly added unit tests pass
Is this testing sufficient?  How could it be more robust?
> BCDA-1414 add test for a new token's expiration claim

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/api_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/models.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- ssas/systems.go
Since specs have changed over time, some function names do not accurately represent what the functions do.  This PR renames those functions
- rename functions that have outdated names
no security implications on this one.  just some simple renaming
tests still pass!
is there anything else that should be renamed while I'm here?
> BCDA-1447 rename funcs to fit specs

- bcda/auth/alpha.go
- bcda/auth/alpha_test.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
RequestAccessToken is no longer being used so it can be removed from the auth interface
- remove RequestAccessToken from alpha and alpha tests
- move RequestAccessToken functionality to MakeAccessToken for okta auth provider
- remove RequestAccessToken from auth provider interface
- remove create-token cli command
MakeAccessToken is already being used by the /token endpoint so this does not change our security posture.  If anything, this PR increases security because it is removing a CLI command that allowed access tokens to be created with a clientID only
tests pass!
Any is welcome
> BCDA-1448 remove deprecated auth provider method and cli command

- docker-compose.test.yml
- docker-compose.yml
- ssas/README.md
- ssas/cfg/envv.go
- ssas/connection.go
- ssas/connection_test.go
- ssas/credentials.go
- ssas/groups.go
- ssas/groups_test.go
- ssas/hash.go
- ssas/logger.go
- ssas/logger_test.go
- ssas/rsakeys.go
- ssas/rsakeys_test.go
- ssas/service/main.go
- ssas/service/main_test.go
- ssas/systems.go
- ssas/systems_test.go
To maintain SSAS as a standalone code base, it needs to have its own implementations of tooling that currently exists in bcda. This PR brings over much of that needed tooling.
Uses of code in these bcda packages needed to be addressed:
- bcda/database
- bcda/auth/Hash
- bcda/auth/rsautils
- bcda/utils
- auth/Credentials
- the functions formerly provided in the database package are now part of the ssas package, and are implemented in connections.go
- the Hash struct and its functions are now part of the ssas package, and are implemented in hash.go
- the functions formerly provided in the rsautils package are now part of the ssas package, and are implemented in rsakeys.go
- the functions formerly provided in the utils package are now part of the cfg package, and are implemented in envv.go
- …
> Move needed tooling code into SSAS; removed bcda dependencies

- bcdaworker/main.go
- bcdaworker/main_test.go
Fixes [BCDA-1487](https://jira.cms.gov/browse/BCDA-1487)
Problem:
Prior to this change, our ndjson responses were returning values from an entries array as key value pairs of a resource map. We now just return the value portion of the resource map, as opposed to each individual entry.
Instead of returning each entry from our json object, we now return each resource value of that entry.
bcdaworker/main.go - grabs the resource value from the resource map.
bcdaworker/main_test.go - removes the "fullUrl" and "resource" strings from our tests. These are no longer included with the new way we drill down into the data. see here: http://hl7.org/fhir/STU3/bundle.html
No, this change does not deal with any PII/PHI.
Yes …
> BCDA-1487 Feature: Returns an "un-nested" resource property in our ndjson responses.

- bcda/auth/provider.go
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
- ssas/systems.go
The SSAS should include a way for either an SGA (e.g., ACO-MS) or a resource server (e.g., bcda) to add systems to the auth service and get credentials. An SGA might use this endpoint to add a system after creating a group. The resource server might use this endpoint for creating systems for integration tests.
Add an endpoint that creates a system and returns credentials.
* Sets up `/ssas/service/admin` directory with:
* api.go
* api_test.go
* router.go
* router_test.go
* Creates SSAS admin router with `POST /system` path
* Creates handler function for `POST /system` in api.go, parsing request body and calling `RegisterSystem()`
* Some changes copied from another pull request, https://github.com/CMSgov/bcda-app/pull/311, so that should be merged first
This adds an API endpoint for SGAs …
> BCDA-1505: Create create-system endpoint

- ssas/groups.go
- ssas/groups_test.go
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
This adds the endpoint to create a group via the auth api according to the ssas tech spec
- add a function to the group models to create a group in the db
- add a function to api.go to take a request and create the group
- add a route to route a post request to the api func to create a group
- add tests
No security concerns here.  While this is still part of the BCDA API the same security should be applied to this new endpoint
Tests pass.  New and old
Any feedback is welcome.  Should we add additional validation to the contents of the JSON that is stored in the groups table of the db?
> BCDA-1144 add post group endpoint to admin routes

- bcda/bcdacli/cli.go
- bcda/web/api.go
- bcda/web/api_test.go
Fixes [BCDA-1554](https://jira.cms.gov/browse/BCDA-1554)
Problem:
Our .ndjson files were set to prematurely expire before finishing completion. Our old logic used to expire files based on the job creation time, potentially cutting short the download window for our users. We've since updated this to be based on job completion time which will give them the full available window for downloading.
New code for expiration to be based on job completion time using the "updated_at" and not the "created_at" timestamp.
bcda/bcdacli/cli.go - changed archive expiring logic to be based on job completion time.
bcda/web/api.go - changed job status logic to be based on job completion time.
bcda/web/api_test.go - changed test to fit new logic
[No] …
> BCDA-1554 Feature: Updated expire logic to be based on job completion time

- ops/Jenkinsfile.build_trigger
The Daily Deployment interferes with engineering workload. 
Change the deployment time to be earlier in the morning.
Update this time from 9 to 8
- [No] This change does not deal with any PII/PHI.
- [No] This change adds new software dependencies
- [No] This change alters security controls or supporting software
-  [No] This change introduces storage of new data
- [No] A security checklist been completed for this change
Unable to test until merged. Only changing one element of a cron though and should be safe.
Please review
> BCDA-1580 update daily dev deployment time

- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
- ssas/systems.go
- ssas/systems_test.go
SSAS needs a system's credentials to be managed separately from all of the other data associated with it. Deactivation is one part of that credential management.
Create an endpoint for deactivating credentials for a system.
* Creates `DELETE /system/[id]/credentials` path
* Adds functions:
* api.go: `deactivateSystemCredentials()`
* systems.go: `DeactivateSecrets()`
These changes allow a system's secret to be deactivated, preventing the system from being authenticated or authorized by the service.
- This change **does not** add new software dependencies
- This change **does not** alter security controls or supporting software
- This change **does not** introduce storage of new data
- A security checklist **has not** been completed for this change
Old and new tests pass.
Any
> BCDA-1507: Create /auth/system/credentials DELETE endpoint

- ssas/groups.go
- ssas/groups_test.go
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
This PR implements the DELETE method for the Group resource
- add the delete route
- add the api func to process the request
- add the model func to delete the group and its associated system and encryption keys from the db
- add tests
No security implications at this point.  This will be an admin endpoint with security to ensure only authorized parties can affect their attributed groups
tests are passing!
any feedback is welcome!
> BCDA-1146 implement delete group endpoint

- ssas/groups.go
- ssas/groups_test.go
- satisfy the sql.scanner interface to save groupdata to the db
no security implications.  this is just a functional bug fix that doesn't affect security
new test passes!
> BUG FIX: fix saving groupData to db by implementing sql.scanner interface

- bcda/models/models.go
- db/api.sql
Fixes [BCDA-1596](https://jira.cms.gov/browse/BCDA-1596)
Problem:
We need to have our db models in place before implementing the 1-800 medicare suppression ETL.
Added db model for 1-800 medicare suppression data.
bcda/models/models.go - gorm db model code
db/api.sql - db schema updates
Yes, this code **will** handle files containing PII/PHI.
This change does **not** add new software dependencies
This change does **not** alter security controls or supporting software
This change does **not** introduce storage of new data
A security checklist **has** been completed for this change
Yes, all tests pass
Any and all
> BCDA-1596 Feature: Added db model for suppression data

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/suppression/suppression.go
We need a way to import 1-800-MEDICARE suppression data from the CLI.
Create a CLI command for importing suppression data.
* Adds `import-suppression-directory` command to CLI, taking flag `--directory` to indicate location of files to import (cli.go)
* Includes tests for this command that result in success, failures, and skipped files (cli_test.go)
- A security checklist exists for the suppression data ETL process: https://confluence.cms.gov/display/BCDA/1-800-Medicare+opt+outs+data+sourcing+-+Security+Checklist This PR does not create the ETL, but calls the functionality added in https://github.com/CMSgov/bcda-app/pull/349.
Tests included. Example of running from command line:
Any
> BCDA-1606: CLI for executing 1-800-MEDICARE suppression data ETL

- Makefile
Incorporating the 1-800-MEDICARE suppression data ETL into our Docker pipeline would help our local environments more closely mimic the production workflow.
* Create Make target `load-synthetic-suppression-data` that calls CLI `import-suppression-directory` command
* Add new make target to `load-fixtures`
This work is for importing synthetic data in local Docker environments. The 1-800-MEDICARE suppression data ETL checklist is here: https://confluence.cms.gov/display/BCDA/1-800-Medicare+opt+outs+data+sourcing+-+Security+Checklist The work in this pull request calls the ETL logic to import synthetic data, but does not change the production ETL process.
Can be tested by running `make load-fixtures` locally. Near the end of the output will be the message `Completed 1-800-MEDICARE …
> BCDA-1608: Incorporate 1-800-MEDICARE ETL into Docker pipeline

- bcda/logging/middleware.go
BCDA request logs include the `Request.RemoteAddr`, which may be the address of the load balancer rather than the originator.
Add log entry field `forwarded_for`, containing the value of the `X-Forwarded-For` header.
This change logs an additional value on requests, but it is data that BCDA already had.
`forwarded_for` log entry field can be seen in the request logs in Splunk.
Any
> BCDA-1459: Incorrect logging of IP

- bcda/bcdacli/cli_test.go
Fixes [BCDA-1661](https://jira.cms.gov/browse/BCDA-1661)
Problem:
Tests were failing locally due to a file being moved that shouldn't. 
The wrong directory was being passed into the import-suppression-directory cli command. Later in the method a call to reset files used the same path location essentially placing the synthetic file in a wrong location...which caused local test failures. 
bcda/bcdacli/cli_test.go - changed directory to actual location of synthetic suppression file
This change does **not** deal with PII/PHI directly.
This change does **not** add new software dependencies
This change does **not** alter security controls or supporting software
This change does **not** introduce storage of new data
Acceptance Validation …
> BCDA-1661 Feature: Fix for local suppression test failures

- Gopkg.toml
- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- docker-compose.test.yml
- docker-compose.yml
- ssas/groups.go
- ssas/service/admin/api.go
- ssas/service/admin/router.go
- ssas/service/admin/router_test.go
- ssas/service/main/main.go
- ssas/service/public/api.go
- ssas/service/public/api_test.go
- ssas/service/public/router.go
- ssas/service/public/router_test.go
- ssas/service/public/tokens_test.go
- ssas/service/server.go
- ssas/service/server_test.go
- ssas/testutils.go
Adds implementations of BCDA auth provider methods for MakeAccessToken() and VerifyToken().
BCDA's auth process, when using the BCDA_AUTH_PROVIDER named 'ssas', makes calls to SSAS.
1) MakeAccessToken() calls /token on SSAS's public port, using the SSAS client. The token endpoint requires authorization.
2) VerifyToken() calls /introspect on SSAS's public port, using the SSAS client. The introspect endpoint requires authorization, and only returns a true / false response indicating whether the provided token is valid or not.
This work is addressed in SIA's currently being drafted. The code is entirely protected by a feature flag in BCDA that must be set at compile time. Further, the SSAS server itself is not built or deployed anywhere except in local test docker containers.
When reviewing, …
> BCDA-1535, BCDA-1538: BCDA's SSAS auth provider gets tokens from and verifies them with SSAS

- bcda/cclf/cclf.go
- bcda/suppression/suppression.go
Fixes [BCDA-1650](https://jira.cms.gov/browse/BCDA-1650)
Problem:
Before this change, files were being deleted at a different time from our set ARCHIVE_THRESHOLD_HR env variable. This change makes our code more consistent and also stays inline with our security posture.
Changed the deletion threshold to match our env var ARCHIVE_THRESHOLD_HR.
bcda/cclf/cclf.go - changed to align with env variable
bcda/suppression/suppression.go  - changed to align with env variable
This change does deal with PII/PHI directly. -This code will be responsible for deleting all cclf and suppression files from our system.
This change does **not** add new software dependencies
This change does **not** alter security controls or supporting software
This …
> BCDA-1650 Feature: Align deletion threshold with env var

- bcda/models/models.go
- db/api.sql
Fixes [BCDA-1490](https://jira.cms.gov/browse/BCDA-1490)
Problem:
The additional import status field was originally non-nullable, but that presented complications for db migrations on existing rows. A default could have been used that set import statuses as a non-complete string but this is cleaner better solution.
Modified the import status field to nullable.
bcda/models/models.go - removed non-nullable constraint 
db/api.sql - removed non-nullable constraint
This change will deal with PII/PHI directly. This code will set an import status for incoming cclf and suppression files.
This change does **not** add new software dependencies
This change does **not** alter security controls or supporting software
This change does **not** …
> BCDA-1490-b Feature: removed non-nullable constraint on import status field

- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/ssas_test.go
- bcda/suppression/suppression_test.go
- ssas/service/admin/router.go
- ssas/service/logging.go
- ssas/service/main/main.go
- ssas/service/public/api.go
- ssas/service/public/router.go
- test/postman_test/1535-SSAS.postman_collection.json
- test/postman_test/SSAS.postman_collection.json
It's difficult to test end-to-end with SSAS because we don't have fixture data. This PR adds a tiny amount of fixture data to SSAS that matches the fixture data in BCDA for the A9994 ACO, which is used in integration testing.
Adds two groups and two systems to support a bcda admin client and an API consumer client.
Because our tables are entirely built by GORM at the moment, I've added the fixtures via code in main.go. They are direct SQL updates because we need to retain fixed values in order to test with BCDA.
This adds very minimal test-only data. There is no PII in the data; it's all fake. Its intended purpose is to support hand-testing while working on integration with BCDA, and possibly incorporated into postman or smoke tests.
- no new software dependencies
- no security controls …
> BCDA-1541: add fixture data for local testing

- Makefile
- bcda/auth/alpha_test.go
- bcda/auth/backend.go
- bcda/auth/middleware.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_middleware_test.go
- bcda/auth/ssas_test.go
- bcda/auth/tokentools.go
- docker-compose.test.yml
- ssas/README.md
- ssas/blacklist_test.go
- ssas/groups.go
- ssas/groups_test.go
- ssas/service/admin/api.go
- ssas/service/admin/api_test.go
- ssas/service/main/main.go
- ssas/service/public/api.go
- ssas/service/public/api_test.go
- ssas/service/public/middleware_test.go
- ssas/service/public/router.go
- ssas/service/public/router_test.go
- ssas/service/public/tokens.go
- ssas/service/public/tokens_test.go
- ssas/service/server.go
- ssas/service/tokenblacklist_test.go
- ssas/systems.go
- test/postman_test/SSAS.postman_collection.json
- test/postman_test/SSAS_Smoke_Test.postman_collection.json
- test/postman_test/manual-SSAS.postman_collection.json
Integrate SSAS authorization into BCDA via BCDA's auth plugin mechanism. We are modeling what we expect ACO-MS group data to look like when they are done with their integration.
- hook ssas auth into bcda middleware
- have ssas plugin evaluate the token and extract necessary AuthData
- add a separate unit test of middleware using SSAS that sets the auth provider so that the test can run during unit tests where the default alpha provider is used
- fix SSAS plugin tests. BeforeTest / AfterTest are used to do ~different~ setup / tear down for specific named tests via implementing a function for each test. The appropriate function here is SetupTest and TearDownTest, which setup / tear down the ~same~ values before and after every test.
- created a MockSSASServer for use in plugin tests, along …
> BCDA-1537 SSAS: Functional end-to-end Authorize requests

- Dockerfiles/Dockerfile.ssas
- Makefile
- ssas/README.md
- ssas/service/admin/api_test.go
- ssas/service/main/main.go
- ssas/service/main/main_test.go
- ssas/service/public/api_test.go
- ssas/service/tokenblacklist.go
Our current means of bootstrapping SSAS into docker does not work very for the AWS environments where the database is persistent. It also adds to the chicken and egg challenges of deploying a new system with dependencies for the first time. This PR adds commands to make it easier.
Separate commands now exist to migrate the database, add fixture data, add new admin clients, reset secrets and start the service.
Also see the CLI section added to the ssas README.
- No new software dependencies
- No security controls or supporting software altered
- No new data stored or transmitted
- No security checklist (other than this informal one)  is needed for this change
- Does not require more information or team discussion to evaluate security implications
All tests pass.
New test added for …
> BCDA-1877: SSAS: Add helpful CLI commands to simplify deployment

- bcda-site-static/user_guide.md
Fixes [BCDA-1945](https://jira.cms.gov/browse/BCDA-1945)
Problem:
After deploying a new release we have to update our synthetic credentials for our sandbox users. This change will display the new **synthetic** client id and client secret credentials on our sandbox UG.
Update to user guide sections involving synthetic credentials.
bcda-site-static/user_guide.md - changed synthetic credentials.
No, this change does not deal with any PII/PHI. This is only a visual update to our user guide to match our synthetic system credentials.
Acceptance Validation
Yes, tested new creds and they work. Smoke test also passed using the same credentials.
Any and all
Screenshot:
> BCDA-1945 Feature: changed synthetic creds for sandbox userguide

- bcda/web/router.go
- bcda/web/router_test.go
The sandbox user guide URL should redirect to bcda.cms.gov.
Remove user guide file server from bcda-app and redirect user guide paths to a URL set in an environment variable.
* Sets response code to `301 Moved Permanently` for `/`, `user_guide.html`, `encryption.html`, and `decryption_walkthrough.html`, redirecting to value of env var `USER_GUIDE_LOC` or default `https://bcda.cms.gov`
_Static Site Security Checklist (Migrating User Guide to bcda.cms.gov)_ https://confluence.cms.gov/pages/viewpage.action?pageId=154444934
Test updated for path `/` to confirm `301` response. Can be run locally to see the redirects in action.
Any
> BCDA-1967: Redirect sandbox.bcda.cms.gov to bcda.cms.gov

- bcda/bcdacli/cli.go
- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/encryption/encryption.go
- bcda/encryption/encryption_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcda/servicemux/servicemux_test.go
- bcda/testUtils/client.go
- bcda/utils/common.go
- bcdaworker/main.go
- bcdaworker/main_test.go
Some functions in bcdaworker/main.go are difficult to test and maintain because they do a lot of different things.
Simplify `processJob()` and `writeBBDataToFile()`, and related functions.
* Moves parts of `processJob()` and `writeBBDataFile()` into new functions so the parent functions are more readable
* Shortens and/or clarifies BlueButtonClient function names. `Get{ResourceType}Data()` functions have been renamed to `Get{ResourceType}()` and `GetBlueButtonIdentifier()` is now called `GetPatientByHICNHash()` (it returns patient data, not only a BB ID)
* Replaces `EncryptAndMove()` with `EncryptFile()` so moving the output is decoupled from the encryption step. Both steps happen in the new `encryptData()` function in bcdaworker/main.go
* Cleans up linter issues that were causing failed …
> BCDA-1420: Refactor bcdaworker/main.go

- Makefile
Due to a likely combination of our growing codebase and enhancements made to the `golangci-lint` tool, the time it takes to lint our code now exceeds 1 minute.  The default deadline is set to 1 minute in the `golangci-lint` tool, so we will need to explicitly force it to be larger.
Increase the deadline to 2 minutes on the command line invocation of `golangci-lint`.
Updated the `Makefile` to explicitly call `golangci-lint` with a deadline of 2 minutes, overriding the default of 1 minute.
There are no security implications with this change.  This change simply tells our linting tool to wait 2 minutes (instead of 1 minute) to complete
Build/Package is passing in Jenkins against this feature branch: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/991/
Please review.
> Increase deadline for linter from 1m (default) to 2m.

- bcda/models/SwaggerStructs.go
- bcda/web/api.go
BCDA Swagger describes a 401 response as "Undocumented" for some endpoints.
Indicate the reason for a 401.
This adds a description of 
>Unauthorized. The provided credentials are invalid for the requested resource.
to 401 responses on job status, data, and export endpoints (all resource types).
No security implications. This is an improvement to documentation.
Can be seen in Swagger.
Any
> BCDA-1857: Document 401 responses in Swagger

- test/postman_test/prod.postman_environment.json
We currently have no smoke tests running on the production environment.
We are updating the smoke test job in jenkins to run on prod in https://github.com/CMSgov/bcda-ops/pull/307 but we need an app code change for postman tests to pass.
Add a prod config for postman tests.
No security implications. This is not a new test, just an additional config file.
https://bcda-ci.adhocteam.us/job/MMurphy%20-%20BCDA-1360/4/
Please review
> BCDA-1360 add prod config for postman tests

- ssas/service/public/oktamfa_test.go
SonarQube has alerted that two of our unit tests hard-code a string as a mock password.  This PR assigns a random value to those strings as a better password pattern.
- 16 random characters are assigned to each string
No net change to security is introduced, though arguably the net result is an appreciation of the kind of issue SonarQube can catch.
Final validation will occur after merging with `master`, when SonarQube runs its tests.
Please point out anything I've missed.
> BCDA-2035: SSAS: Update test for SonarQube

- .travis.yml
- Makefile
We are redundantly linting the SSAS code: once as part of API build and once as part of SSAS build.  The SSAS code should only be linted as part of the SSAS build.
Exclude linting of SSAS code from both `gosec` and `golangci-lint`.
Updated the `Makefile` to explicitly skip the SSAS code when executing `gosec` and `golangci-lint` as part of the API lint target.
Updated the `test` and `test-ssas` targets so that `test` is API-specific and `test-ssas` is SSAS-specific.
There are no security implications with this change.  This change simply tells our linting tool which directories to lint.
Build/Package is passing in Jenkins against this feature branch: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1012/
Please review.
> Update CI to remove redundant linting of SSAS code

- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
- bcda/suppression/suppression.go
- bcda/suppression/suppression_test.go
The most recent CCLF ETL process was the first execution of that process in which our software was required to accommodate all >500 ACOs (up until that point, we were only ingesting CCLF data for 4 ACOs).  We learned that with >500 ACOs, the ETL process takes >24 hours and the estimation is that it should take ~48 hours.  As a result, our file retention period (for CCLF files and 1-800-Medicare suppression files which enter the BCDA NFS via CMS EFT) must be increased from 24 to 72 hours.
- Updated the ETL code to remove files which are older than 72 hours instead of 24 hours.
- Updated the unit test code to accommodate the new time threshold.
- Modified several security documents (specific documents identified in the `Security Implications` section)
This change means that CCLF files and …
> BCDA-1994: Increase Retention Threshold for Data Files on NFS

- Makefile
Due to a likely combination of our growing codebase and enhancements made to the `golangci-lint` tool, the time it takes to lint our code now exceeds 2 minutes.  
Increase the deadline to 3 minutes on the command line invocation of `golangci-lint`.
Updated the `Makefile` to explicitly call `golangci-lint` with a deadline of 3 minutes.
There are no security implications with this change.  This change simply tells our linting tool to wait 3 minutes (instead of 2 minutes) to complete
Build/Package is passing in Jenkins against this feature branch: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1069/
Please review.
> Increase linter deadline to 3 minutes

- test/datagenerator/1800medicare.go
This pull request contains improvements to the script for creating synthetic 1-800-MEDICARE files.
* Ensures that when a source code is set, its associated effective date, mechanism code, and preference indicator are also set, as indicated by the ICD
* Lowers max records per beneficiary to 3
* Adds trailer row with date and record count in file, per ICD
No security implications. This is a synthetic data generator.
Can be tested by running `go run 1800medicare.go`
Any
> Improvements to 1-800-MEDICARE synthetic data script

- bcda/models/SwaggerStructs.go
- bcda/web/api.go
Fixes [BCDA-2327](https://jira.cms.gov/browse/BCDA-2327)
Problem:
An incorrect description was given for one of our successful responses to the data retrieval endpoint. It described all responses as EOB which is incorrect. This has been changed to a more generic description to fit all bulk resource requests.
Proposed Details:
bcda/models/SwaggerStructs.go - changed to a more generic descriptor
bcda/web/api.go - uses the new response description
This change does **not** deal with PII/PHI at all.
Yes, locally running swagger.
Screenshot:
Any and all
> BCDA-2327 Feature: Fixed description bug for successful responses

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
BB is unable to analyze BCDA request metrics because BCDA is sending BB-specific headers with blank values.
Stop sending the following BB-specific headers:
- `BlueButton-BeneficiaryId`
- `BlueButton-OriginatingIpAddress`
- `BlueButton-BackendCall`
No PHI/PII is involved.  This change helps BFD track requests at a more granular level.
Local tests passed.  Confirmed with BFD team that access logs are correct when removing these headers from requests.  
Please review.
> BCDA-2359: Do not send BB-specific headers with blank values

- bcda/models/models.go
- bcda/models/models_test.go
Queries to `cclf_beneficiaries` to find pre-existing Blue Button IDs are proving to be inefficient (3-4 second execution time).   Acquiring the Blue Button ID directly via lean `/Patient` call to Blue Button might speed up processing.
- Removed inefficient query.
This is a performance optimization implemented by removing code.  No security implications are involved. 
Only local testing has been performed, due to DB/data size differences between `prod` and lower environments.
Additionally, the straight query was executed on `prod` and proven to take ~4 seconds in most cases (note that in the query below, the [HICN is synthetic](https://github.com/CMSgov/bcda-app/blob/master/shared_files/cclf/files/synthetic/test/small/ZC8#L2) 
```
time psql <SECRET_DB_CONN_STRING> -c "select * from …
```
> BCDA-2373: Improve Performance of Blue Button ID Acquisition

- bcda/responseutils/writer.go
- bcda/web/api_test.go
- bcda/web/router.go
- bcda/web/router_test.go
- docker-compose.yml
Fixes [BCDA-2372](https://jira.cms.gov/browse/BCDA-2372)
Problem:
We have progressed past the point of needing feature flags for 2 of our main bulk data requests. At first, both Coverage and Patient endpoints were only exposed via environment variables allowing a smooth rollout of features. At this point in time the env vars are no longer needed as both have been fully implemented.
Removed old environment variables for both patient and coverage endpoint exposure.
bcda/responseutils/writer.go - maintained both endpoints but removed extra methods
bcda/web/api_test.go - removed feature flags from tests.
bcda/web/router.go - removed feature flags for coverage and patient routes.
bcda/web/router_test.go - removed feature flags from tests.
Security …
> BCDA-2372 Feature: Cleanup for removing old feature flags for coverage and patient

- bcda/models/models.go
- db/migrations/20191211-index-cclf-imports.sql
The `aco.GetBeneficiaries()` method is slower than we'd like.  In particular, https://github.com/CMSgov/bcda-app/blob/c5c04b84b08fd1a1416dd665e167016b412101e9/bcda/models/models.go#L265 has been taking about 11 seconds to complete.
After adding indexes on two columns, it is sped up 100-fold.
- Add two indexes to the `cclf_beneficiaries` table
- `hicn`
- `file_id` 
The addition of these indexes has a small impact on availability.  The intended (and tested) impact is a significant increase in speed for some queries.  The possible unintended impact would be a slowdown for writes to the table, but 1) the chance is low and 2) this would affect automated processes only, not user queries.
This is already active in `prod` and `dev`.  GORM will update the `test` during the next deployment, and we …
> BCDA-2414 Add indexes to cclf_beneficiaries

- bcda/web/api.go
If the job status endpoint is called while the job is `In Progress`, the API attempts to double-check the job to see if it is actually done.  In the event where the workers complete the job during the small window of time where the API is double-checking, the files will never get moved from `staging` to `payload` because the API 
As a result, we'll need to fix this to ensure job state is only transitioned by workers.
Updated the job status endpoint functionality so that if the job is `In Progress`, we simply return the progress; we no longer attempt to see if the job is `Complete`.
No PII/PHI is dealt with in this change.  This is a bug fix which eliminates a potential race condition in transitioning job state.
Validated via smoke test execution on `dev` and `test`.
Please review.
> Bug Fix: Only the worker should transition job state

- bcda/bcdacli/cli_test.go
- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
- bcda/cclf/testutils/cclfUtils_test.go
- bcda/web/api_test.go
If for some reason an old CCLF file is presented, or a post-dated CCLF file, we should not attempt to ingest the data. 
- Ignore CCLF files in the future
- Ignore CCLF files more the 45 days in the past
- For testing purposes, allow for an optional environmental variable to set the file comparison date, which defaults to `time.Now()`
If anything, this change improves security by reducing the range of unexpected and probably incorrect data that will be used by BCDA.
- Existing and new tests passing
- Is there any downside to using the environmental variable for selecting a file comparison date?
> BCDA-2491 Feature: Filter CCLF files to valid date range

- bcda/models/models.go
- bcda/models/models_test.go
- bcda/servicemux/servicemux.go
- bcda/web/api.go
For large ACOs, the response to a bulk data request can exceed 30 seconds.
- Increase the application timeout to align with the ALB's upper bound of 60 seconds.
- Optimized the logic that is executed when a bulk data request is made, so that retrieval of beneficiaries is performed one time instead of multiple times per resource type.
This change does not affect data access; it instead optimizes existing logic.
This feature branch was deployed to `dev` and tested by using the extra large test ACO to make a bulk data request.
- Using code in `master`,  the response time from bulk data request using extra large test ACO is ~2.5s.
- Using code in this feature branch, the response time from bulk data request using extra large test ACO is ~1s. 
Please review.
> BCDA-2503: Optimize response time for bulk data request

- bcda/models/models.go
Fixes [BCDA-2506b](https://jira.cms.gov/browse/BCDA-2506b)
Problem:
After merging and testing the original feature ticket BCDA-2506, a bug was discovered in our smoke tests for blue button ids that were set as NULL. Our original query only checked for empty string values but we also need to account for values set to NULL as well.
Adds a null check to both the suppression query list and for the population of suppression records that need to request for blue button ids.
bcda/models/models.go - Adds a null check
This particular change does not, but the overall change in ticket BCDA-2506 does deal with PII/PHI data. It uses hashed hicn values to make request for BB ids.
https://confluence.cms.gov/pages/viewpage.action?spaceKey=BCDA&title …
> BCDA-2506b Feature: Fixed bug for sql statement for null blue_button_ids

- bcda/auth/alpha_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/mokta.go
- bcda/auth/ssas.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcda/web/api.go
- bcda/web/api_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
- db/api.sql
- db/fixtures.sql
- db/migrations/20200120-drop-users.sql
- test/smoke_test/smoke_test.sh
Our authentication and authorization no longer has the concept of a user, but jobs and alpha tokens still reference them.  This PR removes all user references.
- Drop `users` table
- Drop `jobs.user_id` column
- Remove all code and fixture references
In `dev` and `test`:
- Deploy code
- `psql -f db/migrations/20200120-drop-users.sql` from deployer's laptop
- Verify success (`users` table should be gone)
In `opensbx` and `prod`:
- Deploy code
- Transfer `db/migrations/20200120-drop-users.sql` to API server in AWS environment
- SSH to server and run `psql -f 20200120-drop-users.sql`
- Verify success (`users` table should be gone)
This change should be security-neutral, removing unused database and code artifacts.
All tests still run ✅ 
Are there any other references?
> BCDA-2596 Maintenance: Remove users table

- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
High CPU utilization occurs when a large ACO makes a request.
After extensive investigation, it was determined that the high CPU utilization was resulting from the fact that we create a new DB connection for each beneficiary processed in a job.
Reuse the DB connection for all beneficiaries within a single worker's job.
Updated the job processing code to ensure that a DB connection is shared for all processing within the single job.
This is a performance optimization to existing processing.
Updated CPU utilization chart:
Additional enhancements to be addressed in [BCDA-2621](https://jira.cms.gov/browse/BCDA-2621)
Please review.
> Single DB Connection per Worker Job

- bcda/models/models.go
Fixes [BCDA-2506c](https://jira.cms.gov/browse/BCDA-2506c)
Problem:
After implementation of the original BCDA-2506 it was noticed that some log statements were duplicated with similar bits of information.
This change removes the extraneous log statements
bcda/models/models.go  - removed extra log statements
No, this change does **not** deal with any PII/PHI data
Tested locally and it works. See new output below
Any and all
> BCDA-2506c Feature: Removed extraneous log statements

- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/okta.go
- bcda/auth/okta_test.go
- bcda/auth/provider.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
In addition to the UUID that we use internally to represent ACO's, we would like our logs to contain the CMS ID (the one formatted like: A0000).  This PR adds this value to the logs for all three auth providers in the code base (Alpha, Okta, and SSAS).
- Ensure the logging middleware contains data for the CMS ID
- Replace the defunct `AuthData.UserID` with `AuthData.CMSID`
- Remove any remaining `AuthData.UserID` and `Credentials.UserID` references
More information is now contained in the log, but it is [publicly available information](https://data.cms.gov/Special-Programs-Initiatives-Medicare-Shared-Savin/Performance-Year-2020-Medicare-Shared-Savings-Prog/kuwq-yjm7).
- All improvements welcome
> BCDA-2592 Feature: Log CMS ID for API requests

- bcdaworker/main.go
Significant DB CPU utilization optimization was introduced in https://github.com/CMSgov/bcda-app/pull/445.  Despite the optimization, the repeated spikes to ~50% CPU utilization are still a concern.  It was determined that we are performing redundant writes of BB ID to the database.  To reduce the repeated spikes, the redundant writes of BB ID to the database should be addressed.  
The current state of CPU utilization is depicted below (showing the repeated spikes).  The image is pulled from the `Acceptance Validation` portion of https://github.com/CMSgov/bcda-app/pull/445.
Updated the job processing code so that a BB ID is only written to the database once per CCLF period.
This is a performance optimization to existing processing.
The image below shows CPU utilization during a test …
> BCDA-2621: Write to DB only when BB ID requires an update

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/models/models.go
- bcda/testUtils/client.go
- shared_files/synthetic_beneficiary_data/Patient_MBI
Fixes [BCDA-1551](https://jira.cms.gov/browse/BCDA-1551)
Problem:
As currently implemented our users have no way of identifying patients from the downloaded payload. The identifier values were previously hashed, but with this change values will be presented as usable plain text.
Added the necessary header values to our BFD request to provide a response with a plaintext MBI.
bcda/client/bluebutton.go - added necessary header value
bcda/client/bluebutton_test.go - testing logic for new header value
bcda/models/models.go - changed to validate the plaintext identifier when in MBI mode.
bcda/testUtils/client.go - changed to use synthetic MBI from static data file
shared_files/synthetic_beneficiary_data/Patient_MBI - changed to a synthetic plaintext MBI …
> BCDA-1551 Feature: Change for recieving plaintext MBI

- bcdaworker/main.go
- docker-compose.yml
Our workers are under-utilized, so lets see how they do with 3 threads doing work instead of 2.  
Increased the `WORKER_POOL_SIZE` from the default of 2 to 3 in local docker-compose stack.  This work was done in conjunction with this PR: https://github.com/CMSgov/bcda-ops/pull/421
No PHI/PII is affected as part of this change; it is strictly a performance optimization.
Local testing using this feature branch resulted in success.  The majority of the testing in AWS for this feature was documented in the `bcda-ops` PR here: https://github.com/CMSgov/bcda-ops/pull/421
Please review.
> BCDA-2714: Update worker pool size configuration in local environment

- test/postman_test/BCDA_Tests.postman_collection.json
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
There is a test in our postman suite which fails in AWS every once in a while due to the environment being uncontrolled.  We should not have performance tests mixed in with our functional tests.
Relax Postman performance metric from 100 ms to 200 ms
`		"pm.test(\"Response time is less than 200 ms\", function() {",
"    pm.expect(pm.response.responseTime).to.be.below(200);",
"});",`
```
→ Get metadata
GET http://api:3000/api/v1/metadata [200 OK, 1.49KB, 11ms]
✓  Response time is less than 200 ms
✓  Status code is 200
✓  Content-Type is application/json
✓  Resource type is CapabilityStatement
✓  Schema is valid
```
> BCDA-2721 : Relax Postman performance test metric

- bcda/cclf/testutils/cclfUtils.go
- bcda/suppression/suppression.go
- bcdaworker/main.go
- test/performance_test/performance.go
- test/smoke_test/bcda_client.go
Out-of-band modifications to `gosec` affected BCDA's codebase, related to deferring `Close()` on `os.File`.
The change to `gosec` can be viewed [here](https://github.com/securego/gosec/pull/441/files).
`nosec` was added to the affected code, to ignore the linting suggestion, in order to un-block the build.  In addition, a new ticket was created to re-address the situation in a manner that can be planned out (as opposed to rushed to un-block the build).
The new ticket is [BCDA-2804](https://jira.cms.gov/browse/BCDA-2804).
No PHI/PII is affected in this update.
Linting is passing in local, Travis, and Jenkins now.
Please review.
> Ignore gosec rule G307 when deferring file closure

- .github/pull_request_template.md
This conscientious team "learned" the same lesson repeatedly over a couple of sprints: most changes could benefit from being tested in `dev`.  How do we remind ourselves?  This PR drafts language that could prompt us in _every_ PR.
- Add comments to the `Acceptance validation` section to clarify that, while deployment to `dev` is not _required_, you should have carefully thought through why your code couldn't _possibly_ be affected by the deployment environment, or require additional changes to the CI/CD pipeline.
There is a slight risk that unreviewed code deployed to `dev` could open up security risks.  These risks are mitigated by the isolation we place on that environment.
No. This change is limited to the PR process, and will not affect running code, databases, or integrations.
- …
> BCDA-2718 Best Practices: Dev deployment prompt added to PR template

- bcda/web/middleware.go
- bcda/web/middleware_test.go
- bcda/web/router.go
Finding from ACT: Add must-revalidate, Add Pragma 
Also add other headers provided to us by Akamai CDN 
- Adds `must-revalidate`, `no-store`, `no-cache`, `max-age=0` to cache control header
- Adds `Pragma:no-cache` to header
- Rename `HSTSHeader` to `SecurityHeader` to be more generic
- Indicates that once a resource becomes stale, caches must not use their stale copy without successful validation on the origin server.
- Add accompanying unit tests
https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1371/
`curl --insecure -i https://bcda-api-dev-402091678.us-east-1.elb.amazonaws.com/api/v1/metadata`
```
HTTP/2 200
date: Mon, 16 Mar 2020 17:11:24 GMT
content-type: application/json
content-length: 1699
cache-control: no-cache; no-store; must-revalidate; max-age=0
pragma: …
```
> BCDA-2728 Feature: Add "cache-control" and "pragma:no-cache" to security header

- bcda/web/middleware.go
- bcda/web/middleware_test.go
Set X-Content-Type-Options header to `nosniff` per ZAP analysis
Add header to existing security headers
- https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1374/
`curl --insecure -i https://bcda-api-dev-402091678.us-east-1.elb.amazonaws.com/_version`
```
HTTP/2 200
date: Mon, 16 Mar 2020 19:17:39 GMT
content-type: application/json
content-length: 23
cache-control: no-cache; no-store; must-revalidate; max-age=0
pragma: no-cache
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
```
`curl --insecure -i https://bcda-api-dev-402091678.us-east-1.elb.amazonaws.com/_auth`
```
HTTP/2 200
date: Mon, 16 Mar 2020 19:18:07 GMT
content-type: application/json
content-length: 24
cache-control: no-cache; no-store; must-revalidate; …
```
>  BCDA 2729 Feature: Set X-Content-Type-Options header to nosniff

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
The ordering of the newest Postman tests related to `_since` result in a `429` in `prod`.  This was not encountered in any of the lower environments because `429` is only relevant in `prod`.
- Updated the sequence of tests to ensure the same resource type is not requested back-to-back in the Postman tests.
No PHI/PII is affected by this change.
Feature branch was used to run integration tests against `prod` successfully [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/1754/parameters/).
Please review.
> Update order of Postman tests to avoid 429 in production

- bcda/auth/middleware.go
- bcda/responseutils/writer.go
- bcda/web/api.go
- bcda/web/api_test.go
- bcda/web/middleware.go
- bcdaworker/main_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
In some cases throughout our code, translation of error scenarios to a FHIR-compliant `OperationOutcome` format was omitting key details.
- Updated our utility function to properly propagate the `detailsCode`.
- Updated usage throughout the application to properly designate between `detailsCode` and `detailsString`.
- Updated relevant tests to handle the new usage of utility function.
PHI/PII is not affected by this change.
All integration tests were run locally with successful results.  There is nothing in the AWS environment or persistent DB which would require this to be tested in `dev`.
Please review.
> BCDA-2833: Update error logging to comply with OperationOutcome format

- Dockerfiles/Dockerfile.tests
A new version of `golangci-lint` was released yesterday, and it is causing problems in our environment.  The new version can be found [here](https://github.com/golangci/golangci-lint/releases/tag/v1.25.0).
We are seeing the following errors when using this version to lint our code:
```
src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in slice literal
Service 'tests' failed to build: The command '/bin/sh -c go get -u …
```
> Pin `golangci-lint` at v1.24.0

- README.md
Fixing the link the the README to go to the correct link for the API documentation 
* Changed the API documentation link in the README
Changed the link for API documentation to go to [https://bcda.cms.gov/sandbox/user-guide](https://bcda.cms.gov/sandbox/user-guide/)
This change does *not* deal with PII/PHI. This is purely a change to the documentation to be more usable
Was able to see the link going to the correct location when viewing the README for this branch on GitHub.
This branch has not been deployed to the `dev` environment since this change does not effect the either production or test code but only effects documentation
> BCDA-3011: Updated API documentation link in README

- bcda/responseutils/writer_test.go
We were missing unit test coverage for the entire `responseutils` package.
- Added some unit tests for `writer.go` in `responseutils` package, which brings us up to >80% for the `responseutils` package.
All tests passing locally and in Travis.  
Test coverage for `responseutils` is up above 80% now.
Please review.
> BCDA-658: Unit tests for responseutils writer

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
In `prod`, if an ACO requests the same resource type repeatedly, they will be presented with a `429` response.  We have several Postman tests which validate this behavior.  However, in some scenarios, our tests might execute too quickly and inadvertently request the same resource type before the previous one has completed by the asynchronous worker job (this can occur in `prod` when existing jobs are in the queue; for example, from a real ACO requesting data).
An example of this occurring can be viewed [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/1928/console).
- Re-arrange tests slightly to ensure that we don't incur a `429` when we don't expect it (due to tests executing too quickly).
Smoke tests executed against `dev` using this feature branch with …
> Re-arrange order of Postman tests to avoid 429 race condition

- bcda/models/models.go
A new rule was added to the security linter we use (`gosec`), and it detected an issue with one of our `for` loops.
Background information: 
- [Here](https://github.com/securego/gosec/issues/438) is the initial issue identified as a gap in `gosec`.
- [Here](https://github.com/securego/gosec/pull/443) is the implementation of the new rule.
- Updated the `for` loop to ensure we are using a new memory address for each element in the `RangeStmt`.   
This is a code enhancement, identified by our `gosec` linter, ensuring we are handling memory properly within a `RangeStmt`.
All automated tests in local and Travis are still passing.
Please review.
> BCDA-3034: Address G0601, protecting us against accessing invalid memory

- bcda/bcdacli/cli_test.go
- bcda/web/api_test.go
- db/fixtures.sql
- unit_test.sh
Some of our unit tests reference the same ACO identifier; and, because our unit tests share a test database, race conditions can occur because our unit tests are executed in parallel to speed up the pipeline.
- Run tests in sequence, similar to how the SSAS tests are executed
- Update fixtures to ensure we can reference ACOs by name
Several tests executions succeeded locally.
Tests are passing in Travis.
Tests are passing in [Jenkins](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1537/).
Please review.
> Fixes Race Condition in Unit Tests

- bcda/models/models_test.go
In one suppression test, we were leaving dangling data in the database which could potentially be interfering with other tests.
Ensure test data gets cleaned up appropriately.
- Added a `defer` statement in one of our suppressions tests, to appropriately clean up data created as part of the test.
Passing in all environments.  [Here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1558/) is the Jenkins execution.
Please review.
> Ensure suppression test data is removed once test is complete

- bcda/bcdacli/cli.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main.go
- db/api.sql
Early in 2020, there was a period of time where CCLF was based on MBI and 1-800-Medicare was based on HICN.  As a result, we needed to perform suppression logic based on BB ID (so we are comparing apples-to-apples).  In March, the 1-800-Medicare file was moved over to MBI, but we kept the suppression logic based on BB ID (in order to support historical suppression entries which contained HICNs).  Now that a few months has gone by and the CCLF files are synchronized with latest/greatest suppression data based on MBI, we can perform our suppression logic based solely on MBI and no longer need to acquire BB IDs for each entry (because, now, CCLF and 1-800-Medicare data is both based on MBI and we can compare apples-to-apples).
- Updated logic to remove the overhead of acquiring BB ID for …
> BCDA-3072: Suppression Logic Based on MBI

- test/datagenerator/1800medicare.go
The SecureGo team recently improved the linting rules around `G404`.  The details can be found here.  As a result, some of our test code was marked with `Use of weak random number generator (math/rand instead of crypto/rand)`.  Since only test code was affected (and we don't need a cryptographically secure random number generator in our test code), we should be ignoring `G404` in the affected file.
- Added `#nosec G404` to the file in our test suite.
Linting succeeds locally.
Please review.
> Ignore G404 in test data generator file

- Dockerfiles/Dockerfile.bdt
- Makefile
This branch adds a make recipe for running the bulk data test suite against bcda.
To test, checkout this branch and use the following command to test the sandbox env:
```
$ make bdt BDT_BASE_URL=https://sandbox.bdca.cms.gov BDT_CLIENT_ID=3841c594-a8c0-41e5-98cc-38bb45360d3c BDT_CLIENT_SECRET=f9780d323588f1cdfc3e63e95a8cbdcdd47602ff48a537b51dc5d7834bf466416a716bd4508e904a
```
* Adding make recipe
* Adding Dockerfile
The Dockerfile checks out the original repo as well as a forked repo (based off the work of @richbraman) that has the changes necessary to authenticate with our API.
A patch is generated and applied against the original repo. We do this instead of trying to push our changes back to the original repo. This way, we can apply our changes to the most updated version of the bulk …
> Adding custom Bulk Data Test Suite and Test Runner tool

- bcdaworker/main.go
The SecureGo team recently improved the linting rules around `G304`.  The details can be found [here](https://github.com/securego/gosec/issues/488).  As a result, one line of our code was flagged for opening an error file named by a variable.  This behavior is intentional, so we should ignore the linting rule.
- Added `#nosec` to the `bcdaworker` file
Linting succeeds locally.
Please review.
> Add nosec for G304

- bcda/auth/client/ssas.go
- bcda/client/bluebutton.go
- bcda/servicemux/servicemux.go
A new linting rule was added to `gosec` [today](https://github.com/securego/gosec/pull/493/files), and our software is not compliant with the new rule.  The new rule aims to be more strict at analyzing the Min/Max TLS versions supported in the software.
Because our Akamai configuration only support TLSv1.2 and above, we can explicitly specify a `MinVersion` of TLSv1.2 in our Go code.
From Akamai configuration:
In this PR, we are aligning the software configuration defining the minimum TLS version to our infrastructure configuration.
[Deployed](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1597/parameters/) to `dev` and passed all [smoke tests](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2053/).
Please review.
> Update TLS Config to explicitly specify MinVersion

- Dockerfiles/Dockerfile.bdt
This branch removes the patching that we do so that our job does not break whenever an update to the original repo happens.
Removing Dockerfile script that creates and applies a patch.
From now on we assume all the code we want to run is in our own fork.
Docker image is properly built and executed.
Going forward we will need to periodically merge in the changes from the upstream repo. Does this make sense? All feedback is welcome.
> BCDA-3293 Remove dependency on upstream repo for BDT

- Makefile
Fixing the BDT script so that it always uses the values for ACO A9994 when using the Makefile target
This solves the issues raised in by the ticket but does lock us into only testing against ACO A9994. I struggled to get a conditional to work in the make file so you could optionally pass in different ACO. Do we need something like that or is this enough since we are only using this for local testing as is?
> BCDA-3336: Ensure BDT Scan Runs Locally

- docker-compose.yml
Set the user guide location to `stage.bcda.cms.gov` when developing locally
> BCDA 3265: Switched user guide location to stage environment

- Makefile
We want to be able to dynamically set the lint timeout option to handle different execution environments.
1. Add an optional lint timeout (`LINT_TIMEOUT `) parameter (defaulted to 3m) to the make-lint command.
This option will allow callers to dynamically set a timeout to match their environment.
- Ran BCDA - Build and Package job successfully. [Job link](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1652/)
Please review
> BCDA-3378 Add timeout option in make lint command

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
Ensure that we're making requests to Blue Button API with `Accept-Encoding: gzip` set.
We had initially thought that we need to explicitly add the `Accept-Encoding: gzip` when making requests to Blue Button API. After looking deeper in the implementation, we need to ensure that we **do not** set this header. If the header is present, then the HTTP client needs to explicitly handle the decompression of the gzip data.
The underlying `http.Transport` will handle this for us if we have `DisableCompression: false`. It transparently decompresses the data and the HTTP client is given the decompressed data.
Actual changes:
1. Adding tests to verify that we are handling gzip responses from the server successfully (i.e. the response does not need to be explicitly de-compressed).
2. Add more …
> BCDA-3370 Add tests to verify Blue Button client uses gzip encoding

- bcda/web/api.go
With the toggling of the feature flag for enabling the enhanced `/Group` feature being done as part of [this ops ticket](https://jira.cms.gov/browse/BCDA-3203), our Swagger documentation should be updated accordingly.
- Update Swagger documentation to reflect state of `/Group` in `prod`
Please review.
> BCDA-3421: Update Swagger documentation for /Group.

- Makefile
- docker-compose.yml
Removes a failure point around the documentation Docker container.
```
ERROR: for documentation  You cannot remove a running container DOCUMENTATION_ID. Stop the container before attempting removal or force remove
```
This was a result of each Make (lint, package, unit-test) command re-creating the documentation container.
Update docker-compose files to allow for concurrent execution of multiple stages without needing to sleep between stages.
1. Remove unneeded dependency between the queue-db container and the documentation container.
Successfully ran build & deploy job
>  BCDA-3304 - Remove unnecessary dependency between queue-db and documentation

- docker-compose.yml
We want to shorten the feedback loop for issues with implementation issues. This means running smoke tests with a similar configuration that's being used in production.
1. Re-enable cutoff time parameter when retrieving the latest CCLF file. This means that we'll remove the environment variable (CCLF_CUTOFF_TIME_DAYS) that was set to 0 (disabled).
CI tests passing
> BCDA-3498 - Re-enable cutoff time lookup on smoke-tests

- .gitignore
- Dockerfiles/Dockerfile.openapi
- Makefile
- docker-compose.yml
- ops/build_and_package.sh
- ops/swagger_to_openapi.sh
Included with the Swagger documentation we also want to also include OpenAPI documentation
* Added new openapi conversion docker container and migration script
* Added check to stop packaging if documentation fails to generate
Deployed to dev. OpenAPI documentation is available at https://dev.bcda.cms.gov/api/v1/swagger/openapi.json
> BCDA-3297 Swagger to OpenAPI Conversion

- Gopkg.lock
- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
- bcda/cclf/metrics/metrics.go
- bcda/cclf/metrics/metrics_test.go
- vendor/github.com/newrelic/go-agent/_integrations/nrlogrus/nrlogrus.go
To get better insights into how we can improve our CCLF file ingest performance, we need to time the various methods. 
Adding tracing to the following calls:
1. sortCCLFFiles
2. ImportCCLF0
3. ValidateCCLF8
4. ImportCCLF8
5. CleanupCCLFFiles
Brought in `github.com/newrelic/go-agent/_integrations/nrlogrus`. Only used in test scope to inject a logger to validate our usages of NewRelic transaction/segments.
1. CI passes
2. Able to ingest CCLF data.
3. Timing metrics reported to NewRelic.
> BCDA-3428 - Adding timing metrics to CCLF Ingest process

- bcda/cclf/cclf.go
- bcda/cclf/importer.go
- bcda/cclf/importer_test.go
- vendor/github.com/DATA-DOG/go-sqlmock/go.mod
We want to improve CCLF ingestion process by optimizing how we insert data into our Postgres instance.
Change ingest pattern from single INSERT call per beneficiary to use COPY FROM that allows us to stream all of the beneficiary records.
When using single INSERT per beneficiary, we're paying overhead on opening and committing the transaction for every single INSERT call.
Postgres documentation recommends using COPY FROM statement to perform this bulk loading. With this approach, we open a single transaction to encompass the entire CCLF ingest process for a given CCLF file. Once all beneficiaries have been inserted, we'll commit the transaction. This process is repeated for every CCLF file that needs to be ingested.
The transaction encompasses several statements. Each statement will be …
> BCDA-3429 - Use COPY FROM to bulk load CCLF beneficary data

- bcda/web/api.go
- bcda/web/api_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
During the job creation process, we can encounter situations that cause a particular job to get stuck in the `Pending` or `In Progress` state.
For example, a job is created that depends on 10 queuejobs. We update our Job details (in the DB) to expect 10 queuejobs to be complete. After updating the job, we successfully insert 9 queuejobs, but fail to insert the last queuejob. The created job would process 9 jobs and be stuck indefinitely in the `In Progress` state.
Because of this edge case, we need to ensure that jobs are only created once all of its dependent information is present. This includes having all of the queuejobs successfully added.
Since we're adding queuejobs prior to adding the actual parent job, we can encounter a situation where the queue worker fails to find its parent. …
> BCDA-3510 - Only create job iff all of its dependent information was populated

- Dockerfiles/Dockerfile.bdt
We are seeing failures on the FHIR scan related to issues with the CapabilityStatement response.
It turns out the bdt scan is checking for a field that is available only in FHIR r4. Since we are responding back using FHR r3, we were seeing this test failure.
Pin BDT version to an earlier revision that was validating CapabilityStatements against the FHIR r3 schema.
Since we're pinning the version of BDT, we've created a [follow up ticket](https://jira.cms.gov/browse/BCDA-3594) to un-pin the bdt version and resolve the test failures. It's assumed we'll start this work after we've moved over to FHIR r4.
Successful FHIR scan run
> BCDA-3509 - Pin bdt version to FHIR r3 compatible revision

- bcda/client/bluebutton.go
- bcda/web/api_test.go
- unit_test.sh
To improve developer efficiencies, we want to run our unit tests in parallel. We could not do this before due to 429 responses when submitting jobs.
1. Switch over api_test.go to use Small ACO. It was using Dev ACO, which can cause collisions with other tests.
2. Update our job update commands in bulkConcurrentRequestHelper to no longer assume that the latest created job was created by api_test.go. This assumption is no longer true since we're running tests in parallel.
3. Fix race found after running tests in a parallel.
1. Ran unit tests locally to ensure that they pass reliably.
2. CI Passes.
> BCDA-3398 - Support running unit tests in parallel

- unit_test.sh
Despite the extensive testing associated with #542, there still appears to be some race conditions in the unit test execution.
Updated the `unit_test.sh` script to ensure unit tests are being executed in sequence, to avoid race conditions.
After several failed pipeline builds in Jenkins this morning, this feature branch was built and fixed the broken pipeline. See [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/1800/).
Please review.  I've added a note to Brainstorming to explore additional options.
> Run unit tests in sequence.

- bcda/bcdacli/cli_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
- shared_files/synthetic1800MedicareFiles/test2/T#EFT.ON.ACO.NGD1800.DPRF.D181120.T1000010
- shared_files/synthetic1800MedicareFiles/test2/T#EFT.ON.ACO.NGD1800.DPRF.D190816.T0241391
- unit_test.sh
1. Remove global transaction from bcdaworker. Since multiple threads are calling processjobs, we need to ensure that we do not overwrite the transaction. This should remove some error logs we've seen on the worker logs.
```
{"file":"/go/src/github.com/CMSgov/bcda-app/bcdaworker/main.go:356","func":"main.fhirBundleToResourceNDJSON","level":"error","msg":"improper segment use: the Transaction must be used in a single goroutine and segments must be ended in \"last started first ended\" order: see https://github.com/newrelic/go-agent/blob/master/GUIDE.md#segments","time":"2020-09-02T11:56:46-04:00"}
```
2. Use different test data for cli_test#TestImportSuppressionDirectory. This ensures isolation from the suppression_test.go.
Ran tests locally and several times on dev to resolve race …
> BCDA-3145|3398 - Fixing more failures around test parallelization

- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
There were two definitions of JobEnqueueArgs, in bcda/models.go and bcdaworker/main.go. These definitions were equivalent.
Since we were using JSON serialization AND the field name/types are equivalent, we do not need to worry about any data migration from the old definitions.
1. Allow models.go JobEnqueueArgs definition to be exported and used in other packages (including bcdaworker).
2. Remove the struct definition from the bcdaworker code.
CI and unit tests are sufficient. Since the definition is not changed, we do not need to perform any data migration.
> BCDA-3589 - Consolidate JobEnqueueArgs definition

- test/performance_test/performance.go
Performance tests were silently failing with authentication issues. Need to update auth mechanism and have failures to notify developers when issues arise with the test process.
1. Update CLI to accept clientID and clientSecret. These are used to retrieve a token.
1. Ran positive test with successful requests being made to BCDA backend.
2. Ran negative test to verify performance test fails when it receives non 2xx response codes.
> BCDA-3551 - Update performance tests commands to use clientID/clientSecret

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/models/service.go
- bcda/models/service_test.go
Need to add support to onboard NGACOs (CMS_ID: VXXX) and CEC ACOs (CMS_ID:EXXXX).
Since we're using ACO_ID (UUID generated when an ACO is created in our system) for the majority of our lookups, only minimal changes are needed to add support for these new ACOs.
**NOTE:** This PR **does not** add support for the CCLF files associated with NGACO and CEC ACOs. That work will be completed in later PR.
1. Add IsSupportedACO method that contains the expected patterns for CEC, NGACO, and SSP ACOs.
2. Consolidate all ACO format checks to utilize the new method. This was only needed in the bcda-cli.
CI Passes
1. Double check that we only need to make changes to the bcda CLI.
2. Review PR.
> BCDA-3685 - Add registration support for NGACO/CEC ACO type

- bcda/bcdacli/cli_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcdaworker/main_test.go
When ingesting CCLF files associated with CEC ACOs, we encountered a duplicate file name error in our Postgres instance. Since the CEC files do not contain their CMS_ID in the name, we need to expand our unique constraint to include file name (name) and CMS ID (aco_cms_id)
This does not affect SSP ACOs (or NGACOs) since they already contain CMS ID in the file name.
1. Update our models#InitializeGormModels function to remove the old constraint (on file name only) and add new constraint for fileName + cmsID.
2. Fixing tests that violated the unique constraint. Before this PR, our test db **did not** include the file name constraint. Since we're explicitly adding the unique index in our initialization set, we need to clean up/use unique names.
1. CI Tests pass.
2. Run migration on lower …
> BCDA-3765 - Add aco_cms_id to cclf_file schema constraint

- Makefile
- test/smoke_test/bulk_data_requests_lite.sh
- test/smoke_test/smoke_test.sh
1. Add requests for CEC ACO (`E9996`) and NGACO (`V996`) for our smoke tests.
2. Introduced a lighter version of our requests (`bulk_data_requests_lite.sh`) for usage in the new ACO types.
CI passes
> BCDA-3692 - Add CEC/NGACO requests to smoke test

- Makefile
- ops/swagger_to_openapi.sh
We recently encountered an [issue](https://github.com/CMSgov/bcda-static-site/issues/79) where the OpenAPI schema was not generated properly.  We should fail the build/package if the OpenAPI schema is invalid.
- Added a simple validation step to ensure OpenAPI schema was generated correctly at build time
Performed a negative test locally, and the build was halted.
Please review.
> BCDA-3739: Validate OpenAPI Schema Generation 

- bcda/auth/alpha.go
- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/okta.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/testUtils/utils.go
We want to add the ability to associate a set of IP addresses when registering a new system.
Right now, this IP association is only valid for SSAS auth providers.
1. Update our Provider#RegisterSystem method to accept a list of IP address. Using a variadic input for IPs to allow users to exclude the IP arguments when calling RegisterSystem.
The following snippets are all valid:
```
cred, err := RegisterSystem("id", "key", "groupID")
cred, err := RegisterSystem("id", "key", "groupID", "1.2.3.4", "5.6.7.8")
cred, err := RegisterSystem("id", "key", "groupID", []string{"10.11.12.13"}...)
```
2. Update our cli command for generating system credentials to accept list of IP addresses.
1. Added test cases to verify that we're passing the IP address argument correctly when making the associated …
> BCDA-3681 - Add IP option when registering system

- bcda/cclf/cclf.go
- bcda/cclf/cclf_test.go
- bcda/cclf/fileprocessor.go
- bcda/cclf/fileprocessor_test.go
Runout files have a slightly different format versus regular CCLF files. For the ZIP file, we can expect `ZCR` instead of `ZCY`. For individual CCLF files, we can expect `ZC0R,ZC8R` instead of `ZC0Y,ZC8Y`
1. Update regex found in fileprocessor.go to support the new expectations from runout files.
2. Update our metadata to include filetype. If we have `R`, we assume runout. If we have `Y`, we assume a regular CCLF file.
With this change, we will be able to ingest runout CCLF files. The data stored will be exactly the same as regular CCLF files.
CI passes - new tests written to validate that we can process runout files as expected.
> BCDA-3720 - Update CCLF ingest to support runout files

- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
Log Accept-Encoding header value when logging request parameters. This will allow us to track the adoption of gzip-encoded file requests.
1. Update our StructuredLogger to emit the value of "Accept-Encoding" hdaer.
1. Adding tests to verify that the header is logged as expected.
2. Deploy to dev to verify Splunk metrics are updated as expected.
> BCCDA-3751 - Log "Accept-Encoding" header to gzip adoption

- bcda/api/requests.go
- bcda/api/requests_test.go
User had specified a query parameter that started with the `?` character, which caused the specified `_since` parameter to not be used.
Ex:
```
https://api.bcda.cms.gov/api/v1/Patient/$export?_type=ExplanationOfBenefit&?_since=2020-09-13T08:00:00.000-05:00
```
Considered using a whitelist of approved query parameters (`_since`, `_type`, etc.), but that seems to go against [experimental query parameters](https://hl7.org/fhir/uv/bulkdata/export/index.html#experimental-query-parameters) defined in the bulk FHIR spec..
1. Update ValidateRequest to check that no query parameters start with `?`
CI Passes
> BCDA-3753 - Detect repetition of query param charcter (?) in request

- bcda/api/requests.go
- bcda/api/v1/api_test.go
**tl:dr; We've been incorrectly returning errors when parsing _since parameters with a positive timezone offset**
With this [PR](https://github.com/CMSgov/bcda-app/pull/568) we pushed our validation of the `_since` parameter to occur in both patient and /group/all endpoints. It used to only occur on the /group/all endpoint.
After we merged the PR, we started to see failures in the FHIR scan. It was traced to this section of code:
```
decodedSince, _ := url.QueryUnescape(params[0])			
since, err = time.Parse(time.RFC3339Nano, decodedSince)
```
By using `url.QueryUnescape(...)`, we were incorrectly removing the `+` character from our timezone information.
Example:
```
t := '2020-09-26T15:05:31+04:00'
tNegative := '2020-09-26T15:05:31-04:00'
t1, _ := url.QueryUnescape(t) // t1 = …
```
> Fix issue with parsing _since parameter 

- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/api/v1/api.go
- bcda/api/v1/api_test.go
- bcda/api/v2/api.go
- bcda/api/v2/api_test.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/health/health.go
- bcda/models/models.go
- bcda/models/service.go
- bcda/models/service_test.go
- bcdaworker/main.go
- bcdaworker/main_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
We need to have a mechanism where callers can retrieve data from BFD v1 endpoints (STU3) and v2 endpoints (R4).
1. Update our JobEnqueueArgs to accept a basePath parameter. This parameter will be used to allow our worker to make v1/v2 BFD calls.
2. Update v1/v2 APIs to contain a list of supported resourceTypes. This information is passed into requests.go.
3. Update requests.go to contain a handler struct to capture resourceTypes and basePath parameters. v1 and v2 API will instantiate the handler with the expected parameters.
4. Refactor validation tests into request_test.go (from v1/api_test.go)
This PR **does not** call BFD v2 endpoints since they are not yet available. We will have follow up PR that switches the basePath. As such, no new data is stored/transmitted.
CI passes
> BCDA-3582 - Update BCDA to support querying v1/v2 BFD endpoints

- bcda/api/v2/api.go
- bcda/api/v2/api_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
- test/smoke_test/bcda_client.go
- test/smoke_test/bulk_data_requests.sh
BFD just released the v2 patient resource. This PR enables our v2 endpoints to leverage it. We had anticipated that Coverage would also be available. It is not. We will create a follow up PR to enable it.
This is a follow up on the [PR](https://github.com/CMSgov/bcda-app/pull/570) which set up the framework to allow us to send v1 and v2 BFD requests.
1. Change over the request path for BFD v2 endpoints to actually use v2.  It was set to v1 because Patient EP was not available.
2. Update our smoke test client to accept API version.
3. Update smoke test client to emit response code and body in case of an error. This helps better troubleshoot failures.
This will be the first opportunity for users to retrieve FHIR r4 data.
1. Added two additional smoke tests that request our v2 endpoints.
2. …
> BCDA-3582 - Enable BFD v2 patient endpoint

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
If we have the v2 endpoints disabled, we should expect to see a 404 not found error.
Introduce new global variable `v2Disabled` that will alter the expected response code.
Decided to introduce a new variable instead of leveraging the env variable. bcda-api is not aware of what environments have v2 enabled or disabled. By introducing a new variable, we can keep that information at the ops/deployment side.
1. Ran [smoke test in prod environment](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2545/) and verified postman tests pass with the expectation of the 404 error.
2. Ran [smoke tests in dev environment](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2546/) and verified postman tests pass with the expectation of the 400 error.
> BCDA-3582 - expect a 404 error if v2 endpoints are disabled

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/testUtils/client.go
- bcda/testUtils/utils.go
- bcdaworker/main.go
- bcdaworker/main_test.go
Updates bcdaworker to use the serviceDate filter when querying from BFD.
1. Update bcdaworker and bb client to use the JobEnqueueArgs#ServiceDate parameter. When the field is set, we will query BFD with `service-date=le<SERVICE_DATE>`. See [RFC](https://github.com/CMSgov/beneficiary-fhir-data/blob/master/rfcs/0007-service-date-filter.md) for more details.
2. Consolidate bcda worker test setup into SetupSuite()/SetupTest()
This PR will leverage service-date query parameter.
[Security checklist](https://confluence.cms.gov/display/BCDA/20-10-16%3A+Service+Date+Filter+Implementation+Security+Checklist) for service-date filter implementation.
1. CI Passes. Added unit tests to verify the service date parameter is passed in as expected.
We have a follow up …
> BCDA-3722 - Update bcdaworker to leverage ServiceDate parameter

- bcdaworker/main.go
- bcdaworker/main_test.go
All jobs should have a `BBBasePath` set and should not need to fall back to to the `/v1/fhir/` default anymore.
Remove fallback code for basepath and add error checking.
Removed the `basePath` fallback check. Added a separate test to check for that an error is raised if no `BBBasePath` arg is provided.
Tested via unittests.
Let me know if this an ideal way to build and return an error!
> bcda-3895 Feature: Remove bfd v1 fhir fallback basepath for job args

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/client/fhir/client.go
- bcda/client/fhir/client_test.go
We encountered the following race condition:
```
=== FAIL: bcda/api/v1 TestAPITestSuite/TestBulkConcurrentRequestTime (2.54s)
==================
WARNING: DATA RACE
Write at 0x00c000360a80 by goroutine 36:
github.com/CMSgov/bcda-app/bcda/client/fhir.(*singleClient).DoBundleRequest()
/go/src/github.com/CMSgov/bcda-app/bcda/client/fhir/client.go:45 +0xfe
github.com/CMSgov/bcda-app/bcda/client.(*BlueButtonClient).tryBundleRequest.func1()
/go/src/github.com/CMSgov/bcda-app/bcda/client/bluebutton.go:231 +0xa7
github.com/CMSgov/bcda-app/vendor/github.com/cenkalti/backoff.RetryNotifyWithTimer()
/go/src/github.com/CMSgov/bcda-app/vendor/github.com/cenkalti/backoff/retry.go:52 +0x2db
github.com/CMSgov/bcda-app/vendor/github.com/cenkalti/backoff.RetryNotify() …
```
> BCDA-3970 - Fix race condition uncovered in bluebutton.go

- bcda/api/requests.go
- bcda/models/service.go
- bcda/models/service_test.go
1. Use an environment variable to define runout claim thru date, defaulted to 2020-12-31. 
We used to compute the claim thru date to lock it to the end of the **previous** year. This would mean that we would have to restart our API instances on 2021-01-1 to have the service date set to 2020-12-31. If we forgot to do this operation, we would have the service date set to 2019-12-31.
2. Use a default runout cutoff time of 120 days. This value was misconfigured (set to 45 days).
CI Passes
> Fix runout claim thru/cutoff dates

- bcdaworker/main.go
- bcdaworker/main_test.go
Errors that are written to the `errors.ndjson` either use the BB id or the beneficiary id. Neither of these are useful to us and the error should be updated to use another id that can be helpful.
- Update error message to use the MBI identifier instead.
- Error message was updated to use MBI id.
- `handleBBError` func was moved entirely as it wasn't necessary for the couple times it was called. The logic was moved into the top level function where the `errorCount` lives (and we dont have to to pass a pointer around anymore).
- `beneBBID` was renamed to `getBeneficiary` since it now returns the entire beneficiary instead of just the BB id.
- Top level code was updated to use a closure method that passes back the err and error message that will be written to the file.
Unittests have been …
> bcda-3838 Feature: Update errors to use MBI id

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
Bulk headers do not match those listed in [https://github.com/CMSgov/beneficiary-fhir-data/blob/master/docs/request-audit-headers.md](https://github.com/CMSgov/beneficiary-fhir-data/blob/master/docs/request-audit-headers.md)
- Update our bulk request headers to match listed [BFD Audit Headers](https://github.com/CMSgov/beneficiary-fhir-data/blob/master/docs/request-audit-headers.md)
- Update associated tests and logs to utilize new headers
`BCDA-JOBID`  should now be `BULK-JOBID`
`BCDA-CMSID` should now be `BULK-CLIENTID`
See: [https://github.com/CMSgov/beneficiary-fhir-data/pull/386](https://github.com/CMSgov/beneficiary-fhir-data/pull/386)
-  [x] no PHI/PII is affected by this change
Unit tests have been updated to check for the correct headers
> BCDA-4019 - Update Bulk Request Header Names

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
We encountered an issue when attempting to copy the CCLF files for NGACOs. The regex for the NGACO file names did not match the expectations.
To resolve this, we relaxed the regex requirements.
1. Relax the regex requirements for renaming the CCLF files.
2. Adding tests with NGACO/CEC files to verify the rename works as expected.
1. Added unit tests to verify CEC/NGACO files would be renamed.
2. Verified fix by running the updated CLI on our NGACO files. They were renamed correctly.
> Relax regex requirements to handle CEC/NGACOs

- bcda/cclf/fileprocessor_test.go
When the `TestMultipleFileTypes` unit test was added to `bcda/cclf/fileprocessor_test.go`, it was intentionally isolated from the `FileProcessorTestSuite`.   By excluding this test from the `FileProcessorTestSuite`, we are unable to take advantage of the pre-processing done as part of the test setup.  One of the items included in the test setup is the setting of `CCLF_REF_DATE`, to ensure that we can use CCLF files with static dates in the filename (if we do not set this value, then our unit tests fail because the `CCLF_MAX_AGE` is surpassed).  With the current test implementation, the `TestMultipleFileTypes` test fails 45 days after the test was written (with the defined static timestamp in the CCLF filename).  The failure Is:
```
date 'D201113.T000001' from file …
```
> Update file ingestion test to use a static CCLF_REF_DATE

- bcda/cclf/fileprocessor_test.go
We were hard coding the performance year for certain CCLF file tests to 20 (for 2020). These tests are failing when we roll up to the new year.
1. Compute the perfYear in the `TestGetCCLFMetadata` test to avoid this issue moving forward.
CI passes.
> Fix issue with perf year advancing

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
Adds a header to the Explanation of Benefits requests to take advantage of the new optional flag on BlueButton to provide the tax numbers for the claim.
Add IncludeTaxNumbers: True header to the GetExplanationOfBenefits function in bluebutton.go
Create variable with default header, add additional header, and include the header in bluebutton getBundleData
Local unit tests passing.
Missing stuff, Best Practices, Better Ideas
> BCDA-4017 Feature: Add IncludeTaxNumbers: True header to EOB requests

- Dockerfiles/Dockerfile.ssas
Clone the bcda-ssas-app repository instead of running `go get github.com/CMSgov/bcda-ssas-app`. With the migration to go modules, we do not have a guaranteed path which we'll find the bcda-ssas-app binaries. By cloning the repository and running `go install`, we can determine where we need to set the `WORKINGDIR` in order for the config parameters to be resolved correctly.
We tried a couple other solutions, but ran into other snags.
1. https://github.com/golang/go/issues/40276
```
(cd $(mktemp -d); GO111MODULE=on go get github.com/CMSgov/bcda-ssas-app)
```
Allowed us to download and install the ssas-app binary, but we were not able to determine where the module was downloaded to. We felt like it would be easier/clearer to download the repository instead.
2. We tried adding it to the …
> Fix Dockerfile.ssas to account for go module migration.

- bcda/api/v1/api.go
- bcda/api/v1/api_test.go
- bcda/models/models.go
We are enabling the capabilities for a consumer to cancel a group export request. Since this request is sequestered off to a job queue we mark the job as being in a cancelled state. We need to convey this to the consumer if a status is requested. The return should be a `404` and have an operational outcome json payload as per the fhir spec.
Add a cancelled state check to the case statement in the `api.go` job status endpoint method.
- Updated the models.go job constant to include a `Cancelled` state
- Updated the `api.go` case statement to handle the job cancelled state and return a `404` with an operational outcome. 
ACO-API now returns a correct response code for cancelled jobs.
Couple things:
- I ended up not having to update the swagger since theres already a `404` response coming …
> bcda-3663 Feature: Job status endpoint handles cancelled jobs

- .vscode/settings.json
Update settings.json for VScode to not fire off warning for two function calls in the conf package.
Adding a setting into vscode to ignore warnings generated for not handling errors for conf.SetEnv and conf.UnsetEnv. Future update to application will remove/replace making these calls.
VScode ignores warnings related to conf.SetEnv and conf.UnsetEnv.
Make sure the setting.json looks sound.
> VSCode Settings Update

- db/migrations/bcda/000007_remove_deleted_at_columns.down.sql
- db/migrations/bcda/000007_remove_deleted_at_columns.up.sql
- db/migrations/migrations_test.go
With our move from GORM to sql builder we lost access to some automatic GORM functionality that created and updated bookkeeping columns in our tables. `deleted_at` is one of those columns.
Create a migration that removes the `deleted_at` column from all the tables that contain it since we do not use this data for anything.
- Migration up removes `deleted_at` column.
- Migration down adds `deleted_at` column.
- Unit tests verify migrations
Migration removes `deleted_at` column.
The migration was applied manually to the unit test database and the unit tests run to assure the migration wont affect the unit tests in the future.
[jenkins smoke test](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2908/) ran successfully after applying the …
> bcda-4135 Feature: remove deleted at columns from db

- Dockerfiles/Dockerfile.documentation
When running `make docker-bootstrap`, we encountered the following error when building the documentation container:
```
Step 6/11 : RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger
---> Running in 4fe5388ba4e0
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
/usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```
Looking at go-swagger's [go.mod](https://github.com/go-swagger/go-swagger/blob/master/go.mod) file, it doesn't reference github.com/hashicorp/hcl/hcl/printer so it makes sense that this dependency is missing. We are still looking at the reason for this regression.
Using the [go-swagger installation guide](https://goswagger.io/install.html#installing-from-source), we …
> Change methodology for building the go-swagger binary

- db/migrations/bcda/000008_remove_cclf_bene_xref_table.down.sql
- db/migrations/bcda/000008_remove_cclf_bene_xref_table.up.sql
- db/migrations/migrations_test.go
The `cclf_beneficiary_xrefs` table is not being used in our db schema.
Drop `cclf_beneficiary_xrefs` table in a migration.
- Create up migration to remove xref table.
- Create down migration to readd xref table, the id sequence, and the indexes.
- 
We are dropping the xref table from our schema.
The migration was successfully applied to [dev](https://bcda-ci.adhocteam.us/job/BCDA%20-%20SQL%20Migrate/121/).
The Smoke tests [Passed](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2918/) after the migration.
Sister [PR](https://github.com/CMSgov/bcda-ops/pull/659) in bcda-ops.
I kept the unittest pretty basic (checking existence of the table). If anybody feels strongly about making the asserts more specific, please comment on what you'd like to see.
This migration …
> bcda-4134 Feature: remove cclf xref table

- Dockerfiles/Dockerfile.wait_for_it
- Makefile
- docker-compose.wait-for-it.yml
In this [PR](https://github.com/CMSgov/bcda-app/pull/635), we rebuild the database container and run the migration script to ensure that the database schema matches our expectations. To ensure that we start with a clean state, we teardown and rebuild the database container. We expect that this process does not take longer 5s.
However, our build were failing on the CI pipeline since the sleep time was not adequate. 
Use the strategy listed [here](https://github.com/vishnubob/wait-for-it/issues/57#issuecomment-497661237) to ensure that the unit-test-db container is started as expected
We are using this [project](https://github.com/vishnubob/wait-for-it) as recommended by [Docker team](https://docs.docker.com/compose/startup-order/) to ensure that our database instance works as expected.
1. …
> Use wait-for-it script to ensure unit test db is running

- Makefile
- bcda/cclf/fileprocessor.go
- bcda/cclf/fileprocessor_test.go
- bcda/cclf/testutils/cclfUtils.go
- bcda/cclf/testutils/cclfUtils_test.go
- bcda/models/service.go
- bcda/models/service_test.go
Update the api to allow for kcc (ckcc/kcf) and dc cclf models.
Update our models service to allow for the ckcc, kcf, and dc cms id types. Update the filename regex in `fileprocessor.go` to not only allow for the new file types but to tighten up our regexing in general and ONLY allow for the specific file types. Update our cclf synthetic file generation to create new dev files for ckcc, kcf, and dc models.
- Updated `models/service.go` to allow new kcc and dc models by adding the cms_id to regex.
- Updated `fileprocessor.go` regex to specifically check for our currently whitelisted aco types.
- Updated `cclfUtils.go` to generate synthetic data for the new aco types (kcc and dc).
- Updated makefile `load-synthetic-cclf-data` and add dev generation for kcc and dc models.
The API now accepts …
> bcda-4219 Feature: support kcc and dc models

- bcda/models/service.go
- bcda/models/service_test.go
When creating jobs, we need to account for the ACOs termination details (date + claims strategy). This should be applied to the service date field which caps claims data.
1. Apply termination#ClaimsDate() when creating que_jobs.
2. Let runout claims take precedence when computing the claims date cutoff. If the caller is terminated & is making a runout request, we'll  use the runout date instead of termination date. 
1. CI Passes - added tests to verify that we are applying the correct termination information.
> BCDA-4214 - Use claims data cutoff when creating jobs for terminated ACO

- bcda/models/alr.go
- db/migrations/bcda/000010_alr.down.sql
- db/migrations/bcda/000010_alr.up.sql
- db/migrations/migrations_test.go
We are getting ready to start consuming and serving up Assignment List Report (ALR) data to our customers. To do this, the initial step is to create a model and then make the necessary migrations to prep the database for ingestion.
1. Create ALR Model. We need to keep in mind that a typical ALR submission may have more rows than a typical CCLF submission. In addition, we are currently assuming that seven fields (out of possible hundreds) should be present in each ALR submssions.  The rest of the fields are possibly violate and we cannot guarantee they will be present in each submission.
2. Make the appropriate migration.
1. The ALR model will have two tables. One will house the meta data and will be shorter in terms of rows compared to the second. We will query the first table by ACOs and …
> BCDA 4237 Adding ALR Models

- Makefile
- docker-compose.yml
We have a series of `sleep` commands in our `Makefile`. We want to remove these and leverage a tool.
Take advantage of the `wait-for-it` docker container to wait on our `db`, `api`, and other containers we build.
- Update Makefile to integrate `wait-for-it`.
- Update `depends_on` in `docker-compose.yml` builds to have a correct dependency tree.
All sleeps in the makefile are removed and we are waiting for our services to start.
Jenkins build pass: https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/2235/
Scrutinize my make skills. Also, note that I didn't add `api` to the workers dependency due to a cyclical dependency error.
> bcda-4258 Feature: Integrate wait-for-it container in make

- bcda/cclf/metrics/metrics_test.go
- bcdaworker/worker/worker.go
- go.mod
- go.sum
golangci-lint started reporting errors about the deprecated newrelic library. We needed to change all imports from 
`github.com/newrelic/go-agent` to `github.com/newrelic/go-agent/v3`.
CI passes - we were utilizing the same underlying NewRelic version so we shouldn't see any regressions with the change of import paths.
> Remove references to deprecated newrelic library

- bcdaworker/worker/bluebutton.go
Handle changes made to the R4 Patient resource. Specifically:
1. The mbi field is now under `http://terminology.hl7.org/CodeSystem/v2-0203` instead of `http://hl7.org/fhir/sid/us-mbi`
2. bene_id (`https://bluebutton.cms.gov/resources/variables/bene_id`) is no longer listed as one of the identifiers.
BFD PR: https://github.com/CMSgov/beneficiary-fhir-data/pull/474
Update our bluebutton.go code to search for MBI in different location.
CI Passes
> Fix issue with MBI field in different location

- .vscode/settings.json
To enable local testing (in vscode), we need to update file/folder paths to reference the workspace folder.
Update settings.json to include env vars that need to reference the workspace path.
Verified that once this settings.json was updated, requests_test.go was able to be executed within vscode.
> Adding file path env vars to vscode config

- bcda/service/config.go
CIs were failing for all recent commits. 
Source of the bug: config_test.go: line 58.
When we enter a new month, the cutoff day may be higher than the current day. This leads to the condition to resolve to a false, and does not take off an additional year.
Additional logic added to conditional to fix issue.
CI Pass
Edits to control flow looks correct.
> BCDA-4382 Hotfix

- bcda/auth/provider.go
With this [PR](https://github.com/CMSgov/bcda-app/pull/684), we exited early if we could not set up the auth provider.
This caused issues with packages that import the auth package, but do not use it. It was causing errors in our NFS instances.
1. Switch init() block to use Errorf instead of Fatalf
1. Running deploy on dev environment and verify smoke tests pass
> BCDA-4372 - Switch from fatal to error logging

- .github/workflows/ci-workflow.yml
- codecov.yml
To add immediate signal on how well changes are covered, we want to add a tool report code coverage stats on pull requests.
Use [codecov's github actions](https://github.com/codecov/codecov-action) to publish code coverage stats.
We are using codecov's github actions to publish metrics
Code coverage metrics will be reported in PRs
Completed Checklist](https://confluence.cms.gov/display/BCDA/21+-+04+-+16%3A+Use+Codecov+in+BCDA+Code+Reviews+Security+Checklist?src=contextnavpagetreemode)
1. Verified coverage report meets the expectations of the team.
> BCDA-3486 - Add codecov action on pull requests

- docker-compose.test.yml
- docker-compose.yml
The current deployed major version of Postgres in AWS for ACO API is Postgres 10.  However, in the docker-compose stacks for bcda-app we are pulling from postgres:latest (see here for example).
We need to ensure all references to pulling Postgres images from Dockerhub in bcda-app align with the version of Postgres that we are using in AWS.  This should be `postgres:10` image in Dockerhub.
- Pin Postgres image version to 10
> BCDA 4452 Fix: Pin Postgres image version to 10

- go.mod
The newest version of https://github.com/xo/usql was causing build failures for our test package. This fix pins usql at the previous stable version 0.8.2.
Add replace directive in `go.mod` to pin correct version of usql
Builds successfully locally
> Hotfix: Pin usql to version 0.8.2

- db/migrations/manual/20210512-gpdc-import-status-completed.sql
- db/migrations/manual/20210512-gpdc-import-status-ignore-manual.sql
GPDC models are currently authorized to make credentials for BCDA access, but are not authorized to receive data. In response to [this incident](https://confluence.cms.gov/display/BCDA/20210510+-+BCDA+GPDC+model+making+a+call), we are adding a migration script to track database changes made to prevent GPDC models from receiving data prior to when they should be.
These migration scripts are for tracking purposes only. When GPDC models are authorized to receive data, the `gpdc-import-status-completed` script may be run to enable the model's access.
**Note:** monthly CCLF ingestion will overwrite the updated `import_status` column; if needed, re-run this script to ensure `import_status` remains set to `Ignore_Manual` for GPDC models.
General improvements and/or missing info
> BCDA-4512: Add migration scripts for updating import_status column

- bcda/bcdacli/cli.go
- bcda/insights/insights.go
- bcda/insights/insights_test.go
We have built a capability for BFD Insights to acquire BCDA metrics by using a lambda to periodically poll our Read Replica database, extract the necessary metrics, and push them to BFD Insights.  However, there exists the need to send real-time events to BFD Insights via the BCDA application itself.  This PR adds a utility to allow the BCDA application to send real-time events to BFD.
These changes were implemented and tested in conjunction with the infrastructure changes outlined in [this PR](https://github.com/CMSgov/bcda-ops/pull/740).
- Added a utility function (`PutEvent`) which can be used to send a real-time event to BFD Insights (as long as the `BCDA_ENABLE_INSIGHTS_EVENTS` feature flag is enabled).
- Added proper unit test coverage for the new utility function.
Note: [a …
> BCDA-4532: Enable Application Code to Send Events to BFD Insights

- Dockerfiles/Dockerfile.documentation
- bcda/api/alr_test.go
- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/api/v1/api.go
- bcda/api/v2/api.go
- bcda/api/v2/api_test.go
- bcda/models/SwaggerStructs.go
- bcda/web/router.go
- bcda/web/router_test.go
- test/smoke_test/bcda_client.go
We use the `jobs/{jobID}` endpoint in v1 to allow GET requests to check the status of a job, and DELETE requests to cancel an in-progress or pending job. This ticket makes the endpoints available in v2.
- Move `JobStatus` and `DeleteJob` methods out of `api/v1/api.go` and into `api/requests.go`; this allows each method to be version-agnostic and easily accessible for both v1 and v2.
Unit, smoke, and postman tests passing locally
Confirmed `/jobs/...` endpoint was available locally with v2 enabled, via Swagger
- I had to increase the `httpRetry` flag in `bcda_client.go` from 3 to 4 in order for smoke tests to pass; any concerns with that change?
- Any additional test coverage needed
- General improvements or suggestions
> BCDA-4515: Implement jobs endpoints for v2

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
Currently, if our cclf and 1800 medicare ingestions process gets a termination signal from AWS it will stop immediately. Since we attempt to ingest on an hourly basis we would like these ingestions to get a chance to finish.
Add signal handling to both ingestion cli process commands that ignores the termination signals.
Note that AWS will send a power down request to its ec2 instances when trying to shut them down. This results in the instance giving a `SIGTERM` to its running processes to kill them gracefully. If the instance takes to long shutting down, AWS will then send a `SIGKILL` signal instead to force it to shutdown immediately. That wait time depends on how our ops team has set that up... though by default the wait time should be more than long enough for our ingestions to …
> bcda-4565 Feature: Signal handling for cli tools

- docker-compose.yml
The ACO API environment is currently running on Postgres 10.  To ensure we don't get too far behind, we should upgrade to Postgres 11.  
The system/infrastructure (i.e., RDS) will be updated in separate implementations in `bcda-ops`.  However, to ensure the local development environment functions with Postgres 11, the Docker Compose stack configuration should be updated.
Updated the Docker Compose stack configuration to ensure the local development environment (and CI) used Postgres 11.
Because the Docker Compose configuration is the only thing affected as part of this PR, a successful execution of the CI steps in Github Actions is sufficient acceptance.
Please review.
> BCDA-4477: Update to Postgres 11

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
- test/smoke_test/bulk_data_requests.sh
Since we are almost ready to roll out v2 endpoints in production we want to make sure our test coverage is substantial enough for those endpoints in all our testing infrastructures.
- Update postman tests to include more v2 testing
- Update smoke tests to include more v2 testing
- Update unit tests to include  more v2 testing
- Added more v2 export calls to postman including tests for all endpoints that fail due to not having provided a token and creating and deleting a job. The test order has also been slightly restructured so that the postman tests runner will kick off ALL export jobs (v1 and v2) before starting to consume them by checking the job statuses. Im not sure if this will affect performance at all but theoretically the postman runner wont have to query job statuses as long if …
> bcda-4516 Feature: implement testing for v2

- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/api/v1/api.go
- bcda/auth/api_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/ssas_middleware_test.go
- bcda/responseutils/v2/writer.go
- bcda/responseutils/v2/writer_test.go
- bcda/responseutils/writer.go
- bcda/responseutils/writer_test.go
- bcda/web/middleware/middleware.go
- bcda/web/middleware/middleware_test.go
- bcda/web/middleware/ratelimit.go
- bcda/web/middleware/validation.go
- bcda/web/router.go
- bcda/web/router_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
Currently, the API uses fhir `stu3` as its response type for both `v1` and `v2` of our API. However, since BFD has moved its response for their `v2` to fhir `R4` we want to do the same for when we create Error Responses.
Identify when requests are being made via `v1` or v2` and use the correct response writer. Create a new writer for `v2` that integrates with the `R4` fhir spec and builds the responses appropriately.
- Create `v2` writer.go in `responseutils` that creates responses using the correct fhir library.
- Move the creating of error responses to both `v1` and `v2` writer files and, therefore, removing fhir library access away from the `requests.go` file.
- Create and interface in requests.go that will satisfy the responsewriter methods we are using.
- Update and add testing where …
> bcda-4649 Feature: API v2 response r4 compatible

- Makefile
- test/smoke_test/bulk_data_requests.sh
- test/smoke_test/bulk_data_requests_lite.sh
- test/smoke_test/smoke_test.sh
As an effort to speed up the testing and release process, it has been suggested to parallelize the smoke test. This ticket aims to parallelize a number of calls made by bcda_client.go. This ticket also explored parallelizing the integration smoke-test in jenkins.
Bash / sh has the feature to send a task into a separate child process through "&". We can add this to the end of commands we want to parallelize. We need to ensure however that we collect the PID of that child process and wait for it specifically (e.g. wait \<PID\> not just wait). By doing this, we make sure if any of the child processes fail, the parent process will exit with a code other than 0.
We implemented the proposed changes mentioned above to the following files:
1. bulk_data_requests.sh 
2. bulk_data_requests_lite.sh …
> BCDA-3607 Parallelized Smoke Test and Fix Bulk Lite

- Makefile
- ops/build_and_package.sh
Build and Package was failing during the deployment process because of two things:
1. The wait-for-it timer, which is used to wait for the DB to become available before moving to the next make process, was too short and erroring out during unit-test
2. Crosswalk.tsv is a required file, but the file was moved during a refactor.
Up the wait-for-it timer to 75 seconds, and updated the path of the crosswalk.
Updates to build_and_package.sh and Makefile is correct.
> BCDA-4695: Fixing build and package fail issue due to crosswalk.tsv move

- ops/build_and_package.sh
This is a followup to PR: https://github.com/CMSgov/bcda-app/pull/723
There were additional location to update path to crosswalk in build_and_package.sh.
Update the remaining paths to the crosswalk in build_and_package.
Updates to build_and_package.sh is correct.
> BCDA-4695: Fixing the remaining reference to crosswalk.

- README.md
The CI status badge on the repo's `README` is referencing the deprecated Travis CI status.  It should be replaced to show the CI Workflow from Github Actions.
- Replaced the Build Status badge to reflect the CI Workflow from Github Actions
New Status Badge shows the status of the CI Workflow from `master` branch:
Please review.
> Add CI Status Badge to README

- tools.go
Due to a recent change in delve we are encountering build failures.
Comment out the delve import in our `tools.go` file to avoid installing the package within our dockerfile(s). Once we upgrade our go compiler this change can be reverted.
- Comment out delve package in `tools.go`
CI once again builds.
> Comment out delve from tools file

- bcda/database/config.go
- bcda/service/config.go
When we added a new feature to better track and manage our environment variables (EV) into a single location, we had logs be created when the EV were successfully load. We are currently logging data that is better kept off.
This is short PR to remove code that is responsible for logging configuration data.
Two files are affect:
1. config.go in database
2. config.go in service
Codes mentioned above have been removed.
All unnecessary data logged previous no longer occurs, and CI passes.
> Removed printing config into log for service and db

- Makefile
The time it takes to initialize the unit test DB container has increased, largely due to the heavy parallelization occurring during CI in Jenkins.  This results in flaky CI, causing unit tests to fail sporadically.
- Increased the unit test DB init to 120 seconds
Successful execution in Jenkins occurred [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/2697/).
Please review.
> Increase timeout for initializing unit test DB container

- bcda/api/alr.go
- bcda/api/alr_test.go
- bcda/api/requests.go
- bcda/api/v1/api.go
- bcda/api/v2/api.go
- bcda/web/router.go
- bcda/web/router_test.go
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
Adds dedicated endpoint for ALR requests.
- Create ALR endpoints for Patient and Group requests
- https://bcda.cms.gov/api/v#/alr/Patient/$export
- https://bcda.cms.gov/api/v#/alr/Group/{groupId}/$export
- Add endpoints to `router.go`
- Update handler functions to no longer rely on `isALRRequest()`
- Update tests to reflect these changes
- Confirm that all tests pass
- Existing functionality is not affected
- Requests against the new endpoint are successful and data returned matches existing functionality
> BCDA-4646 Feature/ALR Endpoint

- Makefile
The `wait-for-it` timeout in our Makefile for bringing up our services in containers has been increased in the recent past to `75 seconds`. However, there have still been a few instances of the boot process timing out due to not allowing enough time for the container to start up.
- Increase the `wait-for-it` timeout to 100 seconds for the databases, the api, and the ssas api.
Continue to observe the deployment and running of our smoke tests (that use our docker containers) and see if further timeouts appear.
General feedback always appreciated.
> bcda-4723 Feature: Increase wait-for-it timeout

- ops/Jenkinsfile.build_trigger
BCDA currently uses SSH Keys to integrate with Github from Jenkins, which relies on the SSH key to be stored on the Jenkins volume.  To simplify the migration to the new contract, the strategy will be updated to use Personal Access Tokens to integrate with Github (which is identical to the strategy being used on the DPC project).  
This should be considered an enhancement, as the tokens will be stored in Jenkins Credential Management System as opposed to a nebulous location on the Jenkins volume.
We should migrate to use Personal Access Tokens to integrate with Github from Jenkins.
- Added a new Personal Access Token to the BCDA Jenkins Credential Management System
- Updated the Checkout Strategies for all relevant Jenkins jobs to ensure that it is using the new credential
> Access is …
> BCDA-3047: Use Github PAT over HTTPS instead of SSH Key

- bcda/api/v1/api.go
- bcda/api/v2/api.go
Our Swagger documentation for ALR doesn't specify supported resource types, just whether they are FHIR R4 or STU3. 
Include supported resource types that are returned by the v1 and v2 ALR endpoints
Language updated on both v1 and v2 Swagger pages:
_"Initiates a job to collect Assignment List Report data for your ACO. Supported resource types are Patient, Coverage, Group, Risk Assessment, Observation, and Covid Episode."_
Is there any other supporting language we'd want to add for these ALR endpoints?
> BCDA-4801: Update ALR Swagger Text

- test/smoke_test/bcda_client.go
Due to longer run times in our upper environments for smoke tests we have been running into the retry logic for our tests. This has resulted in errors due to the `response` not being set.
Check if `resp` is set before and fall back to the default retry policy.
Smoke tests pass on dev
Let me know if I missed something
> Add nil check for resp in retry functionality for smoke tests

- db/migrations/manual/20211229-runout-undo.sql
- db/migrations/manual/20211229-runout.sql
We currently do not have runout files within the 180 day window to serve to ACOs. If we ran the terraform implementation without any additional work with data, we not serve any data to your stakeholders until JAN/FEB next year when the new runouts will be available.
To prevent no data being served, we would like to temporarily convert the DEC CCLF files into runout by changing those from 0 to 1 for the type field.  This will enable ACOs to continue to receive data based on their DEC attribution data.
We add two manual DB wrangle to handle this issue. One for changing DEC CCLF to runouts, and another to undo it when new runout files become available.
Ensure the two sql scripts are correctly written. Try running it locally and make sure it works.
Yes!
> BCDA- 5161 Adding manual DB wrangle for runout 2021

- Dockerfiles/Dockerfile.documentation
The latest tagged version of `go-swagger` relies on some Go 1.16 features.  This [new version](https://github.com/go-swagger/go-swagger/releases/tag/v0.29.0) was released on 1/23/22. 
When attempting to use it, [errors occur](https://bcda-ci.adhocteam.us/blue/organizations/jenkins/SSAS%20-%20Build%20and%20Package/detail/SSAS%20-%20Build%20and%20Package/1911/pipeline).
Pin to `go-swagger` v0.28.0
- Pinned to `go-swagger` v0.28.0
- A [ticket exists](https://jira.cms.gov/browse/BCDA-5010) for upgrading Go
The full Build/Package/Deploy process is passing.  See [here](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Build%20and%20Package/2984/).
Please review.
> Pin Go-Swagger to v0.28.0

- .github/workflows/ci-workflow.yml
- bcda/api/v1/api.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/models/repository.go
- bcda/web/router.go
- bcda/web/router_test.go
- starts a pattern for adding fields to the contextual log (the log associated with the request).
- using middleware to decorate functions with additional request level logging.
Using the structured contextual logging provided by the chi middleware
None: adding only one non-pii/phi field to logging.
None
> Log the resource type associated with a download job

- Makefile
Before this running `make unit-test` on it's own would fail due to a missing external dependency. This is used by Jenkins.
Include local `ssas` as a dependency of the `unit-test` make command.
> Updates to allow `make unit-test` to pass

- scripts/unit_test.sh
Before this test coverage would not be counted for called functions from
dependencies (sub directories)
Updated test call to check for how tests cover other packages when running
Locally this upped coverage from 70% to 78%
> Correct test coverage for all packages

- db/migrations/manual/20221222-partially-adj-synthea-rel1-runout-update.sql
Runout queries are not working for PACA test accounts in sandbox environment.  The problem appears to be caused by the type and timestamp parameter values in the runout file records.  This PR includes a manual migration that would need to be executed in the sandbox database to change these values.
Adds manual migration file to update `type` and `timestamp` in PACA runout `cclf_files` records.
Adds manual migration file to update `type` and `timestamp` in PACA runout `cclf_files` records.
Is this change correct for its intended purpose?
> PACA-875: Manual migration to partially adjudicated runout file records.

- Dockerfiles/Dockerfile.tests
- Switch to an Alpine docker image from a Debian base (to be consistent with the rest of BCDA go containers)
- Execute an update on existing apks on base image
- Package dependencies added to Dockerfile to support build and test execution
Successful build and execution of test container on lower environments. Also verify that Snyk findings reported has been reduced.
> BCDA-6627 Update base docker image used for test container

- bcda/auth/api_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
- bcda/auth/mock_provider.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- bcda/errors/errors.go
- bcda/web/router_test.go
https://jira.cms.gov/browse/BCDA-4456
- Rely on ParseToken for token parsing and validation, if it is provided
- Remove validation logic from `RequireTokenAuth` (only check if token has been pre-validated and stored in the request context)
- Instead of deleting the `AuthorizeAccess` method...
- Merge validation logic from `ParseToken` to `AuthorizeAccess` and clean up unreachable code
i.e. flow before and after for authorized endpoints:
```
--> ParseToken (validation logic) 
--> RequireTokenAuth (confirm token exists) 
--> calls AuthorizeAccess (validation logic)
--> ParseToken
--> calls AuthorizeAccess (validation logic)
--> RequireTokenAuth (confirm token exists)
```
---
Currently, token middleware is handled through two functions (ParseToken and RequireTokenAuth).
- Unauthenticated …
> BCDA-4456: Remove duplicate calls to SSAS /introspect endpoint

- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
https://jira.cms.gov/browse/BCDA-7081
- Increase test timeout for EOB runout export jobs from 50 seconds --> 100 seconds
During prod deployment, we ran into two back-to-back failures for the same job. As part of export job testing, we wait up to 50 seconds for the job to complete. However, it appears the EOB prod jobs are taking longer to run than before:
```
...
✓  X-Progress header is Pending or In Progress
┌
│ 'ExplanationOfBenefit export still in progress. Retryi
│ ng...'
└
...
✓  X-Progress header is Pending or In Progress
┌
│ 'ExplanationOfBenefit export still in progress. Retryi
│ ng...'
└
...
✓  X-Progress header is Pending or In Progress
┌
│ 'ExplanationOfBenefit export still in progress. Retryi
│ ng...'
└
...
✓  X-Progress header is Pending or In Progress
┌
│ 'Retry limit …
```
> BCDA-7081: Increase test timeout for EOB runout export tests

- db/migrations/manual/20230601-paca-synthetics-runout.sql
https://jira.cms.gov/browse/BCDA-6873
Added manual migration for the smoke test ACO to include a runout file.
Runout cclf file is required for some of the test cases to run successfully.
Applied migration to opensbx and ran smoke tests successfully.
> BCDA-6873 PACA smoke test manual migration

- bcda/nrpgx/nrpgx_test.go
https://jira.cms.gov/browse/BCDA-6873
Updated the test IP addresses so that they are non-sensitive/non-routable. 
Updating IP addresses in tests added in [PR #849](https://github.com/CMSgov/bcda-app/pull/849) 
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
> BCDA-6873: updated test IPs to non-routable IPs

- bcda/api/alr.go
- bcda/web/router.go
- bcda/web/router_test.go
- docker-compose.yml
https://jira.cms.gov/browse/BCDA-5355
- Disable ALR endpoints in deployed environments
The ALR export endpoints were never completed and officially released, and they should be disabled to prevent confusion.
Since the default is false, I didn't add env vars for ENABLE_ALR_ENDPOINTS in our deployed environments. However, if folks feel we should have those, I can add that separately.
Verified locally:
```sh
bcda-app: curl -X GET 'http://localhost:3000/api/v2/alr/$export' \                                                                                                                  
-H "accept: application/fhir+json" \
-H "Prefer: respond-async" \
-H "Authorization: Bearer $token"
404 page not found
bcda-app: curl -X GET 'http://localhost:3000/api/v1/alr/$export' \
-H "accept: …
```
> BCDA-5355: Disable ALR export endpoints

- db/migrations/manual/20230628-update-paca-cclf-filename.sql
https://jira.cms.gov/browse/BCDA-7211
adding db update to change CCLF filename so smoketest "refresh" step applies to both CCLF filetypes.
smoke test pipeline failing because of refresh step + paca cclf filename. 
ran migration with `rollback` to make sure syntax is correct.
> BCDA-7211: adding migration to update filename for paca test aco

- bcda/api/requests.go
- bcda/api/requests_test.go
- test/postman_test/BCDA_PAC_Postman_Smoke_Tests.postman_collection.json
https://jira.cms.gov/browse/BCDA-7197
When verifying resource type (when _type is empty), the Claim and ClaimResponse data types will only be returned if the ACO is allowed those resources and if the version of the endpoint is not V1.
The v1 endpoints for `/Group` and `/Patient` will return Claim and ClaimResponse resource types for specific ACOs; this functionality should only occur in v2 endpoints `/Group` and `/Patient`.
- added unit test for getResourceTypes
- postman tests passing after deploying API and running tests
> BCDA-7197: v1 API throws an error for REACH ACOs when "_type" parameter is not used

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
https://jira.cms.gov/browse/BCDA-7354
- Update application to support reading multiple files from `BB_CLIENT_CA_FILE`
BCDA uses mutual TLS to connect to BFD, which means that 
1. we are providing a client certificate to BFD upon connection to verify our identity
2. we are verifying BFD's certificate/identity using a Certificate Authority (CA) file
BFD is renewing their server-side TLS certificates so we need to update our CA pool to support both the old and new certificates. After BFD cuts over to the new certificate, we will be able to remove the old certificate from our trusted store.
Our application currently only supports one CA certificate, so these application changes allow us to parse and include multiple certificates in the trusted certificate pool.
The dev environment is …
> BCDA-7354: Support multiple BB client certificates

- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/api/v1/api_test.go
- bcda/api/v2/api_test.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/web/router.go
https://jira.cms.gov/browse/BCDA-7135
- added new middleware in logging.go that adds request ID and the cms ID to the context for next handler
- updated requests.go logging statements to utilize logger that is passed via context
Updating the request processing to add a logger to the context via middleware. Request ID and CMS ID can be used in future logging calls and new fields can be added to the requests context logger as needed.
Looked into database logging to possibility be included in this PR, but database is using the default `logrus.logger`. Creating a separate ticket to address that. 
Current tests pass, new test added, and ran locally to check logs & context values.
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge …
> BCDA-7135: bcda api logging improvements

- bcda/constants/test_constants.go
- bcda/suppression/suppression.go
- bcda/suppression/suppression_test.go
https://jira.cms.gov/browse/BCDA-7126
Removed outdated package in suppression.go (ioutil)
Updated unit tests for suppression.go to get to 95.2% statement coverage. 
In addition to the new tests, of which coverage is primarily added by implementing tests for the ImportSuppressionDirectory function, existing tests are modified to utilize UTC as the standard date format in case someone runs the tests locally (instead of on docker, where the default time is UTC). Future improvements to coverage on this file can be made by implementing a means to mock the repository. This would enable leaving only ~2 statements uncovered. 
> BCDA-7126 BCDA: Improve coverage for "bcda/suppression/suppression.go"

- bcda/api/requests_test.go
- bcda/responseutils/v2/writer.go
- bcda/responseutils/v2/writer_test.go
- bcda/responseutils/writer.go
- bcda/responseutils/writer_test.go
https://jira.cms.gov/browse/BCDA-7446
Changed Content-Type header for OperationOutcome error responses from application/json to application/fhir+json in both v1+v2 of the BCDA API
From: https://build.fhir.org/ig/HL7/bulk-data/export.html#response---error-status-1
According to the Bulk FHIR Export IG, OperationOutcome responses should respond with Content-Type of application/fhir+json. This is a one line change that will enhance the conformance of the BCDA application with respect to the bulk FHIR IG. 
Unit test on requests.api updated to check for the applicable content-type header in the case of an OperationOutcome response.
> BCDA-7446 - update content-type header for OperationOutcome responses to fhir+json

- bcda/service/service.go
- bcda/service/service_test.go
https://jira.cms.gov/browse/BCDA-7455
- Fix the logic for calculating new beneficiaries when the Group endpoint is called using the _since parameter
As described [in our documentation](https://bcda.cms.gov/guide.html#group-endpoint)...
>  If you use _since within the /Group endpoint, you will receive data filtered since the selected date for your existing beneficiaries AND you will receive historical data as far back as 2014 unfiltered by date for new beneficiaries. 
The logic for calculating new beneficiaries works by diffing between two CCLF files:
- `cclfFileNew` — pulls the latest CCLF file
- `cclfFileOld` — pulls the latest CCLF file with a timestamp prior to the _since parameter provided in the Group request.
This logic can sometimes incorrectly calculate the diff between the same …
> BCDA-7455: Fix new beneficiary calculation for Group endpoint

- bcda/cclf/fileprocessor.go
N/A
- Surface error messages that were not being printed/logged
This would have helped us when debugging CCLF import failures.
> Surface CCLF import error messages

- bcda/api/requests.go
- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/client/mock_bluebutton.go
- bcda/models/models.go
- bcdaworker/worker/bluebutton.go
- bcdaworker/worker/worker.go
- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-6594
Using struct `JobEnqueueArgs` in functions to replace individual arguments of `cmsID` and `jobID`, so that we can include those data points in our requests to BFD. The field of `cmsID` has been added to the model `JobEnqueueArgs`. I ended up the available struct with the additional field because many of the functions that required a changed needed some field data from JobEnqueueArgs. This reducing the number of parameters that functions expect and (hopefully) improves readability.
Our BB client has two methods `GetMetaData` and `GetPatientHashIdentifier` that do not include the job ID or CMS ID in the request headers, which results in those values being empty when the request is logged. 
Wrote new test and modified existing; all are passing.
If any …
> BCDA-6594: Improve logging when receiving BFD 400/500 status codes

- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
https://jira.cms.gov/browse/BCDA-7480
Updated the cli command `import-cclf-directory` to return the error when one occurs. If no errors come from the `importcclfdirectory` function in cli.go but a file is skipped or fails import, then a new error is created and returned to be handled by the jenkins script.
Jenkins pipeline currently always runs successfully even if cclf files are skipped or fail to import. 
Tests still passing. This jenkins pipeline does not have the option to run from a development branch, for both the pipeline and the app. This will need to be deployed and a mock test file will need to be created in order to test. 
> BCDA-7480: Add alerting when CCLF-8 import job fails to open a file

- docker-compose.test.yml
https://jira.cms.gov/browse/BCDA-7565
- Fix intermittent failures in testing
Still works locally:
```
655760bcea69   localstack/localstack:latest                                          "docker-entrypoint.sh"   29 seconds ago   Up 22 seconds (healthy)   4510-4559/tcp, 5678/tcp, 0.0.0.0:4566-4583->4566-4583/tcp   bcda-app-localstack-1
```
Should work on Jenkins (see PR checks?)
> BCDA-7565: Support multiple localstack S3 statuses in healthcheck

- bcda/api/requests.go
- bcda/api/requests_test.go
- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/models/models.go
- bcda/service/service.go
- bcda/service/service_test.go
- bcda/web/router.go
- bcdaworker/worker/worker.go
- bcdaworker/worker/worker_test.go
- log/logger.go
https://jira.cms.gov/browse/BCDA-7602
Added:
- middleware that adds a transaction ID to the incoming requests context
- request headers in the BB client to include the transaction ID
- field of `TransactionID` to model JobEnqueueArgs to pass identifier to worker/job processing
Updated:
- tests to check for log messages
- updated deprecated `ioutil`
Removed:
- unused code
Adding transaction ID to all log events between api, worker, ssas, and BFD so we can have better visibility into system health and alerts.
- added and modified tests; tests pass. 
- ran locally and verified transaction ID was added to log statements.
> BCDA-7602: Add Transaction ID to log events

- db/migrations/manual/20240131-runout-undo.sql
https://jira.cms.gov/browse/BCDA-7494
Updated Undo-runout script to refer to 2024 instead of 2023.
Will not be run until mid-late January, hence naming.
Manual verification
> BCDA-7494: Add 2024 undo-runout script

- bcdaworker/queueing/manager/que.go
- bcdaworker/worker/worker.go
- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-7610
- Added logging statement back to `WriteBBToFile`; it was removed in a [previous PR](https://github.com/CMSgov/bcda-app/commit/7398aef93051d8417d5a7a586d19c218b9df0fc2#diff-d42a7d3de9fe41fcee5e61a5d01e675b0b6e4bf0b1e0b3b1745e328cdb16386cL265) to reduce duplicate logs.
- removed unneeded `else` statement to reduce nesting in `ProcessJob`
- removed duplicate log statement in `ProcessJob`
- add the transaction ID to the log entry in `que.processJob` to ensure we still get the ID in log statements called from that function
We have been getting error alerts for HTTP 500s from the job/ endpoint. After further investigation, it appears that the job is failing when attempting to write data to the file in WriteBBToFile and the job eventually fails after a …
> BCDA-7610: Add logging to WriteBBToFile

- optout/s3_file_handler.go
N/A
- Add newlines to S3 optout logs
Lines are getting smushed together when printed in Jenkins, and I would like for that to not happen 😄 
N/A
> Add newlines to S3 optout logs

- bcda/api/requests_test.go
- bcda/auth/api.go
- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/auth/mock_provider.go
- bcda/auth/provider.go
- bcda/auth/ssas.go
- bcda/auth/ssas_test.go
- bcda/logging/middleware.go
- bcda/logging/middleware_test.go
- bcda/service/service.go
- bcda/service/service_test.go
- bcda/testUtils/utils.go
- bcda/web/router.go
- middleware/middleware.go
https://jira.cms.gov/browse/BCDA-7411
- Requests to SSAS to get a token now include a transaction ID header called `transaction-id` which contains a stringified UUID
- Fixed circular dependency by moving the transaction context key handler that adds transaction ids to incoming request's context to a separate package under `bcda/middleware`. We should eventually move more middleware functionality there, as it is split across multiple packages at the moment.
As part of an ongoing effort to improve logging capabilities, this addition will allow us to correlate logs generated in SSAS as part of a consumer request by including the transaction ID in log events.
Added test, verified existing tests pass.
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a …
> BCDA-7411: pass transaction ID to SSAS

- Dockerfiles/Dockerfile.ssas
- bcda/api/alr.go
- bcda/api/requests.go
- bcda/api/v1/api.go
- bcda/auth/middleware.go
- bcda/responseutils/v2/writer.go
- bcda/responseutils/v2/writer_test.go
- bcda/responseutils/writer.go
- bcda/responseutils/writer_test.go
- bcda/web/middleware/middleware.go
- bcda/web/middleware/ratelimit.go
- bcda/web/middleware/validation.go
- docker-compose.yml
https://jira.cms.gov/browse/BCDA-7581
- Passing logger context to response writers to be consistent with use of ctx logger elsewhere. 
- Metadata endpoint still using `log.API` since there is no relevant ctx to use
- auth middleware is using `log.AUTH` to create a ctx logger because auth middleware is processed before ctx logger middleware in the chi routers.
- MakeTestStructuredLoggerEntry duplication is because of circular dependencies in testUtils. Would like to work on package reorganization later to start eliminating circular dependencies here and elsewhere.
We updated error logging but did not switch to using the context logger (which has standardized attributes) for the FHIR response v1 and v2 writer files (writer.go).
tests updated and passing.
If any security implications apply, …
> BCDA-7581: Utilize context logger for FHIR response writers in bcda-app

- bcda/models/postgres/repository.go
- bcda/models/postgres/repository_test.go
- bcda/service/service.go
- bcda/service/service_test.go
- db/postman_fixtures.sql
https://jira.cms.gov/browse/BCDA-7799
Overall, it enforces proper performance year requirements to prevent data leaking.
Specifically, this PR:
1. Sorts results from the cclf_files query in order of performance_year THEN timestamp. This avoids issues with PY23 files coming in after PY24 and causing security issues.
2. Enforces, in getBeneficiaries and getNewAndExistingBeneficiaries, the performance year explicitly. 
3. Updates unit tests to utilize PerformanceYear
BCDA is dependent upon CCLF files to properly attribute beneficiaries to an ACO. Currently, BCDA would source the most recently timestamped CCLF file, regardless of if it is for the current or previous performance year. This is an error, and requires correction, or else claims data could be shared improperly. 
Added unit tests …
> BCDA-7799: Enforce Performance Year Requirement

- .golanglint-ci.yml
- .pre-commit-config.yaml
n/a
- The pre-commit config file has been updated to use golanglint-ci.
- golanlint-ci config file has been added with additional linters
- pinned pre-commit version to stop moving rev warnings
The pre-commit config file has been updated to use golanglint-ci so we can do linting before we commit changes and don't have to wait for CI to run. 
Linters and their descriptions: https://golangci-lint.run/usage/linters/
Ran locally.
> Update pre-commit hooks

- .golanglint-ci.yml
- .pre-commit-config.yaml
- bcda/models/postgres/postgrestest/postgrestest.go
- bcdaworker/worker/worker.go
- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-7786
- `processJob`: moved code to create job keys and update job status into its own function for testing
- `processJob`: moved file size check into `writeBBDataToFile`
- `processJob`: creating keys for each Job Key that is returned 
- `writeBBDataToFile`: changed return values to be a list of JobKeys and an error
- `writeBBDataToFile`: returning "*-error.ndjson" job key if it is created (was not being returned and did not have job keys previously)
- update to pre-commit / golangci-lint to check the pkg, as linting was failing on single files.
error.ndjson files not having job keys written to the database and middleware checks for job keys failing to [serve HTTP](https://github.com/CMSgov/bcda-app/pull/909). These changes will return the ndjson file and …
> BCDA-7786: Create Job Keys for ndjson files

- bcda/api/v1/api_test.go
- bcda/auth/middleware.go
- bcda/auth/middleware_test.go
https://jira.cms.gov/browse/BCDA-7868
Updated response codes to more appropriate responses. 
BCDA has been returning 404 errors for instances such as tokens being expired, etc, in middleware, even when the response may not be appropriate. 
Modified unit tests to handle the new statuses. 
> BCDA-7868: Update Error responses in middleware

- bcda/web/middleware/ratelimit.go
- bcda/web/middleware/ratelimit_test.go
- bcda/web/middleware/validation.go
https://jira.cms.gov/browse/BCDA-7889
Prevent same request URL from triggering duplicate job while in-progress or pending. 
Currently, it's possible to spam the same request and create duplicates of the same job. This prevents that. 
Addition of unit tests for handling this use case.
Local validation (by temporarily removing the code in router.go that only applies rate limiting in prod). 
> BCDA-7889: Prevent creation of duplicate Jobs

- bcda/web/middleware/ratelimit.go
- bcda/web/middleware/ratelimit_test.go
- bcda/web/router.go
- bcda/web/router_test.go
https://jira.cms.gov/browse/BCDA-7889
Unescapes job requests for comparisons to expand de-duplication of requests.
The first go around at this ticket blocked full $export operations, not duplicates with _since, due to one comparison using url-encoded characters, and the other using a raw string. 
Added method-level unit tests for hasDuplicates function. 
> BCDA-7889: Updating rate limiters to limit duplicate jobs. 

- bcdaworker/repository/postgres/repository.go
https://jira.cms.gov/browse/BCDA-7894
Adds additional wildcard param to ensure that -error.ndjson files are properly left uncounted. 
I forgot a % at the end of the query. 
Go behavior matches postgres query used to build the original PR. 
> BCDA-7894: Only count regular keys

- bcda/models/models.go
- bcda/models/postgres/repository.go
- bcda/models/postgres/repository_test.go
- bcda/service/service.go
- bcda/service/service_test.go
https://jira.cms.gov/browse/BCDA-7851
- Modify new beneficiaries check to compare `_since` parameter against the latest CCLF file processing date instead of attribution timestamp
Currently, the since parameter is not implemented _optimally per the spec on the Bulk FHIR IG (https://build.fhir.org/ig/HL7/bulk-data/export.html#query-parameters) . 
The current logic can lead to instances (especially around EOY) where users can receive excessive historical data due to comparisons with a previous PY file for comparing beneficiary rolls. 
The issue that ACOs have run into is that today, the timestamp is being used for comparisons, but there can be a week+ delay of when a file is generated, and when it is processed.
Instead, the new beneficiaries check should be calculated from the user's point …
> BCDA-7851: Compare _since parameter in Group endpoint with CCLF file processing date

- Makefile
N/A
Removed deadline parameter from golangci-lint
--deadline option is deprecated as of 3/19/24 (https://github.com/golangci/golangci-lint/releases/tag/v1.57.0)  and will cause CI failures 
Linter no longer throws a build error in bcda-app or bcda-ssas-app
> Remove deadline from golangci-lint

- .github/workflows/ci-workflow.yml
n/a
removing codecov from CI, since sonarqube is doing the same thing and tokenless is hitting a github api limit. 
[Link to discussion](https://github.com/codecov/feedback/issues/126#:~:text=Tokenless%20generally%20works%20by%20making%20an%20API%20call%20to%20GitHub%20to%20confirm%20that%20the%20repo%20and%20commit%20are%20the%20correct%20values.%20Making%20this%20call%20for%20thousands%20of%20repositories%20causes%20our%20GitHub%20token%20to%20hit%20the%20limit%20causing%20the%20issues%20that%20many%20of%20you%20have%20seen) on tokenless codecov generation and rate limiting. 
n/a
> remove codecov from ci

- bcdaworker/worker/worker.go
https://jira.cms.gov/browse/BCDA-8088
Added deferral of closing the bufio writer as well as returning on failure to load file. 
In troubleshooting some worker errors, it appears there may be a relation to memory issues. Before scaling up, two things stuck out to me in the worker flows: there is no defer statement for the io writer, meaning an untimely error could lead to a memory leak, and likewise there is a defer statement on a file whose potential error opening is not handled. 
Local tests pass, CI checks. 
> BCDA-8088: Prevent potential memory leaks in worker

- bcdaworker/queueing/manager/que.go
https://jira.cms.gov/browse/BCDA-8088
Ensure that pgx pool is closed/released when worker is shut down
While looking for potential spots where memory leaks could occur, it appears that while the workers are shut down, I'm unable to see an existing point where connections in a created pool are released. Our use of a deprecated queueing system has some drawbacks (and workarounds) built into it, so this may help reduce memory usage / cpu time dedicated to purging memory during a job, in conjunction with the existing PR for 8088
Passes tests locally.
> BCDA-8088: ensure connection pool is properly released

- bcdaworker/worker/worker.go
https://jira.cms.gov/browse/BCDA-8088
Ensure that buffer is flushed after each beneficiary's data is written. 
Hopefully the last of these associated with 8088! Was able to ssh into workers while observing memory explosion. This should prevent runaway buffer size during job execution by ensuring that the buffer is flushed after each execution of fhirBundleToResourceNDJSON. 
Passes local tests + verified integrity / consistency of jobs in dev environment with this branch. 
> BCDA-8088: Ensure fhirBundleToResourceNDJSON properly flushes buffer

- bcda/api/v1/api.go
- bcda/api/v1/api_test.go
https://jira.cms.gov/browse/BCDA-8120
Update gzip logic to properly identify a gzip header
>90% of requests to BCDA pass along a valid Accept-Encoding including gzip, but the current method of parsing is only recognizing "gzip" if that header exactly equals "gzip". This PR fixes that and searches for "gzip" and becomes agnostic to whatever else accompanies in that header. 
Added unit tests showing examples of headers we see in production
> BCDA-8120: Parse Accept-Encoding to search for 'gzip'

- bcdaworker/worker/worker.go
https://jira.cms.gov/browse/BCDA-8082
Added explicit log for when a job is marked as failed. 
Currently, job-based failures are picked up via a new relic query on 500 status codes. This alerting is based upon a customer requesting data for a job that has a status of Failed. We have an opportunity to be alerted and take potential corrective action to the environment, in case there's a larger issue (we rarely actually have failed jobs). 
Ignore the %d, not sure why I was treating it as a printf statement at first. latest commit has it removed. 
> BCDA-8082: Add explicit logging for when a job fails

- bcda/api/v2/api.go
- bcda/api/v2/api_test.go
- bcda/responseutils/v2/writer.go
- bcda/responseutils/writer.go
https://jira.cms.gov/browse/BCDA-8154
Updated Operation names to meet FHIR spec
Names of operations in a CapabilityStatement should refer to, conceptually, an OperationDefinition code. In the case of an operation such as Patient/$export for the bulk FHIR IG, the parameter used to instantiate the operation is export, so patient-export should be changed to export. 
There is also some odd auto-linting with this, which appears to go away after this is merged? 
Updated + passed unit tests. 
> BCDA-8154: Update capabilitystatement operation names

- bcdaworker/worker/worker.go
- bcdaworker/worker/worker_test.go
https://jira.cms.gov/browse/BCDA-7980
Instead of attempting to move files, we write a gzip-encoded file to EFS and delete the temporary files after each job key
This is the final ticket in the gzip epic, yay! 
Adds a new environment variable, COMPRESSION_LEVEL, that can be set between 1-9
Files are stored as gzip-encoded content, previous PRs ensure that the /data/ endpoint are content-encoding aware, and can return un-encoded content if requested, while ensuring significant gains for the 90+% of requests that do request gzip-encoded content.
Smoke tests + unit tests pass.
I've also performed manual validation utilizing the dev server. Throughput is as expected.
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR …
> BCDA-7980: Implement gzip compression for files stored on EFS

- .vscode/settings.json
- bcdaworker/main.go
- bcdaworker/main_test.go
N/A
Ensure that the temporary directory is emptied upon process start.
After changing the worker's logic to write to EBS volumes prior to writing compressed files to EFS, some monitoring showed that if the bcda worker process exits in a non-graceful manner, data could accumulate on the EBS volume and cause out of space errors. This PR ensures that when the process starts, the temporary directory is cleared. 
Added unit tests that pass. 
> Ensure temp directory is cleared on process start

- .github/workflows/cclf-import-dev-deploy.yml
- .github/workflows/cclf-import-test-deploy.yml
- .github/workflows/opt-out-import-dev-deploy.yml
- .github/workflows/opt-out-import-test-deploy.yml
N/A
- Remove `/bin/` directories from function zips using `zip -j`
- Rename files to `bootstrap`
Was looking at the lambda logs and saw some errors with trying to find the entrypoint. After reading the AWS documentation, I realized that it expects the zip file to have exactly one binary, which is specifically named `bootstrap` 😅
This was an oversight on my part — I thought if the handler was specified as `cclf-import` in the lambda config, it would look for that binary filename instead.
Verified in logs (doesn't complete successfully, we have another network issue to address..)
> Fix lambda handler paths

- bcda/aws/parsers.go
- bcda/aws/parsers_test.go
- bcda/lambda/cclf/main.go
- bcda/lambda/optout/main.go
https://jira.cms.gov/browse/BCDA-8208
- Fix S3 path parsing
I observed failures with the lambdas attempting to list files in S3 within the bfdeft01 prefix. This is not the correct prefix — the team-specific IAM roles can only access specific subfolders (i.e. bfdeft01/bcda, bfdeft01/dpc, etc.) so the lambdas _should_ be trying to list files within those subfolders.
When parsing the S3 prefix from the SQS event, it needs to split from the last separator instead of the first separator.
Deployed to Dev and verified successful import by uploading a file (I basically did this part of the integration test manually: https://github.com/CMSgov/bcda-app/blob/fabde15cb4f460d7398dcdfcf61205840258afcd/.github/workflows/opt-out-import-test-integration.yml#L47-L48 but fixed the filename since it's using …
> BCDA-8208: Fix S3 path parsing

- bcdaworker/queueing/manager/alr.go
- bcdaworker/queueing/manager/que_test.go
- bcdaworker/repository/mock_repository.go
- bcdaworker/repository/postgres/repository.go
- bcdaworker/repository/repository.go
- bcdaworker/worker/alr.go
- bcdaworker/worker/alr_test.go
https://jira.cms.gov/browse/BCDA-8227
- Replace completed_job_count with a count of unique job keys (based on job_key.que_job_id)
- Avoid re-processing ALR job if que job was already processed
As part of #964, I discovered that the completed_job_count was still being used as part of ALR jobs. This applies the same fix from the "normal" export jobs in #962.
Note that many different job keys can be produced by an ALR job. To simplify the determination of whether a que job was processed, I added a new "getUniqueJobKeyCount" method.
For some historical context, the ALR endpoints are not enabled in deployed environments - see #853 for more details. To avoid making a decision on whether to remove the code entirely, I am applying these changes for now to remove completed_job_count.
Unit Testing
> BCDA-8227: Remove usage of completed_job_count in ALR jobs

- test/postman_test/BCDA_PAC_Postman_Smoke_Tests.postman_collection.json
- test/postman_test/BCDA_Postman_Smoke_Tests.postman_collection.json
- test/postman_test/BCDA_Tests_Sequential.postman_collection.json
N/A
- Update maxRetries from 10 --> 20 everywhere
- Autoformat postman collection JSON files (oops sorry..)
After https://github.com/CMSgov/bcda-app/releases/tag/r226 was released, it looks like jobs are taking a _little_ bit longer to run in production. It's not clear if it's because of something in the release or tangential.
This updates maxRetries everywhere (previously, a handful of maxRetries were already updated to 20 due to intermittent issues.)
Successful smoke test on production with r226 after a series of intermittent failures.
> Increase export job waiting period for smoke tests

- optout/local_file_handler.go
- optout/s3_file_handler.go
N/A
Remove print statements
These were causing the error alarm to go off. We used to duplicate messages to stdout and to the formatted JSON Logger since only stdout would be printed in Jenkins logs. Since we are running in lambda now, we can remove that.
Unit Testing
> Remove stdout print statements

- bcda/auth/ssas.go
- bcda/bcdacli/cli.go
- bcda/bcdacli/cli_test.go
- bcda/models/models.go
- bcda/models/models_test.go
- bcda/models/postgres/repository_test.go
- bcda/models/termination.go
- bcda/web/router_test.go
- db/migrations/migrations_test.go
https://jira.cms.gov/browse/BCDA-8162
Updated cli references + models to blacklist, updated to denylist.
As part of making BCDA's code more inclusive, we are removing the terms "blacklist" and "whitelist." 
Smoke tests + unit tests passing. Note, there is going to be an associated PR to the jenkins job for the denylist that references the new cli command name.
> BCDA-8162: Update cli commands to be more inclusive.

- .github/workflows/cclf-import-test-integration.yml
- .github/workflows/opt-out-import-test-integration.yml
https://jira.cms.gov/browse/BCDA-7900
- Copied opt-out import integration test to CCLF workflow
- Made some edits to support CCLF imports
After getting the opt-out import integration tests merged, realized that it wasn't applied to the CCLF import workflow. Now that we are relying on the CCLF lambda, we want to ensure future changes do not break expected functionality.
Updated integration test works successfully.
> BCDA-7900: Add verification to CCLF import integration test

- bcda/suppression/suppression.go
- bcda/suppression/suppression_test.go
https://jira.cms.gov/browse/BCDA-8231
Logging statements during opt out ingestion will now output a count when completed successfully.
These log statements will support a dashboard that can be used team-wide to view metrics/stats on the latest file import.
Unit test modified + passing and verified that logs were in splunk after deploying dev changes to test environment. 
Log message: 
```
{"application":"bcda-test-opt-out-import",
"created_opt_ins_count":2,
"created_opt_outs_count":1,
"environment":"test",
"file":"/home/runner/work/bcda-app/bcda-app/bcda/suppression/suppression.go:152",
"func":"github.com/CMSgov/bcda-app/bcda/suppression.OptOutImporter.ImportSuppressionData",
"level":"info",
"msg":"",
"time":"2024-08-09T21:17:04.729002492Z"}
```
> BCDA-8231: Log additional Opt Out details for Splunk dashboard

- .github/workflows/ci-workflow.yml
n/a
Bumped actions for artifact upload and down from v2 -> v3.
Github actions/<upload|download>-artifact@v1/2 are deprecated and will result in our CI failing. [Release announcement](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/). Originally bumped to v4, but node20 is required. Can bump the version when PLT-338 is completed. V3 will be deprecated on November 30, 2024, so the upgrade to v3 is temporary to keep PRs unblocked.
Ran CI successfully.
> Update Github Actions Upload and Download Artifact from V2 to V3

- bcda/client/bluebutton.go
- bcda/client/bluebutton_test.go
https://jira.cms.gov/browse/BCDA-8453
- Removed query parameters from POST operations to BFD endpoints, since they are now sent in the body.
- Also removed a header that's no longer in use, per this page: https://github.com/CMSgov/beneficiary-fhir-data/wiki/Making-Requests-to-BFD
Changes were made so that we are no longer sending unnecessary parameters with our requests to BFD. 
Unit tests pass and smoke tests pass.
> BCDA-8453: Remove query params from POST requests to BFD

- bcda/cclf/parser.go
- bcda/cclf/parser_test.go
- bcda/lambda/cclf/main.go
- bcda/lambda/cclf/main_test.go
https://jira.cms.gov/browse/BCDA-8405
Added the main entry to the CCLF lambda.
Added the logic flow for checking if the SQS event contains a CSV file path, or CCLF.
Renamed CCLF lambda functions to attribution agnostic.
Added parser functions for checking CSV file.
Added testing for CSV parser functions.
These changes will be the entry for the lambda changes in order to make the CCLF lambda more agonistic to an attribution lambda.
This PR is a part of a larger group of PR's that will come later. Some of these entries don't function properly, such as the CSVImporter. Therefore this PR is more-or less a check for making sure the functionality is up to standards for the team.
> Draft: CCLF lambda changes

- bcdaworker/queueing/river.go
https://jira.cms.gov/browse/BCDA-8523
Adjust query that counts total unprocessed jobs.
This query is what determines the cloudwatch alarms for total number of unprocessed jobs.  Previously que-go would just delete finished jobs, while river does not.
Local testing and linting.
> BCDA-8523: Adjust query that counts total number of unprocessed jobs

- bcda/client/bluebutton.go
- bcda/client/fhir/client.go
https://jira.cms.gov/browse/BCDA-8529
Updated logic within getResponse. Removed a unnecessary nil check. Reevaluated some error checking with request responses.
Needed to try and see if getResponse logic was responsible for potential memory leaks. 
Unit-test suite runs.
> BCDA-8529: Fix logic for getResponse method

- .github/workflows/build-ami.yml
https://jira.cms.gov/browse/BCDA-8635
Migration of platinum image creation from Jenkins -> Github Workflows.
Made as part of the larger effort to deprecate Jenkins. This requires another PR in the ops repo that must also be merged: https://github.com/CMSgov/bcda-ops/pull/1146 
Workflow passes and confirmed AMI is available in EC2. (latest run will fail until ops repo is merged, but successful run can be found here: https://github.com/CMSgov/bcda-app/actions/runs/13039689810/job/36378517357?pr=1031)
> BCDA-8635: Migrate Platinum AMI From Jenkins to Github Workflows

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8839
Add smoketests to deploy process, add longer sleep, get all worker instances and sort by launchtime for verification.
Smoketest work seems to be wrapping up so we might as well get that in there now.  Longer sleep (😢) as instances are taking a while to refresh.  Better getting of worker instance id to help as well.
Local linting and testing.
> BCDA-8839: Add longer sleep, add smoke-tests

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8839
Add needed smoke test vars to deploy workflow and autodeploy to dev env.
Deploy workflow was failing due to missing vars
Local linting and testing
> BCDA-8839: Add needed smoke test vars to deploy workflow

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/BCDA-8839
Break off slack alerts to new deploy job
Last deploy was succesful however it ran the failure slack block.  I believe this is due to the needs not being available.
Local linting and testing
> BCDA-8839: Break off slack alerts to new deploy job

- .github/workflows/build-and-package-all.yml
- .github/workflows/build-and-package-bcda.yml
- .github/workflows/deploy-all.yml
- .github/workflows/smoke-tests.yml
- .github/workflows/tag-and-release.yml
https://jira.cms.gov/browse/BCDA-8888
Decouple smoke tests from full deploy alert.  Reduce number of slack alerts (noisy).  Add build and package on push to main.  Add cron autodeploy daily.
Small adjustments to the deploy process we think would be useful as we kick the tires.
Test the workflows in dev.
> BCDA-8888: Adjust deploy workflow deps, adjust slack alerts

- .github/workflows/smoke-tests.yml
https://jira.cms.gov/browse/BCDA-8637
Only run SSAS smoke tests in dev and test
These were failing in opensbx and prod.  Checking back on the jenkins scripts and we notice they are skipped there.
Local testing and linting, testing workflow in dev.
> BCDA-8637: Only run SSAS tests in dev and test

- .github/workflows/opt-out-import-test-integration.yml
- .github/workflows/refresh_test_attribution.yml
- bcda/lambda/optout/main.go
https://jira.cms.gov/browse/BCDA-8637
creating github action to refresh attribution data weekly.
Pulled the refresh out of smoke tests to reduce number of times it runs and so we can expand upon this for PY transitions or run it ad-hoc without smoke tests.
Works in all envs, verified in database and multiple successful test runs: https://github.com/CMSgov/bcda-app/actions/runs/13996655667/job/39193385477?pr=1070
> BCDA-8637: refresh attribution data GHA

- .golangci.yml
- Makefile
https://jira.cms.gov/browse/BCDA-8926
Upgrade golangci-lint to v2.
Linting is failing in workflows due to new version.
Local validation of new run line
> BCDA-8926: Upgrade golangci-lint to v2

- Makefile
- README.md
Ticket to set up local environment:
https://jira.cms.gov/browse/BCDA-8897
- Removed an outdated reference in the readme
- Increased time to wait on the api booting up before throwing an error when loading fixtures
These changes are made in response to some small obstacles I faced while setting up the api locally.
The readme referenced a docker service that has been removed.
The api service time-to-wait had to be increased since `load-fixtures` would fail before completing.
I reset my local environment and ran through the setup steps again, including running `load-fixtures` and encountered no errors.
> BCDA-8897: Make small updates to readme and build to address obstacles to local setup

- bcda/api/requests_test.go
- bcda/service/service.go
- bcda/service/service_test.go
https://jira.cms.gov/browse/BCDA-8509
- the method `GetJobAndKeys` in `bcda/service/service.go` now fetches job keys even when the job does not have the "Completed" status
- tests are added to validate the behavior of `GetJobAndKeys`
- tests are added to validate the behavior of the "X-Progress" header
The method `GetJobAndKeys` in `bcda/service/service.go` only fetched and returned job keys if the job had the "Completed" status. This contradicted the comment just above the status check, which implied that the keys should only be fetched if the job _didn't_ have the "Completed" status. Since the keys seemed to be required for jobs with the Completed status and otherwise, I simply removed the check.
- I created tests that check the conditions of this ticket, as well as other conditions
- I …
> BCDA-8509: InProgress JobStatus response always shows 0%

- Dockerfiles/Dockerfile.bcda_prod
- Dockerfiles/Dockerfile.bcdaworker_prod
- Makefile
- README.md
- docker-compose.debug.yml
- docker-compose.yml
https://jira.cms.gov/browse/BCDA-8975
- fixed a problem with the worker docker container by including the `shared_files` directory in its file system
- added a docker volume to share files in the FHIR_ PAYLOAD_DIR between the api and worker containers
- adjusted the debug docker compose file to enable debugging with our new docker setup, and updated docs to make it user-friendly
The changes from the first BCDA-8975 PR more clearly defined the file system of the docker containers, and the bind mount to the host file system was removed. I missed that the `share_files` directory was required by the worker container, which caused it to fail when it picked up jobs. Adding the directory explicitly into the container should address this problem. **On a related note, we should keep an eye out for …
> BCDA-8975: Fix worker docker container and enable debugging

- bcda/api/requests.go
- bcda/service/service.go
- bcda/service/service_test.go
- bcdaworker/queueing/worker_prepare_test.go
- bcdaworker/queueing/worker_types/prepare_types.go
https://jira.cms.gov/browse/BCDA-9064
Add ACO config values (data types) to prepare job args
Currently prepare jobs are failing on not being able to find ACO configs.  I believe this is due to worker instance not having aco config.yml available.  This would also explain how it got past unit testing, docker composet smoke tests, but failed on actual public url smoke tests.
Local linting and testing.
> BCDA-9064: Add aco config to prepare job data

- bcda/health/health.go
- bcda/web/router.go
- bcdaworker/main.go
- bcdaworker/queueing/river.go
https://jira.cms.gov/browse/BCDA-9092
Re-ordered middleware to make sure that both:
- transaction id is available when parsing jwt tokens
- auth data is available when setting up the structured logger
The recent changes to logging (making sure transaction_id is present when making requests from bcda api -> ssas) broke the logging of ACO ID on various splunk alerts.
Local linting, testing.
> BCDA-9092: Adjust order of request mw to make sure AD info is available

- bcda/api/requests.go
- bcda/service/service.go
- bcda/service/service_test.go
- bcdaworker/queueing/worker_prepare.go
- bcdaworker/queueing/worker_prepare_test.go
- bcdaworker/queueing/worker_types/prepare_types.go
https://jira.cms.gov/browse/BCDA-9102
Not represented in this PR:
- Added param store values for BCDA_WORKER_CONFIG_PATH to point at (cloned) worker config.yml files (also in param store).  This doubles the config.yml files we have to keep in sync but was the easiest path forward.  (The alternative is messing around with an archaic script in bcda-ops, something that we have spent a lot of time trying to refactor as part of our AL2023 work).
In this PR:
- Add error checks for when we fail to load ACO Config appropriately.
- Add tests for the above and update existing.
- Some cleanup of now unused functions.
Previously if we failed to load ACO Configs we would just silently ignore the related logic blocks.  This included important logic checks.
Local linting and testing.
> BCDA-9102: Make sure config is available for worker instance

- .github/workflows/fhirscan.yml
https://jira.cms.gov/browse/BCDA-9060
Updated the FHIR Scan workflow to point at the dev deployment instead of sandbox
initially, i pointed at sandbox to get it working because there were some issues with dev. But it's all good now, and this makes more sense to point at dev.
Go to the FHIR Scan workflow https://github.com/CMSgov/bcda-app/actions/workflows/fhirscan.yml, click "Run workflow", select a branch (this PR is `colby/BCDA-9060`), and then run. then make sure it passes
> BCDA-9060: Update FHIR Scan to point to dev

- .pre-commit-config.yaml
https://jira.cms.gov/browse/BCDA-9225
Removed args that are unneeded and don't play nicely with newer versions of golangci-lint pre-commit hook
> BCDA-9225: remove superfluous precommit args

- bcda/auth/client/ssas.go
- bcda/auth/client/ssas_test.go
- bcda/health/health.go
https://jira.cms.gov/browse/BCDA-9107
- pointed the bcda-app `/_health` check endpoint to hit the ssas `_/health` check endpoint instead of `/introspect`
Tested locally by curling `localhost:3000/_health`
> BCDA-9107: use ssas health endpoint in app health check

- bcda/client/bluebutton.go
- bcda/constants/constants.go
- bcdaworker/queueing/worker_prepare.go
- bcdaworker/worker/bluebutton.go
- bcdaworker/worker/worker.go
https://jira.cms.gov/browse/BCDA-9138
- Point the /demo endpoint at BFD V3 (instead of V2)
- fetch bluebutton (FHIR) ID for all resources except claim/claimResponse (instead of looking at adjudication-level)
- changes for only v3:
- Do not pass the `excludeSAMHSA` for v3
- Use Transaction time as lastupdated param
- update patient ID lookup to only require mbi match
Change was added to make \demo endpoint work for connectathon. when we implement the real v3, we'll probably want to refactor the code.
Test the /$export and /jobs endpoints for demo and v2:
- http://localhost:3000/api/demo/Group/all/$export
- http://localhost:3000/api/demo/Patient/$export?_typeFilter=ExplanationOfBenefit%3F_tag%3DAdjudicated
- http://localhost:3000/api/v2/Group/all/$export
- …
> BCDA-9138: Move /demo to BFD v3

- bcda/api/v1/api.go
- bcda/api/v1/api_test.go
- bcda/auth/middleware_test.go
https://jira.cms.gov/browse/BCDA-9298:
added tests that were missing from previous PR: https://github.com/CMSgov/bcda-app/pull/1183
Added tests and updated endpoint to check if file exists before taking any other action. HTTP 5XXs alerting still occurring due to a missing return statement to check if the file is gzip encoded.
> BCDA-9298: Serve data endpoint test updates + file checks

- .github/workflows/deploy-all.yml
- .github/workflows/dev-daily-autodeploy.yml
- .github/workflows/package-rpms.yml
https://jira.cms.gov/browse/BCDA-9367
Added a new workflow to address issues with the daily dev deploy from main.
The daily dev deploy to main has been having troubles since our greenfield migration.  We are no longer getting the latest changes deployed to dev daily.  Adding this new workflow should address this.  It felt better to create a new workflow then to try to finagle existing workflows (which would have involved a lot of if else checks and such).
Testing workflow in PR pushes.  (Successful run: https://github.com/CMSgov/bcda-app/actions/runs/17082274241)
> BCDA-9367: Add new auto deploy to dev workflow

- .dockerignore
- .github/workflows/cclf-import-integration-test.yml
- .github/workflows/opt-out-import-integration-test.yml
https://jira.cms.gov/browse/BCDA-9397
Adjust cclf import and opt-out lambda integration test workflows to make sure the verify process works when called via on_dispatch.
Recent manual runs of both have skipped the verify step: https://github.com/CMSgov/bcda-app/actions/runs/17273221595
Workflow run on push: 
- cclfhttps://github.com/CMSgov/bcda-app/actions/runs/17274630077/job/49028241943?pr=1202 (cclf import)
> BCDA-9397: Make sure lambda workflow verify steps run on call

- .github/workflows/deploy-all.yml
https://jira.cms.gov/browse/PLT-1347
terraform_gf was renamed to terraform
To maintain standard directory naming across app repos.
see plan
> [PLT-1347] Rename the terraform_gf directory to terraform, post-migration
